// Auto-generated by boardsmith-fw for STM32 target
// HIR version: 1.1.0
#include "stm32f1xx_hal.h"

void init_all_peripherals(void) {
    // TODO: implement per-component init
}

int main(void) {
    HAL_Init();
    init_all_peripherals();
    while (1) { }
}
