# SPDX-License-Identifier: AGPL-3.0-or-later
"""Intent Code Generator — compiles IntentRoot into C application loop.

Translates declarative firmware intent (what to do) into concrete C code
that runs on top of the HIR-generated driver layer.

    IntentRoot + target → main_intent.c
"""

from __future__ import annotations

import re
from dataclasses import dataclass

import yaml

from boardsmith_fw.models.intent_schema import IntentRoot, IntentTask


@dataclass
class IntentCodegenResult:
    files: list[tuple[str, str]]  # [(path, content)]
    warnings: list[str]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def compile_intent(intent_yaml: str, target: str = "esp32") -> IntentCodegenResult:
    """Compile an intent YAML string into C source files."""
    raw = yaml.safe_load(intent_yaml)
    root = IntentRoot(**raw)
    return _generate(root, target)


def compile_intent_from_file(path, target: str = "esp32") -> IntentCodegenResult:
    """Compile an intent YAML file into C source files."""
    from pathlib import Path
    text = Path(path).read_text(encoding="utf-8")
    return compile_intent(text, target)


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def _generate(root: IntentRoot, target: str) -> IntentCodegenResult:
    fw = root.firmware
    warnings: list[str] = []

    if not fw.tasks:
        warnings.append("No tasks defined in intent — generating empty main loop")

    # Separate periodic tasks from triggered tasks
    periodic = [t for t in fw.tasks if t.every and not t.trigger]
    triggered = [t for t in fw.tasks if t.trigger]

    if target in ("stm32",):
        content = _gen_stm32(fw.name, periodic, triggered)
    elif target in ("rp2040",):
        content = _gen_rp2040(fw.name, periodic, triggered)
    elif target in ("nrf52",):
        content = _gen_nrf52(fw.name, periodic, triggered)
    else:  # esp32/esp32c3 default
        content = _gen_esp32(fw.name, periodic, triggered)

    files = [("main_intent.c", content)]

    # Also emit a human-readable intent summary as a comment file
    summary = _gen_summary(root)
    files.append(("intent_summary.md", summary))

    return IntentCodegenResult(files=files, warnings=warnings)


# ---------------------------------------------------------------------------
# ESP32 (FreeRTOS) generator
# ---------------------------------------------------------------------------

def _gen_esp32(name: str, periodic: list[IntentTask], triggered: list[IntentTask]) -> str:
    safe_name = _sanitize(name)
    lines = [
        f"/* boardsmith-fw intent: {name} — ESP32/FreeRTOS */",
        "/* Generated by boardsmith-fw intent compiler */",
        "/* Edit intent.yaml to change behaviour, not this file */",
        "",
        '#include "freertos/FreeRTOS.h"',
        '#include "freertos/task.h"',
        '#include "esp_log.h"',
        '#include "drivers.h"  /* HIR-generated driver layer */',
        "",
        f'static const char *TAG = "{safe_name}";',
        "",
    ]

    # Data structs for read tasks
    for task in periodic:
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            lines += _emit_data_struct(struct_name, read.values)

    # Handler prototypes for triggered tasks
    for task in triggered:
        lines.append(f"static void {_sanitize(task.name)}_handler(void *data);")
    if triggered:
        lines.append("")

    # Periodic task functions
    for task in periodic:
        lines += _emit_esp32_task(task, triggered)

    # Handler implementations for triggered tasks
    for task in triggered:
        lines += _emit_esp32_handler(task)

    # app_main
    lines += [
        "void app_main(void) {",
        f'    ESP_LOGI(TAG, "Starting {name}");',
        "    drivers_init();  /* HIR-generated init sequence */",
        "",
    ]
    for task in periodic:
        task_fn = f"{_sanitize(task.name)}_task"
        stack = 4096
        lines.append(f'    xTaskCreate({task_fn}, "{task.name}", {stack}, NULL, 5, NULL);')

    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


def _emit_data_struct(name: str, values: list[str]) -> list[str]:
    if not values:
        return []
    lines = ["typedef struct {"]
    for v in values:
        lines.append(f"    float {_sanitize(v)};")
    lines += [f"}} {name}_t;", ""]
    return lines


def _emit_esp32_task(task: IntentTask, triggered: list[IntentTask]) -> list[str]:
    fn_name = f"{_sanitize(task.name)}_task"
    delay_ms = task.every_ms()
    lines = [
        f"static void {fn_name}(void *arg) {{",
        f"    const TickType_t period = pdMS_TO_TICKS({delay_ms});",
        "    TickType_t last_wake = xTaskGetTickCount();",
        "",
        "    for (;;) {",
    ]

    # Read actions
    for read in task.read:
        struct_name = _sanitize(read.store_as or read.component.lower())
        cmp = _sanitize(read.component.lower())
        lines.append(f"        {struct_name}_t {struct_name} = {{0}};")
        for val in read.values:
            lines.append(f"        {struct_name}.{_sanitize(val)} = {cmp}_read_{_sanitize(val)}();")
        lines.append(f'        ESP_LOGI(TAG, "{task.name}: read {read.component}");')

    # Other actions
    for action in task.parsed_actions():
        lines += _emit_action_esp32(action, task)

    # Trigger downstream tasks (call their handlers directly)
    downstream = [t for t in triggered if t.trigger == task.name]
    for dep in downstream:
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            lines.append(f"        {_sanitize(dep.name)}_handler(&{struct_name});")

    lines += [
        "",
        "        vTaskDelayUntil(&last_wake, period);",
        "    }",
        "}",
        "",
    ]
    return lines


def _emit_esp32_handler(task: IntentTask) -> list[str]:
    """Emit a handler function body for a triggered task."""
    fn = f"{_sanitize(task.name)}_handler"
    lines = [
        f"static void {fn}(void *data) {{",
        "    (void)data;",
    ]
    for action in task.parsed_actions():
        lines += [f"    {ln}" for ln in _emit_action_esp32(action, task)]
    lines += ["}", ""]
    return lines


def _emit_action_esp32(action, task: IntentTask) -> list[str]:
    a = action.action
    args = action.args

    if a == "serial.print":
        text = args.get("text", "")
        return [f'        ESP_LOGI(TAG, "{_escape(text)}");']

    if a == "flash.append":
        device = args.get("device", "flash")
        data = args.get("data", "data")
        fmt = args.get("format", "binary")
        return [
            f"        /* flash.append: {device} fmt={fmt} */",
            f"        flash_append(&{_sanitize(data)}, sizeof({_sanitize(data)}));",
        ]

    if a == "display.show":
        device = args.get("device", "display")
        text = args.get("text", "")
        return [
            f"        /* display.show: {device} */",
            f'        display_print("{_escape(text)}");',
        ]

    if a == "mqtt.publish":
        topic = args.get("topic", "data")
        data = args.get("data", "data")
        return [
            f'        mqtt_publish("{_escape(topic)}", &{_sanitize(data)}, sizeof({_sanitize(data)}));',
        ]

    if a == "gpio.set":
        pin = args.get("pin", "0")
        value = args.get("value", "1")
        return [f"        gpio_set_level(GPIO_NUM_{pin}, {value});"]

    if a == "led.set":
        led_id = args.get("id", "0")
        value = args.get("value", "1")
        return [f"        led_set({led_id}, {value});"]

    if a == "ble.notify":
        uuid = args.get("uuid", "0")
        data = args.get("data", "data")
        return [f"        ble_notify_char({uuid}, &{_sanitize(data)}, sizeof({_sanitize(data)}));"]

    if a in ("http.get", "http.post"):
        url = args.get("url", "")
        method = "GET" if a == "http.get" else "POST"
        return [
            f"        /* HTTP {method}: {_escape(url)} */",
            f'        http_{method.lower()}("{_escape(url)}", NULL, 0, NULL, 0);',
        ]

    if a == "i2c.write":
        addr = args.get("addr", "0x00")
        data = args.get("data", "data")
        return [f"        i2c_write_to({addr}, &{_sanitize(data)}, sizeof({_sanitize(data)}));"]

    if a == "spi.transfer":
        cs = args.get("cs", "GPIO_NUM_5")
        data = args.get("data", "data")
        return [f"        spi_transfer({cs}, &{_sanitize(data)}, sizeof({_sanitize(data)}));"]

    # Unknown action — emit a descriptive comment, no TODO
    return [f"        /* Unimplemented action: '{a}' — add custom code here */"]


# ---------------------------------------------------------------------------
# STM32 (HAL + bare-metal super-loop) generator
# ---------------------------------------------------------------------------

def _gen_stm32(name: str, periodic: list[IntentTask], triggered: list[IntentTask]) -> str:
    safe_name = _sanitize(name)
    lines = [
        f"/* boardsmith-fw intent: {name} — STM32/HAL */",
        "/* Generated by boardsmith-fw intent compiler */",
        "",
        '#include "main.h"',
        '#include "stm32f4xx_hal.h"',
        '#include "drivers.h"',
        "",
        f"/* {safe_name} application loop */",
        "",
    ]

    # Data structs
    for task in periodic:
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            lines += _emit_data_struct(struct_name, read.values)

    # Forward declarations
    for task in periodic:
        lines += [f"static void run_{_sanitize(task.name)}(void);", ""]
    for task in triggered:
        lines += [f"static void {_sanitize(task.name)}_handler(void *data);", ""]
    lines.append("")

    lines += [
        "void app_run(void) {",
        "    drivers_init();",
        "",
    ]
    for task in periodic:
        lines.append(f"    uint32_t tick_{_sanitize(task.name)} = 0;")

    lines += [
        "",
        "    for (;;) {",
        "        uint32_t now = HAL_GetTick();",
        "",
    ]
    for task in periodic:
        delay_ms = task.every_ms()
        fn = f"run_{_sanitize(task.name)}"
        t = f"tick_{_sanitize(task.name)}"
        lines += [
            f"        if (now - {t} >= {delay_ms}u) {{",
            f"            {t} = now;",
            f"            {fn}();",
            "        }",
            "",
        ]
    lines += ["    }", "}", ""]

    # Task implementations
    for task in periodic:
        fn = f"run_{_sanitize(task.name)}"
        lines += [f"static void {fn}(void) {{"]
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            cmp = _sanitize(read.component.lower())
            lines.append(f"    {struct_name}_t {struct_name} = {{0}};")
            for val in read.values:
                lines.append(f"    {struct_name}.{_sanitize(val)} = {cmp}_read_{_sanitize(val)}();")
        for action in task.parsed_actions():
            for line in _emit_action_stm32(action):
                lines.append(f"    {line}")
        downstream = [t for t in triggered if t.trigger == task.name]
        for dep in downstream:
            for read in task.read:
                struct_name = _sanitize(read.store_as or read.component.lower())
                lines.append(f"    {_sanitize(dep.name)}_handler(&{struct_name});")
        lines += ["}", ""]

    # Handler implementations for triggered tasks
    for task in triggered:
        fn = f"{_sanitize(task.name)}_handler"
        lines += [f"static void {fn}(void *data) {{", "    (void)data;"]
        for action in task.parsed_actions():
            for line in _emit_action_stm32(action):
                lines.append(f"    {line}")
        lines += ["}", ""]

    return "\n".join(lines)


def _emit_action_stm32(action) -> list[str]:
    a = action.action
    args = action.args
    if a == "serial.print":
        text = args.get("text", "")
        return [f'HAL_UART_Transmit(&huart2, (uint8_t*)"{_escape(text)}\\r\\n", '
                f'strlen("{_escape(text)}") + 2, 100);']
    if a == "flash.append":
        data = args.get("data", "data")
        return [f"flash_append(&{_sanitize(data)}, sizeof({_sanitize(data)}));"]
    if a == "display.show":
        text = args.get("text", "")
        return [f'display_print("{_escape(text)}");']
    if a == "mqtt.publish":
        topic = args.get("topic", "data")
        data = args.get("data", "data")
        return [f'mqtt_publish("{_escape(topic)}", &{_sanitize(data)}, sizeof({_sanitize(data)}));']
    if a == "gpio.set":
        pin = args.get("pin", "0")
        value = args.get("value", "1")
        return [f"HAL_GPIO_WritePin(GPIOA, GPIO_PIN_{pin}, GPIO_PIN_{'SET' if value == '1' else 'RESET'});"]
    if a == "led.set":
        led_id = args.get("id", "0")
        value = args.get("value", "1")
        return [f"led_set({led_id}, {value});"]
    if a == "ble.notify":
        uuid = args.get("uuid", "0")
        data = args.get("data", "data")
        return [f"ble_notify_char({uuid}, &{_sanitize(data)}, sizeof({_sanitize(data)}));"]
    # Unknown action — descriptive comment, no TODO
    return [f"/* Unimplemented action: '{a}' — add custom code here */"]


# ---------------------------------------------------------------------------
# RP2040 (Pico SDK) generator
# ---------------------------------------------------------------------------

def _gen_rp2040(name: str, periodic: list[IntentTask], triggered: list[IntentTask]) -> str:
    lines = [
        f"/* boardsmith-fw intent: {name} — RP2040/Pico SDK */",
        "/* Generated by boardsmith-fw intent compiler */",
        "",
        '#include "pico/stdlib.h"',
        '#include "pico/time.h"',
        '#include "drivers.h"',
        "",
    ]

    for task in periodic:
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            lines += _emit_data_struct(struct_name, read.values)

    # Repeating timer callbacks
    for task in periodic:
        fn = f"{_sanitize(task.name)}_callback"
        delay_ms = task.every_ms()
        lines += [
            f"bool {fn}(struct repeating_timer *t) {{",
            "    (void)t;",
        ]
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            cmp = _sanitize(read.component.lower())
            lines.append(f"    {struct_name}_t {struct_name} = {{0}};")
            for val in read.values:
                lines.append(f"    {struct_name}.{_sanitize(val)} = {cmp}_read_{_sanitize(val)}();")
        for action in task.parsed_actions():
            if action.action == "serial.print":
                text = action.args.get("text", "")
                lines.append(f'    printf("{_escape(text)}\\n");')
            elif action.action == "flash.append":
                data = action.args.get("data", "data")
                lines.append(f"    flash_append(&{_sanitize(data)}, sizeof({_sanitize(data)}));")
            elif action.action == "display.show":
                text = action.args.get("text", "")
                lines.append(f'    display_print("{_escape(text)}");')
            elif action.action == "mqtt.publish":
                topic = action.args.get("topic", "data")
                data = action.args.get("data", "data")
                lines.append(f'    mqtt_publish("{_escape(topic)}", &{_sanitize(data)}, sizeof({_sanitize(data)}));')
            elif action.action == "gpio.set":
                pin = action.args.get("pin", "0")
                value = action.args.get("value", "1")
                lines.append(f"    gpio_put({pin}, {value});")
            elif action.action == "led.set":
                led_id = action.args.get("id", "0")
                value = action.args.get("value", "1")
                lines.append(f"    led_set({led_id}, {value});")
            else:
                lines.append(f"    /* Unimplemented action: '{action.action}' — add custom code here */")
        # Call handlers for triggered tasks
        downstream = [t for t in triggered if t.trigger == task.name]
        for dep in downstream:
            for read in task.read:
                struct_name = _sanitize(read.store_as or read.component.lower())
                lines.append(f"    {_sanitize(dep.name)}_handler(&{struct_name});")
        lines += ["    return true;", "}", ""]

    # Handler functions for triggered tasks
    for task in triggered:
        fn = f"{_sanitize(task.name)}_handler"
        lines += [f"static void {fn}(void *data) {{", "    (void)data;"]
        for action in task.parsed_actions():
            if action.action == "serial.print":
                text = action.args.get("text", "")
                lines.append(f'    printf("{_escape(text)}\\n");')
            elif action.action == "flash.append":
                data_name = action.args.get("data", "data")
                lines.append(f"    flash_append({_sanitize(data_name)}, sizeof(*{_sanitize(data_name)}));")
            elif action.action == "display.show":
                text = action.args.get("text", "")
                lines.append(f'    display_print("{_escape(text)}");')
            elif action.action == "mqtt.publish":
                topic = action.args.get("topic", "data")
                data = action.args.get("data", "data")
                lines.append(f'    mqtt_publish("{_escape(topic)}", &{_sanitize(data)}, sizeof({_sanitize(data)}));')
            elif action.action == "gpio.set":
                pin = action.args.get("pin", "0")
                value = action.args.get("value", "1")
                lines.append(f"    gpio_put({pin}, {value});")
            elif action.action == "led.set":
                led_id = action.args.get("id", "0")
                value = action.args.get("value", "1")
                lines.append(f"    led_set({led_id}, {value});")
            else:
                lines.append(f"    /* Unimplemented action: '{action.action}' — add custom code here */")
        lines += ["}", ""]

    lines += [
        "int main(void) {",
        "    stdio_init_all();",
        "    drivers_init();",
        "",
    ]
    for task in periodic:
        fn = f"{_sanitize(task.name)}_callback"
        delay_ms = task.every_ms()
        t_var = f"timer_{_sanitize(task.name)}"
        lines += [
            f"    struct repeating_timer {t_var};",
            f"    add_repeating_timer_ms(-{delay_ms}, {fn}, NULL, &{t_var});",
        ]
    lines += [
        "",
        "    for (;;) {",
        "        tight_loop_contents();",
        "    }",
        "    return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# nRF52 (Zephyr RTOS) generator
# ---------------------------------------------------------------------------

def _gen_nrf52(name: str, periodic: list[IntentTask], triggered: list[IntentTask]) -> str:
    safe_name = _sanitize(name)
    lines = [
        f"/* boardsmith-fw intent: {name} — nRF52/Zephyr */",
        "/* Generated by boardsmith-fw intent compiler */",
        "",
        '#include <zephyr/kernel.h>',
        '#include <zephyr/logging/log.h>',
        '#include "drivers.h"',
        "",
        f'LOG_MODULE_REGISTER({safe_name}, LOG_LEVEL_INF);',
        "",
    ]

    # Data structs
    for task in periodic:
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            lines += _emit_data_struct(struct_name, read.values)

    # Timer work handlers
    for task in periodic:
        fn = f"{_sanitize(task.name)}_work_handler"
        lines += [
            f"static void {fn}(struct k_work *work) {{",
        ]
        for read in task.read:
            struct_name = _sanitize(read.store_as or read.component.lower())
            cmp = _sanitize(read.component.lower())
            lines.append(f"    {struct_name}_t {struct_name} = {{0}};")
            for val in read.values:
                lines.append(f"    {struct_name}.{_sanitize(val)} = {cmp}_read_{_sanitize(val)}();")
            lines.append(f'    LOG_INF("{task.name}: read {read.component}");')
        for action in task.parsed_actions():
            lines += _emit_action_nrf52(action)
        # Trigger downstream
        downstream = [t for t in triggered if t.trigger == task.name]
        for dep in downstream:
            for read in task.read:
                struct_name = _sanitize(read.store_as or read.component.lower())
                lines.append(f"    {_sanitize(dep.name)}_handler(&{struct_name});")
        lines += ["}", ""]

    # K_WORK_DEFINE macros
    for task in periodic:
        fn = f"{_sanitize(task.name)}_work_handler"
        lines.append(f"K_WORK_DEFINE({_sanitize(task.name)}_work, {fn});")
    lines.append("")

    # Timer expiry functions
    for task in periodic:
        timer_fn = f"{_sanitize(task.name)}_timer_expiry"
        lines += [
            f"static void {timer_fn}(struct k_timer *timer) {{",
            f"    k_work_submit(&{_sanitize(task.name)}_work);",
            "}",
        ]
    lines.append("")

    # Timer definitions
    for task in periodic:
        timer_fn = f"{_sanitize(task.name)}_timer_expiry"
        lines.append(f"K_TIMER_DEFINE({_sanitize(task.name)}_timer, {timer_fn}, NULL);")
    lines.append("")

    # Triggered handler stubs
    for task in triggered:
        fn = f"{_sanitize(task.name)}_handler"
        lines += [
            f"static void {fn}(void *data) {{",
            "    (void)data;",
        ]
        for action in task.parsed_actions():
            lines += [f"    {ln}" for ln in _emit_action_nrf52(action)]
        lines += ["}", ""]

    # main
    lines += [
        "void main(void) {",
        f'    LOG_INF("Starting {name}");',
        "    drivers_init();",
        "",
    ]
    for task in periodic:
        delay_ms = task.every_ms()
        lines.append(f"    k_timer_start(&{_sanitize(task.name)}_timer, K_MSEC({delay_ms}), K_MSEC({delay_ms}));")

    lines += [
        "}",
        "",
    ]
    return "\n".join(lines)


def _emit_action_nrf52(action) -> list[str]:
    a = action.action
    args = action.args
    if a == "serial.print":
        text = args.get("text", "")
        return [f'    LOG_INF("{_escape(text)}");']
    if a == "flash.append":
        data = args.get("data", "data")
        return [f"    flash_append(&{_sanitize(data)}, sizeof({_sanitize(data)}));"]
    if a == "display.show":
        text = args.get("text", "")
        return [f'    display_print("{_escape(text)}");']
    if a == "mqtt.publish":
        topic = args.get("topic", "data")
        data = args.get("data", "data")
        return [f'    mqtt_publish("{_escape(topic)}", &{_sanitize(data)}, sizeof({_sanitize(data)}));']
    if a == "gpio.set":
        pin = args.get("pin", "0")
        value = args.get("value", "1")
        return [f"    gpio_pin_set_dt(&{_sanitize(pin)}, {value});"]
    if a == "led.set":
        led_id = args.get("id", "0")
        value = args.get("value", "1")
        return [f"    led_set({led_id}, {value});"]
    if a == "ble.notify":
        uuid = args.get("uuid", "0")
        data = args.get("data", "data")
        return [f"    bt_gatt_notify(NULL, &{_sanitize(uuid)}_attr, &{_sanitize(data)}, sizeof({_sanitize(data)}));"]
    if a in ("http.get", "http.post"):
        url = args.get("url", "")
        method = "GET" if a == "http.get" else "POST"
        return [
            f"    /* HTTP {method}: {_escape(url)} */",
            f'    http_client_{method.lower()}("{_escape(url)}", NULL, NULL);',
        ]
    if a == "i2c.write":
        addr = args.get("addr", "0x00")
        data = args.get("data", "data")
        return [f"    i2c_write({addr}, &{_sanitize(data)}, sizeof({_sanitize(data)}));"]
    # Unknown action — descriptive comment, no TODO
    return [f"    /* Unimplemented action: '{a}' — add custom code here */"]


# ---------------------------------------------------------------------------
# Summary markdown
# ---------------------------------------------------------------------------

def _gen_summary(root: IntentRoot) -> str:
    fw = root.firmware
    lines = [
        f"# Intent Summary: {fw.name}",
        "",
        f"boardsmith_fw_intent schema v{root.boardsmith_fw_intent}",
        "",
        "## Tasks",
        "",
    ]
    for task in fw.tasks:
        if task.every:
            lines.append(f"### `{task.name}` — every {task.every}")
        elif task.trigger:
            lines.append(f"### `{task.name}` — triggered by `{task.trigger}`")
        else:
            lines.append(f"### `{task.name}`")

        for read in task.read:
            vals = ", ".join(read.values) if read.values else "all"
            lines.append(f"- Read {read.component}: {vals} → `{read.store_as or read.component.lower()}`")

        for action in task.parsed_actions():
            lines.append(f"- Action: `{action.action}` {action.args}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_")


def _escape(text: str) -> str:
    return text.replace('"', '\\"').replace("\\", "\\\\")
