# SPDX-License-Identifier: AGPL-3.0-or-later
"""OTA Update Scaffolding Code Generator.

Generates over-the-air update support code for ESP32, STM32, and RP2040 targets.

    target + config → ota_config.h + ota_update.c + ota_summary.md

ESP32:  esp_https_ota + partition-based dual-bank OTA
STM32:  HAL flash write + application jump (single-bank basic OTA)
RP2040: Pico SDK flash write + reboot

Usage:
    from boardsmith_fw.codegen.ota_codegen import generate_ota
    result = generate_ota(target="esp32")
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Configuration model
# ---------------------------------------------------------------------------


class OTAConfig(BaseModel):
    """OTA update configuration."""

    server_url: str = "https://firmware.example.com/ota"
    check_interval_s: int = 3600
    max_retries: int = 3
    verify_signature: bool = True
    rollback_enabled: bool = True
    firmware_version: str = "1.0.0"


# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------


@dataclass
class OTACodegenResult:
    files: list[tuple[str, str]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_ota(
    target: str = "esp32",
    config: OTAConfig | None = None,
) -> OTACodegenResult:
    """Generate OTA update scaffolding for the given target."""
    if config is None:
        config = OTAConfig()

    result = OTACodegenResult()

    if target == "stm32":
        _gen_stm32(config, result)
    elif target == "rp2040":
        _gen_rp2040(config, result)
    elif target == "nrf52":
        _gen_nrf52(config, result)
    else:  # esp32, esp32c3
        _gen_esp32(config, result)

    result.files.append(("ota_summary.md", _gen_summary(config, target)))
    return result


# ---------------------------------------------------------------------------
# ESP32 — esp_https_ota with dual-bank partition
# ---------------------------------------------------------------------------


def _gen_esp32(cfg: OTAConfig, result: OTACodegenResult) -> None:
    result.files.append(("main/ota_config.h", _esp32_header(cfg)))
    result.files.append(("main/ota_update.c", _esp32_impl(cfg)))


def _esp32_header(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA config — ESP32/esp_https_ota */",
        "/* Generated by boardsmith-fw */",
        "#ifndef OTA_CONFIG_H",
        "#define OTA_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        f'#define OTA_SERVER_URL       "{_escape(cfg.server_url)}"',
        f"#define OTA_CHECK_INTERVAL_S {cfg.check_interval_s}",
        f"#define OTA_MAX_RETRIES      {cfg.max_retries}",
        f"#define OTA_VERIFY_SIGNATURE {_bool_c(cfg.verify_signature)}",
        f"#define OTA_ROLLBACK_ENABLED {_bool_c(cfg.rollback_enabled)}",
        f'#define OTA_FW_VERSION       "{_escape(cfg.firmware_version)}"',
        "",
        "void ota_init(void);",
        "void ota_check_and_update(void);",
        "",
        "#endif /* OTA_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _esp32_impl(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA update — ESP32/esp_https_ota */",
        '#include "ota_config.h"',
        "",
        '#include "esp_http_client.h"',
        '#include "esp_https_ota.h"',
        '#include "esp_log.h"',
        '#include "esp_ota_ops.h"',
        '#include "esp_system.h"',
        '#include "freertos/FreeRTOS.h"',
        '#include "freertos/task.h"',
        "",
        'static const char *TAG = "ota";',
        "",
        "static void ota_task(void *arg);",
        "",
    ]

    # ota_init
    lines += [
        "void ota_init(void) {",
        '    ESP_LOGI(TAG, "OTA init — firmware version: %s", OTA_FW_VERSION);',
        "",
    ]
    if cfg.rollback_enabled:
        lines += [
            "#if OTA_ROLLBACK_ENABLED",
            "    const esp_partition_t *running = esp_ota_get_running_partition();",
            "    esp_ota_img_states_t state;",
            "    if (esp_ota_get_state_partition(running, &state) == ESP_OK) {",
            "        if (state == ESP_OTA_IMG_PENDING_VERIFY) {",
            '            ESP_LOGI(TAG, "OTA: confirming new firmware");',
            "            esp_ota_mark_app_valid_cancel_rollback();",
            "        }",
            "    }",
            "#endif",
            "",
        ]
    lines += [
        '    xTaskCreate(ota_task, "ota_task", 8192, NULL, 3, NULL);',
        "}",
        "",
    ]

    # ota_check_and_update
    lines += [
        "void ota_check_and_update(void) {",
        '    ESP_LOGI(TAG, "Checking for OTA update at: %s", OTA_SERVER_URL);',
        "",
        "    esp_http_client_config_t http_cfg = {",
        "        .url = OTA_SERVER_URL,",
        "        .timeout_ms = 10000,",
        "    };",
        "",
        "    esp_https_ota_config_t ota_cfg = {",
        "        .http_config = &http_cfg,",
        "    };",
        "",
        "    for (int attempt = 0; attempt < OTA_MAX_RETRIES; attempt++) {",
        "        esp_err_t err = esp_https_ota(&ota_cfg);",
        "        if (err == ESP_OK) {",
        '            ESP_LOGI(TAG, "OTA succeeded — rebooting");',
        "            esp_restart();",
        "        }",
        '        ESP_LOGW(TAG, "OTA attempt %d failed: %s", attempt + 1, esp_err_to_name(err));',
        "        vTaskDelay(pdMS_TO_TICKS(5000));",
        "    }",
        "",
        '    ESP_LOGE(TAG, "OTA failed after %d attempts", OTA_MAX_RETRIES);',
        "}",
        "",
    ]

    # Background task
    lines += [
        "static void ota_task(void *arg) {",
        "    (void)arg;",
        "    const TickType_t interval = pdMS_TO_TICKS(OTA_CHECK_INTERVAL_S * 1000);",
        "",
        "    /* Initial delay before first check */",
        "    vTaskDelay(pdMS_TO_TICKS(30000));",
        "",
        "    for (;;) {",
        "        ota_check_and_update();",
        "        vTaskDelay(interval);",
        "    }",
        "}",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# STM32 — HAL flash write, basic single-bank OTA
# ---------------------------------------------------------------------------


def _gen_stm32(cfg: OTAConfig, result: OTACodegenResult) -> None:
    result.files.append(("Src/ota_config.h", _stm32_header(cfg)))
    result.files.append(("Src/ota_update.c", _stm32_impl(cfg)))


def _stm32_header(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA config — STM32/HAL */",
        "/* Generated by boardsmith-fw */",
        "#ifndef OTA_CONFIG_H",
        "#define OTA_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        f'#define OTA_FW_VERSION       "{_escape(cfg.firmware_version)}"',
        f"#define OTA_MAX_RETRIES      {cfg.max_retries}",
        f"#define OTA_VERIFY_SIGNATURE {_bool_c(cfg.verify_signature)}",
        "",
        "/* Flash layout */",
        "#define OTA_APP_ADDR         0x08020000u  /* Application slot B */",
        "#define OTA_APP_SIZE         0x00020000u  /* 128KB */",
        "",
        "typedef enum {",
        "    OTA_OK = 0,",
        "    OTA_ERR_ERASE,",
        "    OTA_ERR_WRITE,",
        "    OTA_ERR_VERIFY,",
        "    OTA_ERR_TIMEOUT,",
        "} ota_err_t;",
        "",
        "void ota_init(void);",
        "ota_err_t ota_write_chunk(uint32_t offset, const uint8_t *data, uint32_t len);",
        "ota_err_t ota_finish_and_reboot(void);",
        "",
        "#endif /* OTA_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _stm32_impl(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA update — STM32/HAL flash write */",
        '#include "ota_config.h"',
        '#include "stm32f4xx_hal.h"',
        "",
        '#include <string.h>',
        "",
        "static uint32_t ota_bytes_written;",
        "",
        "void ota_init(void) {",
        "    ota_bytes_written = 0;",
        "    HAL_FLASH_Unlock();",
        "",
        "    /* Erase application slot B */",
        "    FLASH_EraseInitTypeDef erase = {",
        "        .TypeErase = FLASH_TYPEERASE_SECTORS,",
        "        .Sector = FLASH_SECTOR_5,  /* Adjust for your layout */",
        "        .NbSectors = 1,",
        "        .VoltageRange = FLASH_VOLTAGE_RANGE_3,",
        "    };",
        "    uint32_t error = 0;",
        "    HAL_FLASHEx_Erase(&erase, &error);",
        "    HAL_FLASH_Lock();",
        "}",
        "",
        "ota_err_t ota_write_chunk(uint32_t offset, const uint8_t *data, uint32_t len) {",
        "    HAL_FLASH_Unlock();",
        "",
        "    for (uint32_t i = 0; i < len; i++) {",
        "        if (HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE,",
        "                              OTA_APP_ADDR + offset + i,",
        "                              data[i]) != HAL_OK) {",
        "            HAL_FLASH_Lock();",
        "            return OTA_ERR_WRITE;",
        "        }",
        "    }",
        "",
        "    ota_bytes_written += len;",
        "    HAL_FLASH_Lock();",
        "    return OTA_OK;",
        "}",
        "",
        "ota_err_t ota_finish_and_reboot(void) {",
        "    /* Verify: read back first word */",
        "    uint32_t first_word = *(volatile uint32_t *)OTA_APP_ADDR;",
        "    if (first_word == 0xFFFFFFFF) {",
        "        return OTA_ERR_VERIFY;",
        "    }",
        "",
        "    /* System reset to boot into new firmware */",
        "    HAL_NVIC_SystemReset();",
        "    return OTA_OK;  /* unreachable */",
        "}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# RP2040 — Pico SDK flash write + reboot
# ---------------------------------------------------------------------------


def _gen_rp2040(cfg: OTAConfig, result: OTACodegenResult) -> None:
    result.files.append(("ota_config.h", _rp2040_header(cfg)))
    result.files.append(("ota_update.c", _rp2040_impl(cfg)))


def _rp2040_header(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA config — RP2040/Pico SDK */",
        "/* Generated by boardsmith-fw */",
        "#ifndef OTA_CONFIG_H",
        "#define OTA_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        f'#define OTA_FW_VERSION       "{_escape(cfg.firmware_version)}"',
        f"#define OTA_MAX_RETRIES      {cfg.max_retries}",
        "",
        "/* Flash layout */",
        "#define OTA_FLASH_OFFSET     (256 * 1024)  /* 256KB into flash */",
        "#define OTA_MAX_SIZE         (256 * 1024)  /* 256KB max firmware */",
        "#define OTA_SECTOR_SIZE      4096",
        "",
        "typedef enum {",
        "    OTA_OK = 0,",
        "    OTA_ERR_ERASE,",
        "    OTA_ERR_WRITE,",
        "    OTA_ERR_VERIFY,",
        "    OTA_ERR_SIZE,",
        "} ota_err_t;",
        "",
        "void ota_init(void);",
        "ota_err_t ota_write_chunk(uint32_t offset, const uint8_t *data, uint32_t len);",
        "ota_err_t ota_finish_and_reboot(void);",
        "",
        "#endif /* OTA_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _rp2040_impl(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA update — RP2040/Pico SDK flash */",
        '#include "ota_config.h"',
        "",
        '#include "hardware/flash.h"',
        '#include "hardware/watchdog.h"',
        '#include "pico/stdlib.h"',
        "",
        '#include <string.h>',
        "",
        "static uint32_t ota_bytes_written;",
        "",
        "void ota_init(void) {",
        "    ota_bytes_written = 0;",
        '    printf("[ota] OTA ready — version: %s\\n", OTA_FW_VERSION);',
        "}",
        "",
        "ota_err_t ota_write_chunk(uint32_t offset, const uint8_t *data, uint32_t len) {",
        "    if (offset + len > OTA_MAX_SIZE) {",
        "        return OTA_ERR_SIZE;",
        "    }",
        "",
        "    uint32_t flash_addr = OTA_FLASH_OFFSET + offset;",
        "",
        "    /* Erase sectors as needed */",
        "    if (offset % OTA_SECTOR_SIZE == 0) {",
        "        uint32_t erase_len = ((len + OTA_SECTOR_SIZE - 1) / OTA_SECTOR_SIZE) * OTA_SECTOR_SIZE;",
        "        flash_range_erase(flash_addr, erase_len);",
        "    }",
        "",
        "    /* Write in 256-byte pages */",
        "    flash_range_program(flash_addr, data, len);",
        "    ota_bytes_written += len;",
        "",
        "    return OTA_OK;",
        "}",
        "",
        "ota_err_t ota_finish_and_reboot(void) {",
        "    /* Verify: check first bytes are not erased */",
        "    const uint8_t *check = (const uint8_t *)(XIP_BASE + OTA_FLASH_OFFSET);",
        "    if (check[0] == 0xFF && check[1] == 0xFF) {",
        "        return OTA_ERR_VERIFY;",
        "    }",
        "",
        '    printf("[ota] Update complete (%u bytes) — rebooting\\n", ota_bytes_written);',
        "    watchdog_reboot(0, 0, 100);",
        "    return OTA_OK;  /* unreachable */",
        "}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# nRF52 — MCUboot + Zephyr DFU
# ---------------------------------------------------------------------------


def _gen_nrf52(cfg: OTAConfig, result: OTACodegenResult) -> None:
    result.files.append(("src/ota_config.h", _nrf52_header(cfg)))
    result.files.append(("src/ota_update.c", _nrf52_impl(cfg)))


def _nrf52_header(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA config — nRF52/Zephyr + MCUboot */",
        "/* Generated by boardsmith-fw */",
        "#ifndef OTA_CONFIG_H",
        "#define OTA_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        f'#define OTA_FW_VERSION       "{_escape(cfg.firmware_version)}"',
        f"#define OTA_MAX_RETRIES      {cfg.max_retries}",
        f"#define OTA_ROLLBACK_ENABLED {_bool_c(cfg.rollback_enabled)}",
        "",
        "typedef enum {",
        "    OTA_OK = 0,",
        "    OTA_ERR_FLASH,",
        "    OTA_ERR_VERIFY,",
        "    OTA_ERR_CONFIRM,",
        "} ota_err_t;",
        "",
        "void ota_init(void);",
        "ota_err_t ota_confirm_image(void);",
        "ota_err_t ota_request_upgrade(void);",
        "",
        "#endif /* OTA_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _nrf52_impl(cfg: OTAConfig) -> str:
    lines = [
        "/* boardsmith-fw OTA update — nRF52/Zephyr MCUboot */",
        '#include "ota_config.h"',
        "",
        '#include <zephyr/kernel.h>',
        '#include <zephyr/dfu/mcuboot.h>',
        '#include <zephyr/logging/log.h>',
        "",
        'LOG_MODULE_REGISTER(ota, LOG_LEVEL_INF);',
        "",
        "void ota_init(void) {",
        '    LOG_INF("OTA init — firmware version: %s", OTA_FW_VERSION);',
        "",
    ]

    if cfg.rollback_enabled:
        lines += [
            "#if OTA_ROLLBACK_ENABLED",
            "    if (!boot_is_img_confirmed()) {",
            '        LOG_INF("Confirming current image");',
            "        boot_write_img_confirmed();",
            "    }",
            "#endif",
        ]

    lines += [
        "}",
        "",
        "ota_err_t ota_confirm_image(void) {",
        "    int rc = boot_write_img_confirmed();",
        "    if (rc != 0) {",
        '        LOG_ERR("Failed to confirm image: %d", rc);',
        "        return OTA_ERR_CONFIRM;",
        "    }",
        '    LOG_INF("Image confirmed");',
        "    return OTA_OK;",
        "}",
        "",
        "ota_err_t ota_request_upgrade(void) {",
        "    int rc = boot_request_upgrade(BOOT_UPGRADE_TEST);",
        "    if (rc != 0) {",
        '        LOG_ERR("Failed to request upgrade: %d", rc);',
        "        return OTA_ERR_FLASH;",
        "    }",
        '    LOG_INF("Upgrade requested — reboot to apply");',
        "    return OTA_OK;",
        "}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------


def _gen_summary(cfg: OTAConfig, target: str) -> str:
    lines = [
        "# OTA Update Configuration Summary",
        "",
        f"Target: **{target}**",
        f"Firmware version: `{cfg.firmware_version}`",
        "",
    ]

    if target == "esp32":
        lines += [
            "## Architecture: ESP32 Dual-Bank OTA",
            "",
            "- Method: `esp_https_ota` with partition table",
            f"- Server: `{cfg.server_url}`",
            f"- Check interval: {cfg.check_interval_s}s",
            f"- Max retries: {cfg.max_retries}",
            f"- Signature verification: {cfg.verify_signature}",
            f"- Rollback support: {cfg.rollback_enabled}",
            "",
            "### Flow",
            "",
            "1. Background task periodically checks server for updates",
            "2. Downloads firmware to inactive OTA partition",
            "3. Verifies integrity and reboots to new partition",
            "4. On next boot, marks firmware valid (anti-rollback)",
            "",
        ]
    elif target == "stm32":
        lines += [
            "## Architecture: STM32 Single-Bank Flash OTA",
            "",
            "- Method: HAL flash write to application slot B",
            "- Flash address: `0x08020000` (128KB slot)",
            f"- Max retries: {cfg.max_retries}",
            "",
            "### Flow",
            "",
            "1. Receive firmware chunks via UART/SPI/I2C",
            "2. Write chunks to flash slot B with `ota_write_chunk()`",
            "3. Verify and reboot with `ota_finish_and_reboot()`",
            "",
        ]
    elif target == "rp2040":
        lines += [
            "## Architecture: RP2040 Flash OTA",
            "",
            "- Method: Pico SDK `flash_range_program`",
            "- Flash offset: 256KB",
            "- Max firmware size: 256KB",
            f"- Max retries: {cfg.max_retries}",
            "",
            "### Flow",
            "",
            "1. Receive firmware chunks via USB/UART",
            "2. Erase and write flash with `ota_write_chunk()`",
            "3. Verify and reboot with `ota_finish_and_reboot()`",
            "",
        ]

    elif target == "nrf52":
        lines += [
            "## Architecture: nRF52 MCUboot DFU",
            "",
            "- Method: MCUboot bootloader + Zephyr DFU API",
            f"- Max retries: {cfg.max_retries}",
            f"- Rollback support: {cfg.rollback_enabled}",
            "",
            "### Flow",
            "",
            "1. Receive firmware image via BLE DFU / UART",
            "2. Write to secondary slot (managed by MCUboot)",
            "3. Request upgrade with `boot_request_upgrade()`",
            "4. MCUboot swaps images on reboot",
            "5. Confirm new image with `boot_write_img_confirmed()`",
            "",
        ]

    lines += [
        "## Files Generated",
        "",
    ]

    if target in ("esp32", "esp32c3"):
        lines += [
            "- `main/ota_config.h` — OTA defines and API",
            "- `main/ota_update.c` — esp_https_ota implementation",
        ]
    elif target == "stm32":
        lines += [
            "- `Src/ota_config.h` — OTA defines, error codes, API",
            "- `Src/ota_update.c` — HAL flash write implementation",
        ]
    elif target == "rp2040":
        lines += [
            "- `ota_config.h` — OTA defines, error codes, API",
            "- `ota_update.c` — Pico SDK flash write implementation",
        ]
    elif target == "nrf52":
        lines += [
            "- `src/ota_config.h` — OTA defines, error codes, API",
            "- `src/ota_update.c` — MCUboot DFU implementation",
        ]

    lines += [
        "- `ota_summary.md` — This file",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _bool_c(val: bool) -> str:
    return "1" if val else "0"


def _escape(text: str) -> str:
    return text.replace('"', '\\"').replace("\\", "\\\\")


def _sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_")
