# SPDX-License-Identifier: AGPL-3.0-or-later
"""PlatformIO integration — generate platformio.ini alongside CMakeLists.txt."""

from __future__ import annotations

from boardsmith_fw.codegen.llm_wrapper import GeneratedFile
from boardsmith_fw.models.hardware_graph import HardwareGraph, MCUFamily


def generate_platformio_ini(
    graph: HardwareGraph,
    target: str = "auto",
    lang: str = "c",
) -> GeneratedFile:
    """Generate a platformio.ini configuration file."""
    resolved = _resolve_pio_target(graph, target)
    env = _PIO_ENVS.get(resolved, _PIO_ENVS["esp32"])

    monitor_speed = 115200
    lib_deps: list[str] = []
    build_flags: list[str] = []

    if lang == "cpp":
        build_flags.append("-std=gnu++17")

    flags_str = ""
    if build_flags:
        flags_str = "\nbuild_flags =\n" + "\n".join(
            f"    {f}" for f in build_flags
        )

    deps_str = ""
    if lib_deps:
        deps_str = "\nlib_deps =\n" + "\n".join(
            f"    {d}" for d in lib_deps
        )

    content = (
        "; PlatformIO Configuration\n"
        "; Generated by boardsmith-fw CLI\n"
        ";\n"
        f"; Target: {resolved}\n\n"
        "[env:default]\n"
        f"platform = {env['platform']}\n"
        f"board = {env['board']}\n"
        f"framework = {env['framework']}\n"
        f"monitor_speed = {monitor_speed}\n"
        f"{flags_str}"
        f"{deps_str}\n"
    )

    return GeneratedFile(path="platformio.ini", content=content)


def _resolve_pio_target(graph: HardwareGraph, target: str) -> str:
    if target != "auto":
        return target
    if graph.mcu:
        if graph.mcu.family == MCUFamily.ESP32_C3:
            return "esp32c3"
        if graph.mcu.family == MCUFamily.STM32:
            return "stm32"
        if graph.mcu.family == MCUFamily.RP2040:
            return "rp2040"
        if graph.mcu.family == MCUFamily.NRF52:
            return "nrf52"
    return "esp32"


_PIO_ENVS: dict[str, dict[str, str]] = {
    "esp32": {
        "platform": "espressif32",
        "board": "esp32dev",
        "framework": "espidf",
    },
    "esp32c3": {
        "platform": "espressif32",
        "board": "esp32-c3-devkitm-1",
        "framework": "espidf",
    },
    "stm32": {
        "platform": "ststm32",
        "board": "genericSTM32F407VGT6",
        "framework": "stm32cube",
    },
    "rp2040": {
        "platform": "raspberrypi",
        "board": "pico",
        "framework": "arduino",
    },
    "nrf52": {
        "platform": "nordicnrf52",
        "board": "nrf52840_dk",
        "framework": "zephyr",
    },
}
