# SPDX-License-Identifier: AGPL-3.0-or-later
"""FreeRTOS task structure generator.

Transforms the flat while(1) loop architecture into:
- One task per bus/device group
- Inter-task communication via queues
- Proper ISR integration with task notifications
"""

from __future__ import annotations

import re

from boardsmith_fw.codegen.llm_wrapper import GeneratedFile
from boardsmith_fw.models.component_knowledge import ComponentKnowledge
from boardsmith_fw.models.hardware_graph import HardwareGraph, IRQLine


def _sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)[:32]


def generate_rtos_main_esp32(
    graph: HardwareGraph,
    knowledge: list[ComponentKnowledge],
    description: str,
    lang: str,
    driver_headers: list[str],
    stack_size: int = 4096,
) -> GeneratedFile:
    """Generate an ESP32 FreeRTOS main.c with task-per-bus architecture."""
    ext = "cpp" if lang == "cpp" else "c"
    extern_c = 'extern "C" ' if lang == "cpp" else ""

    includes = "\n".join(f'#include "{h}"' for h in driver_headers)

    # Group slaves by bus
    bus_tasks: list[dict] = []
    for bus in graph.buses:
        if not bus.slave_component_ids:
            continue
        task_name = f"task_{bus.type.value.lower()}_{_sanitize(bus.name).lower()}"
        slaves = []
        for slave_id in bus.slave_component_ids:
            comp = next(
                (c for c in graph.components if c.id == slave_id), None
            )
            if comp:
                slaves.append(comp)
        bus_tasks.append({
            "name": task_name,
            "bus": bus,
            "slaves": slaves,
        })

    # Collect IRQ lines
    irq_lines = graph.irq_lines

    # Build task function prototypes
    task_protos = "\n".join(
        f"static void {t['name']}(void *pvParameters);"
        for t in bus_tasks
    )

    # Build task handle declarations
    task_handles = "\n".join(
        f"static TaskHandle_t {t['name']}_handle = NULL;"
        for t in bus_tasks
    )

    # Build ISR declarations
    isr_decls = ""
    for irq in irq_lines:
        gpio = _get_irq_gpio(irq, graph)
        if gpio:
            isr_name = f"isr_{_sanitize(irq.net).lower()}"
            isr_decls += f"static void IRAM_ATTR {isr_name}(void *arg);\n"

    # Build bus init code (same as before, extracted)
    bus_init = _gen_esp32_bus_init(graph)

    # Build ISR install code
    isr_install = _gen_esp32_isr_install(irq_lines, graph, bus_tasks)

    # Build task creation code
    task_creates = "\n".join(
        f'    xTaskCreate({t["name"]}, "{t["name"]}", '
        f'{stack_size}, NULL, 5, &{t["name"]}_handle);'
        for t in bus_tasks
    )

    # Build task function bodies
    task_bodies = "\n\n".join(
        _gen_esp32_task_body(t, knowledge)
        for t in bus_tasks
    )

    # Build ISR bodies
    isr_bodies = _gen_esp32_isr_bodies(irq_lines, graph, bus_tasks)

    return GeneratedFile(
        path=f"main/main.{ext}",
        content=(
            f"/**\n"
            f" * Eagle->ESP32 Generated Firmware (FreeRTOS)\n"
            f" * Function: {description}\n"
            f" * Architecture: Task-per-bus with ISR notifications\n"
            f" * Generated by boardsmith-fw CLI\n"
            f" */\n\n"
            f"#include <stdio.h>\n"
            f'#include "freertos/FreeRTOS.h"\n'
            f'#include "freertos/task.h"\n'
            f'#include "freertos/queue.h"\n'
            f'#include "driver/i2c.h"\n'
            f'#include "driver/spi_master.h"\n'
            f'#include "driver/uart.h"\n'
            f'#include "driver/gpio.h"\n'
            f'#include "esp_log.h"\n'
            f"{includes}\n\n"
            f'static const char *TAG = "main";\n\n'
            f"/* Task handles */\n"
            f"{task_handles}\n\n"
            f"/* Task prototypes */\n"
            f"{task_protos}\n\n"
            f"{isr_decls}\n"
            f"{extern_c}void app_main(void)\n"
            f"{{\n"
            f'    ESP_LOGI(TAG, "Eagle->ESP32 FreeRTOS Firmware Starting...");\n\n'
            f"{bus_init}\n"
            f"{isr_install}\n"
            f"    /* Create tasks */\n"
            f"{task_creates}\n\n"
            f'    ESP_LOGI(TAG, "All tasks started.");\n'
            f"}}\n\n"
            f"{task_bodies}\n"
            f"{isr_bodies}"
        ),
    )


def _get_irq_gpio(irq: IRQLine, graph: HardwareGraph) -> str | None:
    """Get GPIO number for an IRQ net from bus pin mappings."""
    for comp in graph.components:
        for pin in comp.pins:
            if pin.net and pin.net == irq.net:
                if comp.id == irq.target_component_id:
                    # MCU pin — extract GPIO number
                    name = pin.name.upper()
                    m = re.search(r"GPIO(\d+)", name)
                    if m:
                        return m.group(1)
                    m = re.search(r"IO(\d+)", name)
                    if m:
                        return m.group(1)
    return None


def _gen_esp32_bus_init(graph: HardwareGraph) -> str:
    """Generate bus initialization code for ESP32."""
    lines: list[str] = []

    for bus in graph.buses:
        if bus.type.value == "I2C":
            sda = _get_bus_pin(bus, "SDA", "21")
            scl = _get_bus_pin(bus, "SCL", "22")
            lines += [
                "    /* I2C bus init */",
                "    i2c_config_t i2c_conf = {",
                "        .mode = I2C_MODE_MASTER,",
                f"        .sda_io_num = GPIO_NUM_{sda},",
                f"        .scl_io_num = GPIO_NUM_{scl},",
                "        .sda_pullup_en = GPIO_PULLUP_ENABLE,",
                "        .scl_pullup_en = GPIO_PULLUP_ENABLE,",
                "        .master.clk_speed = 100000,",
                "    };",
                "    i2c_param_config(I2C_NUM_0, &i2c_conf);",
                "    i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);",
                "",
            ]
        elif bus.type.value == "SPI":
            mosi = _get_bus_pin(bus, "MOSI", "23")
            miso = _get_bus_pin(bus, "MISO", "19")
            sck = _get_bus_pin(bus, "SCK", "18")
            lines += [
                "    /* SPI bus init */",
                "    spi_bus_config_t spi_conf = {",
                f"        .mosi_io_num = GPIO_NUM_{mosi},",
                f"        .miso_io_num = GPIO_NUM_{miso},",
                f"        .sclk_io_num = GPIO_NUM_{sck},",
                "        .quadwp_io_num = -1,",
                "        .quadhd_io_num = -1,",
                "    };",
                "    spi_bus_initialize(SPI2_HOST, &spi_conf, SPI_DMA_CH_AUTO);",
                "",
            ]
        elif bus.type.value == "UART":
            tx = _get_bus_pin(bus, "TX", "17")
            rx = _get_bus_pin(bus, "RX", "16")
            lines += [
                "    /* UART init */",
                "    uart_config_t uart_conf = {",
                "        .baud_rate = 9600,",
                "        .data_bits = UART_DATA_8_BITS,",
                "        .parity = UART_PARITY_DISABLE,",
                "        .stop_bits = UART_STOP_BITS_1,",
                "        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,",
                "    };",
                "    uart_param_config(UART_NUM_1, &uart_conf);",
                f"    uart_set_pin(UART_NUM_1, GPIO_NUM_{tx}, GPIO_NUM_{rx}, -1, -1);",
                "    uart_driver_install(UART_NUM_1, 1024, 0, 0, NULL, 0);",
                "",
            ]

    return "\n".join(lines)


def _get_bus_pin(bus, signal: str, fallback: str) -> str:
    for pm in bus.pin_mapping:
        if pm.signal == signal and pm.gpio:
            return pm.gpio
    return fallback


def _gen_esp32_isr_install(
    irq_lines: list[IRQLine],
    graph: HardwareGraph,
    bus_tasks: list[dict],
) -> str:
    """Generate GPIO ISR installation code."""
    if not irq_lines:
        return ""

    lines = ["    /* Install GPIO ISR service */"]
    lines.append("    gpio_install_isr_service(0);")
    lines.append("")

    for irq in irq_lines:
        gpio = _get_irq_gpio(irq, graph)
        if not gpio:
            continue

        isr_name = f"isr_{_sanitize(irq.net).lower()}"
        trigger = irq.trigger or "falling"
        edge_map = {
            "falling": "GPIO_INTR_NEGEDGE",
            "rising": "GPIO_INTR_POSEDGE",
            "both": "GPIO_INTR_ANYEDGE",
            "level": "GPIO_INTR_LOW_LEVEL",
        }
        intr_type = edge_map.get(trigger, "GPIO_INTR_NEGEDGE")

        lines += [
            f"    /* IRQ: {irq.net} ({irq.source_component_id} -> MCU GPIO{gpio}) */",
            "    gpio_config_t irq_conf = {",
            f"        .pin_bit_mask = (1ULL << GPIO_NUM_{gpio}),",
            "        .mode = GPIO_MODE_INPUT,",
            "        .pull_up_en = GPIO_PULLUP_ENABLE,",
            "        .pull_down_en = GPIO_PULLDOWN_DISABLE,",
            f"        .intr_type = {intr_type},",
            "    };",
            "    gpio_config(&irq_conf);",
            f"    gpio_isr_handler_add(GPIO_NUM_{gpio}, {isr_name}, NULL);",
            "",
        ]

    return "\n".join(lines)


def _gen_esp32_task_body(task: dict, knowledge: list[ComponentKnowledge]) -> str:
    """Generate task function body."""
    slaves = task["slaves"]
    name = task["name"]

    init_lines: list[str] = []
    read_lines: list[str] = []

    for comp in slaves:
        fn = _sanitize(comp.value or comp.name).lower()
        init_lines.append(f"    {fn}_init();")
        read_lines.append(f"        {fn}_read();")

    interval = "1000"  # Default 1s
    # Use timing from knowledge if available
    for comp in slaves:
        kn = next(
            (k for k in knowledge if k.component_id == comp.id), None
        )
        if kn:
            for tc in kn.timing_constraints:
                if "measurement" in tc.parameter.lower() and tc.typical:
                    # Use 10x measurement time as poll interval
                    try:
                        meas_ms = int(float(tc.typical))
                        interval = str(max(meas_ms * 10, 100))
                    except ValueError:
                        pass

    return (
        f"static void {name}(void *pvParameters)\n"
        f"{{\n"
        f'    ESP_LOGI(TAG, "Starting {name}");\n\n'
        f"{chr(10).join(init_lines)}\n\n"
        f"    while (1) {{\n"
        f"{chr(10).join(read_lines)}\n"
        f"        vTaskDelay(pdMS_TO_TICKS({interval}));\n"
        f"    }}\n"
        f"}}"
    )


def _gen_esp32_isr_bodies(
    irq_lines: list[IRQLine],
    graph: HardwareGraph,
    bus_tasks: list[dict],
) -> str:
    """Generate ISR function bodies with task notifications."""
    if not irq_lines:
        return ""

    bodies: list[str] = []

    for irq in irq_lines:
        gpio = _get_irq_gpio(irq, graph)
        if not gpio:
            continue

        isr_name = f"isr_{_sanitize(irq.net).lower()}"

        # Find the task that owns the source component
        notify_task = None
        for t in bus_tasks:
            for slave in t["slaves"]:
                if slave.id == irq.source_component_id:
                    notify_task = t["name"]
                    break

        if notify_task:
            bodies.append(
                f"static void IRAM_ATTR {isr_name}(void *arg)\n"
                f"{{\n"
                f"    BaseType_t xHigherPriorityTaskWoken = pdFALSE;\n"
                f"    vTaskNotifyGiveFromISR("
                f"{notify_task}_handle, &xHigherPriorityTaskWoken);\n"
                f"    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);\n"
                f"}}\n"
            )
        else:
            bodies.append(
                f"static void IRAM_ATTR {isr_name}(void *arg)\n"
                f"{{\n"
                f"    /* IRQ from {irq.source_component_id} "
                f"on {irq.net} */\n"
                f"}}\n"
            )

    return "\n".join(bodies)
