# SPDX-License-Identifier: AGPL-3.0-or-later
"""Safety Template Code Generator — IEC 61508 inspired safety scaffolding.

Generates watchdog, stack-overflow detection, and heap monitoring code
for ESP32/FreeRTOS, STM32/HAL, and RP2040/Pico SDK targets.

    target + config → safety_config.h + safety_monitor.c + safety_summary.md

Usage:
    from boardsmith_fw.codegen.safety_codegen import generate_safety
    result = generate_safety(target="esp32")
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Configuration model
# ---------------------------------------------------------------------------


class WatchdogConfig(BaseModel):
    """Watchdog timer configuration."""

    enabled: bool = True
    timeout_ms: int = 5000
    panic_on_trigger: bool = True


class StackConfig(BaseModel):
    """Stack overflow detection configuration."""

    enabled: bool = True
    check_interval_ms: int = 10000
    min_free_bytes: int = 256
    paint_pattern: int = 0xDEADBEEF


class HeapConfig(BaseModel):
    """Heap monitoring configuration."""

    enabled: bool = True
    check_interval_ms: int = 30000
    low_watermark_bytes: int = 4096


class SafetyConfig(BaseModel):
    """Top-level safety configuration."""

    watchdog: WatchdogConfig = Field(default_factory=WatchdogConfig)
    stack: StackConfig = Field(default_factory=StackConfig)
    heap: HeapConfig = Field(default_factory=HeapConfig)
    task_names: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------


@dataclass
class SafetyCodegenResult:
    files: list[tuple[str, str]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_safety(
    target: str = "esp32",
    config: SafetyConfig | None = None,
) -> SafetyCodegenResult:
    """Generate safety template files for the given target."""
    if config is None:
        config = SafetyConfig()

    result = SafetyCodegenResult()

    if target == "stm32":
        _gen_stm32(config, result)
    elif target == "rp2040":
        _gen_rp2040(config, result)
    elif target == "nrf52":
        _gen_nrf52(config, result)
    else:  # esp32, esp32c3
        _gen_esp32(config, result)

    result.files.append(("safety_summary.md", _gen_summary(config, target)))
    return result


# ---------------------------------------------------------------------------
# ESP32 / FreeRTOS
# ---------------------------------------------------------------------------


def _gen_esp32(cfg: SafetyConfig, result: SafetyCodegenResult) -> None:
    header = _esp32_header(cfg)
    impl = _esp32_impl(cfg)
    result.files.append(("main/safety_config.h", header))
    result.files.append(("main/safety_monitor.c", impl))


def _esp32_header(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety config — ESP32/FreeRTOS */",
        "/* IEC 61508 inspired — generated by boardsmith-fw */",
        "#ifndef SAFETY_CONFIG_H",
        "#define SAFETY_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "/* Watchdog */",
        f"#define SAFETY_WDT_ENABLED       {_bool_c(cfg.watchdog.enabled)}",
        f"#define SAFETY_WDT_TIMEOUT_MS    {cfg.watchdog.timeout_ms}",
        f"#define SAFETY_WDT_PANIC         {_bool_c(cfg.watchdog.panic_on_trigger)}",
        "",
        "/* Stack overflow detection */",
        f"#define SAFETY_STACK_ENABLED     {_bool_c(cfg.stack.enabled)}",
        f"#define SAFETY_STACK_CHECK_MS    {cfg.stack.check_interval_ms}",
        f"#define SAFETY_STACK_MIN_FREE    {cfg.stack.min_free_bytes}",
        "",
        "/* Heap monitoring */",
        f"#define SAFETY_HEAP_ENABLED      {_bool_c(cfg.heap.enabled)}",
        f"#define SAFETY_HEAP_CHECK_MS     {cfg.heap.check_interval_ms}",
        f"#define SAFETY_HEAP_LOW_WATER    {cfg.heap.low_watermark_bytes}",
        "",
        "void safety_init(void);",
        "void safety_wdt_feed(void);",
        "",
        "#endif /* SAFETY_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _esp32_impl(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety monitor — ESP32/FreeRTOS */",
        '#include "safety_config.h"',
        "",
        '#include "esp_log.h"',
        '#include "esp_system.h"',
        '#include "esp_task_wdt.h"',
        '#include "freertos/FreeRTOS.h"',
        '#include "freertos/task.h"',
        "",
        'static const char *TAG = "safety";',
        "",
    ]

    # Stack overflow hook
    if cfg.stack.enabled:
        lines += [
            "/* FreeRTOS stack overflow hook — called on overflow */",
            "void vApplicationStackOverflowHook(TaskHandle_t task, char *name) {",
            '    ESP_LOGE(TAG, "STACK OVERFLOW: task=%s", name);',
            "    esp_system_abort(\"stack overflow\");",
            "}",
            "",
        ]

    # Monitoring task
    if cfg.stack.enabled or cfg.heap.enabled:
        lines += [
            "static void safety_monitor_task(void *arg) {",
            "    (void)arg;",
            "",
        ]
        # Determine the longest interval so we can use it as the loop period
        intervals = []
        if cfg.stack.enabled:
            intervals.append(cfg.stack.check_interval_ms)
        if cfg.heap.enabled:
            intervals.append(cfg.heap.check_interval_ms)
        period = min(intervals) if intervals else 10000

        lines += [
            f"    const TickType_t period = pdMS_TO_TICKS({period});",
            "    TickType_t last_wake = xTaskGetTickCount();",
            "",
            "    for (;;) {",
        ]

        if cfg.stack.enabled:
            lines += [
                "#if SAFETY_STACK_ENABLED",
                "        {",
                "            UBaseType_t hwm = uxTaskGetStackHighWaterMark(NULL);",
                "            if (hwm < SAFETY_STACK_MIN_FREE) {",
                '                ESP_LOGW(TAG, "Stack low: %u bytes remaining", (unsigned)hwm);',
                "            }",
                "        }",
                "#endif",
                "",
            ]

        if cfg.heap.enabled:
            lines += [
                "#if SAFETY_HEAP_ENABLED",
                "        {",
                "            uint32_t free_heap = esp_get_free_heap_size();",
                "            if (free_heap < SAFETY_HEAP_LOW_WATER) {",
                '                ESP_LOGW(TAG, "Heap low: %lu bytes free", (unsigned long)free_heap);',
                "            }",
                "        }",
                "#endif",
                "",
            ]

        lines += [
            "        vTaskDelayUntil(&last_wake, period);",
            "    }",
            "}",
            "",
        ]

    # safety_init
    lines += [
        "void safety_init(void) {",
    ]

    if cfg.watchdog.enabled:
        timeout_s = max(1, cfg.watchdog.timeout_ms // 1000)
        lines += [
            "#if SAFETY_WDT_ENABLED",
            f"    esp_task_wdt_init({timeout_s}, SAFETY_WDT_PANIC);",
            "    esp_task_wdt_add(NULL);",
            '    ESP_LOGI(TAG, "Watchdog enabled: %ds timeout", '
            f"{timeout_s});",
            "#endif",
        ]

    if cfg.stack.enabled or cfg.heap.enabled:
        lines += [
            "",
            '    xTaskCreate(safety_monitor_task, "safety_mon", 2048, NULL, 1, NULL);',
            '    ESP_LOGI(TAG, "Safety monitor started");',
        ]

    lines += [
        "}",
        "",
    ]

    # safety_wdt_feed
    lines += [
        "void safety_wdt_feed(void) {",
        "#if SAFETY_WDT_ENABLED",
        "    esp_task_wdt_reset();",
        "#endif",
        "}",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# STM32 / HAL
# ---------------------------------------------------------------------------


def _gen_stm32(cfg: SafetyConfig, result: SafetyCodegenResult) -> None:
    header = _stm32_header(cfg)
    impl = _stm32_impl(cfg)
    result.files.append(("Src/safety_config.h", header))
    result.files.append(("Src/safety_monitor.c", impl))


def _stm32_header(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety config — STM32/HAL */",
        "/* IEC 61508 inspired — generated by boardsmith-fw */",
        "#ifndef SAFETY_CONFIG_H",
        "#define SAFETY_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "/* Watchdog (IWDG) */",
        f"#define SAFETY_WDT_ENABLED       {_bool_c(cfg.watchdog.enabled)}",
        f"#define SAFETY_WDT_TIMEOUT_MS    {cfg.watchdog.timeout_ms}",
        "",
        "/* Stack overflow detection */",
        f"#define SAFETY_STACK_ENABLED     {_bool_c(cfg.stack.enabled)}",
        f"#define SAFETY_STACK_CHECK_MS    {cfg.stack.check_interval_ms}",
        f"#define SAFETY_STACK_MIN_FREE    {cfg.stack.min_free_bytes}",
        f"#define SAFETY_STACK_PAINT       0x{cfg.stack.paint_pattern:08X}u",
        "",
        "/* Heap monitoring */",
        f"#define SAFETY_HEAP_ENABLED      {_bool_c(cfg.heap.enabled)}",
        f"#define SAFETY_HEAP_CHECK_MS     {cfg.heap.check_interval_ms}",
        f"#define SAFETY_HEAP_LOW_WATER    {cfg.heap.low_watermark_bytes}",
        "",
        "void safety_init(void);",
        "void safety_wdt_feed(void);",
        "void safety_check(uint32_t now_ms);",
        "",
        "#endif /* SAFETY_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _stm32_impl(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety monitor — STM32/HAL */",
        '#include "safety_config.h"',
        '#include "stm32f4xx_hal.h"',
        "",
    ]

    if cfg.watchdog.enabled:
        lines += [
            "#if SAFETY_WDT_ENABLED",
            "static IWDG_HandleTypeDef hiwdg;",
            "#endif",
            "",
        ]

    lines += [
        "static uint32_t last_stack_check;",
        "static uint32_t last_heap_check;",
        "",
    ]

    # Stack painting helpers
    if cfg.stack.enabled:
        lines += [
            "/* Linker symbols — set in linker script */",
            "extern uint32_t _estack;",
            "extern uint32_t _Min_Stack_Size;",
            "",
            "static uint32_t stack_check_free(void) {",
            "    volatile uint32_t *bottom = &_estack - (uint32_t)(uintptr_t)&_Min_Stack_Size;",
            "    uint32_t free_words = 0;",
            "    while (*bottom == SAFETY_STACK_PAINT) {",
            "        free_words++;",
            "        bottom++;",
            "    }",
            "    return free_words * 4;",
            "}",
            "",
        ]

    # safety_init
    lines += [
        "void safety_init(void) {",
    ]

    if cfg.watchdog.enabled:
        # IWDG prescaler/reload: LSI ~32kHz, prescaler 64 → 500Hz tick
        # reload = timeout_ms * 500 / 1000
        reload_val = min(4095, max(1, cfg.watchdog.timeout_ms * 500 // 1000))
        lines += [
            "#if SAFETY_WDT_ENABLED",
            "    hiwdg.Instance = IWDG;",
            "    hiwdg.Init.Prescaler = IWDG_PRESCALER_64;",
            f"    hiwdg.Init.Reload = {reload_val};",
            "    HAL_IWDG_Init(&hiwdg);",
            "#endif",
        ]

    lines += [
        "    last_stack_check = 0;",
        "    last_heap_check = 0;",
        "}",
        "",
    ]

    # safety_wdt_feed
    lines += [
        "void safety_wdt_feed(void) {",
        "#if SAFETY_WDT_ENABLED",
        "    HAL_IWDG_Refresh(&hiwdg);",
        "#endif",
        "}",
        "",
    ]

    # safety_check — called from main super-loop
    lines += [
        "void safety_check(uint32_t now_ms) {",
    ]

    if cfg.stack.enabled:
        lines += [
            "#if SAFETY_STACK_ENABLED",
            "    if (now_ms - last_stack_check >= SAFETY_STACK_CHECK_MS) {",
            "        last_stack_check = now_ms;",
            "        uint32_t free = stack_check_free();",
            "        if (free < SAFETY_STACK_MIN_FREE) {",
            "            /* STACK LOW — trigger error handler */",
            "            Error_Handler();",
            "        }",
            "    }",
            "#endif",
        ]

    if cfg.heap.enabled:
        lines += [
            "#if SAFETY_HEAP_ENABLED",
            "    if (now_ms - last_heap_check >= SAFETY_HEAP_CHECK_MS) {",
            "        last_heap_check = now_ms;",
            "        /* Application-specific heap check */",
            "    }",
            "#endif",
        ]

    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# RP2040 / Pico SDK
# ---------------------------------------------------------------------------


def _gen_rp2040(cfg: SafetyConfig, result: SafetyCodegenResult) -> None:
    header = _rp2040_header(cfg)
    impl = _rp2040_impl(cfg)
    result.files.append(("safety_config.h", header))
    result.files.append(("safety_monitor.c", impl))


def _rp2040_header(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety config — RP2040/Pico SDK */",
        "/* IEC 61508 inspired — generated by boardsmith-fw */",
        "#ifndef SAFETY_CONFIG_H",
        "#define SAFETY_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "/* Watchdog */",
        f"#define SAFETY_WDT_ENABLED       {_bool_c(cfg.watchdog.enabled)}",
        f"#define SAFETY_WDT_TIMEOUT_MS    {cfg.watchdog.timeout_ms}",
        "",
        "/* Stack overflow detection */",
        f"#define SAFETY_STACK_ENABLED     {_bool_c(cfg.stack.enabled)}",
        f"#define SAFETY_STACK_CHECK_MS    {cfg.stack.check_interval_ms}",
        f"#define SAFETY_STACK_MIN_FREE    {cfg.stack.min_free_bytes}",
        f"#define SAFETY_STACK_PAINT       0x{cfg.stack.paint_pattern:08X}u",
        "",
        "/* Heap monitoring */",
        f"#define SAFETY_HEAP_ENABLED      {_bool_c(cfg.heap.enabled)}",
        f"#define SAFETY_HEAP_CHECK_MS     {cfg.heap.check_interval_ms}",
        f"#define SAFETY_HEAP_LOW_WATER    {cfg.heap.low_watermark_bytes}",
        "",
        "void safety_init(void);",
        "void safety_wdt_feed(void);",
        "void safety_check(void);",
        "",
        "#endif /* SAFETY_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _rp2040_impl(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety monitor — RP2040/Pico SDK */",
        '#include "safety_config.h"',
        "",
        '#include "pico/stdlib.h"',
        '#include "hardware/watchdog.h"',
        "",
        "static uint32_t last_stack_check;",
        "static uint32_t last_heap_check;",
        "",
    ]

    # Stack check helper
    if cfg.stack.enabled:
        lines += [
            "/* Linker symbols */",
            "extern uint32_t __StackBottom;",
            "extern uint32_t __StackLimit;",
            "",
            "static uint32_t stack_check_free(void) {",
            "    volatile uint32_t *bottom = &__StackBottom;",
            "    uint32_t free_words = 0;",
            "    while (*bottom == SAFETY_STACK_PAINT) {",
            "        free_words++;",
            "        bottom++;",
            "    }",
            "    return free_words * 4;",
            "}",
            "",
        ]

    # safety_init
    lines += [
        "void safety_init(void) {",
    ]

    if cfg.watchdog.enabled:
        lines += [
            "#if SAFETY_WDT_ENABLED",
            "    watchdog_enable(SAFETY_WDT_TIMEOUT_MS, true);",
            '    printf("[safety] watchdog enabled: %dms\\n", SAFETY_WDT_TIMEOUT_MS);',
            "#endif",
        ]

    lines += [
        "    last_stack_check = 0;",
        "    last_heap_check = 0;",
        '    printf("[safety] safety monitor initialized\\n");',
        "}",
        "",
    ]

    # safety_wdt_feed
    lines += [
        "void safety_wdt_feed(void) {",
        "#if SAFETY_WDT_ENABLED",
        "    watchdog_update();",
        "#endif",
        "}",
        "",
    ]

    # safety_check — called from main loop
    lines += [
        "void safety_check(void) {",
        "    uint32_t now = to_ms_since_boot(get_absolute_time());",
    ]

    if cfg.stack.enabled:
        lines += [
            "#if SAFETY_STACK_ENABLED",
            "    if (now - last_stack_check >= SAFETY_STACK_CHECK_MS) {",
            "        last_stack_check = now;",
            "        uint32_t free = stack_check_free();",
            "        if (free < SAFETY_STACK_MIN_FREE) {",
            '            printf("[safety] STACK LOW: %u bytes\\n", free);',
            "        }",
            "    }",
            "#endif",
        ]

    if cfg.heap.enabled:
        lines += [
            "#if SAFETY_HEAP_ENABLED",
            "    if (now - last_heap_check >= SAFETY_HEAP_CHECK_MS) {",
            "        last_heap_check = now;",
            "        /* RP2040: no built-in heap stats — application-specific */",
            "    }",
            "#endif",
        ]

    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# nRF52 / Zephyr
# ---------------------------------------------------------------------------


def _gen_nrf52(cfg: SafetyConfig, result: SafetyCodegenResult) -> None:
    header = _nrf52_header(cfg)
    impl = _nrf52_impl(cfg)
    result.files.append(("src/safety_config.h", header))
    result.files.append(("src/safety_monitor.c", impl))


def _nrf52_header(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety config — nRF52/Zephyr */",
        "/* IEC 61508 inspired — generated by boardsmith-fw */",
        "#ifndef SAFETY_CONFIG_H",
        "#define SAFETY_CONFIG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "/* Watchdog */",
        f"#define SAFETY_WDT_ENABLED       {_bool_c(cfg.watchdog.enabled)}",
        f"#define SAFETY_WDT_TIMEOUT_MS    {cfg.watchdog.timeout_ms}",
        "",
        "/* Stack overflow detection */",
        f"#define SAFETY_STACK_ENABLED     {_bool_c(cfg.stack.enabled)}",
        f"#define SAFETY_STACK_CHECK_MS    {cfg.stack.check_interval_ms}",
        f"#define SAFETY_STACK_MIN_FREE    {cfg.stack.min_free_bytes}",
        "",
        "/* Heap monitoring */",
        f"#define SAFETY_HEAP_ENABLED      {_bool_c(cfg.heap.enabled)}",
        f"#define SAFETY_HEAP_CHECK_MS     {cfg.heap.check_interval_ms}",
        f"#define SAFETY_HEAP_LOW_WATER    {cfg.heap.low_watermark_bytes}",
        "",
        "void safety_init(void);",
        "void safety_wdt_feed(void);",
        "",
        "#endif /* SAFETY_CONFIG_H */",
        "",
    ]
    return "\n".join(lines)


def _nrf52_impl(cfg: SafetyConfig) -> str:
    lines = [
        "/* boardsmith-fw safety monitor — nRF52/Zephyr */",
        '#include "safety_config.h"',
        "",
        '#include <zephyr/kernel.h>',
        '#include <zephyr/logging/log.h>',
    ]

    if cfg.watchdog.enabled:
        lines.append('#include <zephyr/drivers/watchdog.h>')

    lines += [
        "",
        'LOG_MODULE_REGISTER(safety, LOG_LEVEL_WRN);',
        "",
    ]

    if cfg.watchdog.enabled:
        lines += [
            "#if SAFETY_WDT_ENABLED",
            "static const struct device *wdt_dev;",
            "static int wdt_channel_id;",
            "#endif",
            "",
        ]

    # Monitor thread
    if cfg.stack.enabled or cfg.heap.enabled:
        lines += [
            "static void safety_monitor_entry(void *p1, void *p2, void *p3) {",
            "    ARG_UNUSED(p1); ARG_UNUSED(p2); ARG_UNUSED(p3);",
            "",
            "    for (;;) {",
        ]

        if cfg.stack.enabled:
            lines += [
                "#if SAFETY_STACK_ENABLED",
                "        size_t unused = 0;",
                "        k_thread_stack_space_get(k_current_get(), &unused);",
                "        if (unused < SAFETY_STACK_MIN_FREE) {",
                '            LOG_WRN("Stack low: %zu bytes remaining", unused);',
                "        }",
                "#endif",
            ]

        if cfg.heap.enabled:
            lines += [
                "#if SAFETY_HEAP_ENABLED",
                "        /* Zephyr: application-specific heap check */",
                "#endif",
            ]

        period = min(
            cfg.stack.check_interval_ms if cfg.stack.enabled else 99999,
            cfg.heap.check_interval_ms if cfg.heap.enabled else 99999,
        )
        lines += [
            f"        k_msleep({period});",
            "    }",
            "}",
            "",
            "K_THREAD_DEFINE(safety_mon, 1024, safety_monitor_entry, NULL, NULL, NULL, 14, 0, 0);",
            "",
        ]

    # safety_init
    lines += [
        "void safety_init(void) {",
    ]
    if cfg.watchdog.enabled:
        lines += [
            "#if SAFETY_WDT_ENABLED",
            '    wdt_dev = DEVICE_DT_GET(DT_ALIAS(watchdog0));',
            "    if (device_is_ready(wdt_dev)) {",
            "        struct wdt_timeout_cfg cfg = {",
            "            .window.max = SAFETY_WDT_TIMEOUT_MS,",
            "            .callback = NULL,",
            "            .flags = WDT_FLAG_RESET_SOC,",
            "        };",
            "        wdt_channel_id = wdt_install_timeout(wdt_dev, &cfg);",
            "        wdt_setup(wdt_dev, 0);",
            '        LOG_INF("Watchdog enabled: %dms", SAFETY_WDT_TIMEOUT_MS);',
            "    }",
            "#endif",
        ]
    lines += [
        '    LOG_INF("Safety monitor initialized");',
        "}",
        "",
    ]

    # safety_wdt_feed
    lines += [
        "void safety_wdt_feed(void) {",
        "#if SAFETY_WDT_ENABLED",
        "    if (wdt_dev && device_is_ready(wdt_dev)) {",
        "        wdt_feed(wdt_dev, wdt_channel_id);",
        "    }",
        "#endif",
        "}",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------


def _gen_summary(cfg: SafetyConfig, target: str) -> str:
    lines = [
        "# Safety Configuration Summary",
        "",
        f"Target: **{target}**",
        "",
        "## Watchdog",
        "",
        f"- Enabled: {cfg.watchdog.enabled}",
        f"- Timeout: {cfg.watchdog.timeout_ms}ms",
    ]
    if cfg.watchdog.panic_on_trigger:
        lines.append("- Action: System reset on trigger")
    else:
        lines.append("- Action: Callback on trigger")

    lines += [
        "",
        "## Stack Overflow Detection",
        "",
        f"- Enabled: {cfg.stack.enabled}",
        f"- Check interval: {cfg.stack.check_interval_ms}ms",
        f"- Minimum free: {cfg.stack.min_free_bytes} bytes",
    ]

    if target in ("esp32", "esp32c3"):
        lines.append("- Method: FreeRTOS `uxTaskGetStackHighWaterMark()` + overflow hook")
    elif target == "stm32":
        lines.append(
            f"- Method: Stack painting (pattern 0x{cfg.stack.paint_pattern:08X})"
        )
    elif target == "rp2040":
        lines.append(
            f"- Method: Stack painting (pattern 0x{cfg.stack.paint_pattern:08X})"
        )
    elif target == "nrf52":
        lines.append("- Method: Zephyr `k_thread_stack_space_get()`")

    lines += [
        "",
        "## Heap Monitoring",
        "",
        f"- Enabled: {cfg.heap.enabled}",
        f"- Check interval: {cfg.heap.check_interval_ms}ms",
        f"- Low watermark: {cfg.heap.low_watermark_bytes} bytes",
    ]

    if target in ("esp32", "esp32c3"):
        lines.append("- Method: `esp_get_free_heap_size()`")
    elif target == "stm32":
        lines.append("- Method: Application-specific heap tracking")
    elif target == "rp2040":
        lines.append("- Method: Application-specific heap tracking")
    elif target == "nrf52":
        lines.append("- Method: Zephyr kernel heap tracking")

    lines += [
        "",
        "## IEC 61508 Coverage",
        "",
        "| Requirement | Implementation |",
        "|-------------|---------------|",
        "| Watchdog supervision | Hardware/software WDT with configurable timeout |",
        "| Stack monitoring | Periodic high-watermark check / stack painting |",
        "| Memory integrity | Heap low-watermark alerting |",
        "| Fail-safe state | System reset on critical failure |",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _bool_c(val: bool) -> str:
    return "1" if val else "0"


def _sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_")
