# SPDX-License-Identifier: AGPL-3.0-or-later
"""Multi-Board Topology Code Generator.

For each node in a topology, generates:
  - Message struct definitions (shared header)
  - Communication setup and send/receive functions
  - Per-node main scaffold

Supports UART, ESP-NOW, and MQTT communication protocols.

Usage:
    from boardsmith_fw.codegen.topology_codegen import generate_topology
    result = generate_topology(topology)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

import yaml

from boardsmith_fw.models.topology import (
    BoardNode,
    CommLink,
    MessageDef,
    TopologyRoot,
)

# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------


@dataclass
class TopologyCodegenResult:
    files: list[tuple[str, str]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_topology(topology: TopologyRoot) -> TopologyCodegenResult:
    """Generate code for all nodes in a topology."""
    result = TopologyCodegenResult()

    if not topology.nodes:
        result.warnings.append("No nodes defined in topology")
        return result

    # Shared message header
    if topology.messages:
        result.files.append(("shared/messages.h", _gen_messages_header(topology)))

    # Per-node code
    for node in topology.nodes:
        prefix = f"{_sanitize(node.id)}"
        outgoing = topology.get_outgoing_links(node.id)
        incoming = topology.get_incoming_links(node.id)

        header = _gen_node_comm_header(node, outgoing, incoming, topology)
        impl = _gen_node_comm_impl(node, outgoing, incoming, topology)

        result.files.append((f"{prefix}/comm.h", header))
        result.files.append((f"{prefix}/comm.c", impl))

    # Summary
    result.files.append(("topology_summary.md", _gen_summary(topology)))

    return result


def parse_topology(yaml_str: str) -> TopologyRoot:
    """Parse a topology YAML string into a TopologyRoot."""
    raw = yaml.safe_load(yaml_str)
    return TopologyRoot(**raw)


def parse_topology_file(path) -> TopologyRoot:
    """Parse a topology YAML file."""
    from pathlib import Path

    text = Path(path).read_text(encoding="utf-8")
    return parse_topology(text)


# ---------------------------------------------------------------------------
# Shared messages header
# ---------------------------------------------------------------------------


def _gen_messages_header(topo: TopologyRoot) -> str:
    lines = [
        f"/* boardsmith-fw topology: {topo.system_name} — shared messages */",
        "/* Generated by boardsmith-fw topology compiler */",
        "#ifndef TOPOLOGY_MESSAGES_H",
        "#define TOPOLOGY_MESSAGES_H",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
    ]

    for msg in topo.messages:
        struct_name = f"{_sanitize(msg.name)}_t"
        lines += [
            f"/* Message: {msg.name} */",
            "typedef struct {",
        ]
        for fld in msg.fields:
            c_type = _map_type(fld.type)
            lines.append(f"    {c_type} {_sanitize(fld.name)};")
        lines += [
            f"}} __attribute__((packed)) {struct_name};",
            "",
        ]

    lines += [
        "#endif /* TOPOLOGY_MESSAGES_H */",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-node comm header
# ---------------------------------------------------------------------------


def _gen_node_comm_header(
    node: BoardNode,
    outgoing: list[CommLink],
    incoming: list[CommLink],
    topo: TopologyRoot,
) -> str:
    safe_id = _sanitize(node.id).upper()
    lines = [
        f"/* boardsmith-fw topology: {node.id} communication */",
        f"/* Role: {node.role} — MCU: {node.mcu or node.family} */",
        f"#ifndef COMM_{safe_id}_H",
        f"#define COMM_{safe_id}_H",
        "",
        '#include "messages.h"',
        "",
        "void comm_init(void);",
        "",
    ]

    # Send functions for outgoing links
    for link in outgoing:
        for msg_name in link.messages:
            msg = topo.get_message(msg_name)
            if msg:
                fn = f"comm_send_{_sanitize(msg_name)}"
                struct = f"{_sanitize(msg_name)}_t"
                lines.append(f"int {fn}(const {struct} *msg);")

    # Receive callbacks for incoming links
    for link in incoming:
        for msg_name in link.messages:
            msg = topo.get_message(msg_name)
            if msg:
                fn = f"comm_on_{_sanitize(msg_name)}"
                struct = f"{_sanitize(msg_name)}_t"
                lines.append(f"void {fn}(const {struct} *msg);")

    lines += [
        "",
        f"#endif /* COMM_{safe_id}_H */",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-node comm implementation
# ---------------------------------------------------------------------------


def _gen_node_comm_impl(
    node: BoardNode,
    outgoing: list[CommLink],
    incoming: list[CommLink],
    topo: TopologyRoot,
) -> str:
    lines = [
        f"/* boardsmith-fw topology: {node.id} communication impl */",
        '#include "comm.h"',
        "",
    ]

    # Target-specific includes
    if node.family == "esp32":
        lines += _esp32_includes(outgoing, incoming)
    elif node.family == "stm32":
        lines += _stm32_includes()
    elif node.family == "rp2040":
        lines += _rp2040_includes()

    lines.append("")

    # comm_init
    lines += _gen_comm_init(node, outgoing, incoming, topo)

    # Send functions
    for link in outgoing:
        for msg_name in link.messages:
            msg = topo.get_message(msg_name)
            if msg:
                lines += _gen_send_fn(node, link, msg)

    # Receive callbacks (stub)
    for link in incoming:
        for msg_name in link.messages:
            msg = topo.get_message(msg_name)
            if msg:
                lines += _gen_recv_stub(node, msg)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# comm_init per target
# ---------------------------------------------------------------------------


def _gen_comm_init(
    node: BoardNode,
    outgoing: list[CommLink],
    incoming: list[CommLink],
    topo: TopologyRoot,
) -> list[str]:
    lines = ["void comm_init(void) {"]

    all_links = outgoing + incoming
    protocols = {lk.protocol for lk in all_links}

    if node.family == "esp32":
        if "uart" in protocols:
            baud = _get_baud(all_links, "uart")
            lines += [
                "    /* UART setup */",
                "    const uart_config_t uart_cfg = {",
                f"        .baud_rate = {baud},",
                "        .data_bits = UART_DATA_8_BITS,",
                "        .parity = UART_PARITY_DISABLE,",
                "        .stop_bits = UART_STOP_BITS_1,",
                "        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,",
                "    };",
                "    uart_param_config(UART_NUM_1, &uart_cfg);",
                "    uart_driver_install(UART_NUM_1, 1024, 1024, 0, NULL, 0);",
            ]
        if "esp_now" in protocols:
            lines += [
                "    /* ESP-NOW setup */",
                "    esp_now_init();",
            ]
        if "mqtt" in protocols:
            lines += [
                "    /* MQTT setup */",
                "    /* Configure MQTT client in application code */",
            ]

    elif node.family == "stm32":
        if "uart" in protocols:
            baud = _get_baud(all_links, "uart")
            lines += [
                "    /* UART configured by CubeMX — verify baud rate */",
                f"    /* Expected: {baud} baud */",
            ]

    elif node.family == "rp2040":
        if "uart" in protocols:
            baud = _get_baud(all_links, "uart")
            lines += [
                "    /* UART setup */",
                f"    uart_init(uart0, {baud});",
            ]

    lines += ["}", ""]
    return lines


# ---------------------------------------------------------------------------
# Send function generation
# ---------------------------------------------------------------------------


def _gen_send_fn(node: BoardNode, link: CommLink, msg: MessageDef) -> list[str]:
    fn = f"comm_send_{_sanitize(msg.name)}"
    struct = f"{_sanitize(msg.name)}_t"
    lines = [f"int {fn}(const {struct} *msg) {{"]

    if link.protocol == "uart":
        if node.family == "esp32":
            lines += [
                f"    int written = uart_write_bytes(UART_NUM_1, (const char *)msg, sizeof({struct}));",
                f"    return (written == sizeof({struct})) ? 0 : -1;",
            ]
        elif node.family == "stm32":
            lines += [
                f"    HAL_StatusTypeDef st = HAL_UART_Transmit(&huart1, (uint8_t *)msg, sizeof({struct}), 100);",
                "    return (st == HAL_OK) ? 0 : -1;",
            ]
        elif node.family == "rp2040":
            lines += [
                f"    uart_write_blocking(uart0, (const uint8_t *)msg, sizeof({struct}));",
                "    return 0;",
            ]

    elif link.protocol == "esp_now":
        lines += [
            "    /* ESP-NOW broadcast */",
            "    uint8_t broadcast[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};",
            f"    esp_err_t err = esp_now_send(broadcast, (const uint8_t *)msg, sizeof({struct}));",
            "    return (err == ESP_OK) ? 0 : -1;",
        ]

    elif link.protocol == "mqtt":
        topic = link.topic or f"topology/{_sanitize(msg.name)}"
        lines += [
            f'    /* MQTT publish to: {topic} */',
            f'    return mqtt_publish("{topic}", (const uint8_t *)msg, sizeof({struct}));',
        ]

    elif link.protocol == "can":
        lines += [
            "    /* CAN frame send */",
            "    can_frame_t frame = {0};",
            f"    frame.can_id = COMM_{_sanitize(msg.name).upper()}_CAN_ID;",
            f"    frame.can_dlc = (uint8_t)(sizeof({struct}) < 8 ? sizeof({struct}) : 8);",
            "    memcpy(frame.data, msg, frame.can_dlc);",
            "    return can_send(&frame, CAN_TIMEOUT_MS);",
        ]
    elif link.protocol in ("ble", "bluetooth"):
        lines += [
            "    /* BLE GATT notification */",
            f"    return ble_notify_char(COMM_{_sanitize(msg.name).upper()}_UUID,",
            f"                          (const uint8_t *)msg, sizeof({struct}));",
        ]
    elif link.protocol == "spi":
        lines += [
            "    /* SPI write */",
            f"    return spi_write_blocking(spi0, (const uint8_t *)msg, sizeof({struct}));",
        ]
    elif link.protocol == "i2c":
        target_addr = getattr(link, "address", "0x00") or "0x00"
        lines += [
            "    /* I2C write */",
            f"    return i2c_write_blocking(i2c0, {target_addr},",
            f"                             (const uint8_t *)msg, sizeof({struct}), false);",
        ]
    else:
        lines += [
            f"    /* Protocol '{link.protocol}' not implemented — add custom send code here */",
            "    (void)msg; /* suppress unused-parameter warning */",
            "    return -1;",
        ]

    lines += ["}", ""]
    return lines


# ---------------------------------------------------------------------------
# Receive stub generation
# ---------------------------------------------------------------------------


def _gen_recv_stub(node: BoardNode, msg: MessageDef) -> list[str]:
    fn = f"comm_on_{_sanitize(msg.name)}"
    struct = f"{_sanitize(msg.name)}_t"
    lines = [
        "/* Callback — implement application logic here */",
        f"__attribute__((weak)) void {fn}(const {struct} *msg) {{",
        "    (void)msg;",
        "}",
        "",
    ]
    return lines


# ---------------------------------------------------------------------------
# Target-specific includes
# ---------------------------------------------------------------------------


def _esp32_includes(outgoing: list[CommLink], incoming: list[CommLink]) -> list[str]:
    all_links = outgoing + incoming
    protocols = {lk.protocol for lk in all_links}
    lines = ['#include "esp_log.h"']
    if "uart" in protocols:
        lines.append('#include "driver/uart.h"')
    if "esp_now" in protocols:
        lines.append('#include "esp_now.h"')
    return lines


def _stm32_includes() -> list[str]:
    return ['#include "stm32f4xx_hal.h"', "extern UART_HandleTypeDef huart1;"]


def _rp2040_includes() -> list[str]:
    return ['#include "pico/stdlib.h"', '#include "hardware/uart.h"']


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------


def _gen_summary(topo: TopologyRoot) -> str:
    lines = [
        f"# Topology Summary: {topo.system_name}",
        "",
        f"Schema: v{topo.boardsmith_fw_topology}",
        "",
        "## Nodes",
        "",
        "| ID | Name | MCU | Role |",
        "|----|------|-----|------|",
    ]
    for node in topo.nodes:
        lines.append(f"| {node.id} | {node.name} | {node.mcu or node.family} | {node.role} |")

    lines += [
        "",
        "## Messages",
        "",
    ]
    for msg in topo.messages:
        fields = ", ".join(f"{f.name}: {f.type}" for f in msg.fields)
        lines.append(f"- **{msg.name}**: {fields}")

    lines += [
        "",
        "## Communication Links",
        "",
        "| Source | Target | Protocol | Messages |",
        "|--------|--------|----------|----------|",
    ]
    for link in topo.links:
        msgs = ", ".join(link.messages)
        lines.append(f"| {link.source} | {link.target} | {link.protocol} | {msgs} |")

    lines += [
        "",
        "## Generated Files",
        "",
        "- `shared/messages.h` — Packed message structs",
    ]
    for node in topo.nodes:
        prefix = _sanitize(node.id)
        lines.append(f"- `{prefix}/comm.h` + `comm.c` — {node.id} communication layer")
    lines.append("- `topology_summary.md` — This file")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_")


def _map_type(t: str) -> str:
    mapping = {
        "float": "float",
        "double": "double",
        "int32": "int32_t",
        "int16": "int16_t",
        "int8": "int8_t",
        "uint32": "uint32_t",
        "uint16": "uint16_t",
        "uint8": "uint8_t",
        "bool": "bool",
    }
    # Handle char[N] arrays
    if t.startswith("char["):
        return t.replace("[", " name[")  # gets overridden by field name
    return mapping.get(t, "uint8_t")


def _escape(text: str) -> str:
    return text.replace('"', '\\"').replace("\\", "\\\\")


def _bool_c(val: bool) -> str:
    return "1" if val else "0"


def _get_baud(links: list[CommLink], protocol: str) -> int:
    for lk in links:
        if lk.protocol == protocol:
            return lk.baud_rate
    return 115200
