// Auto-generated by boardsmith-fw for target: rp2040
// HIR version: 1.1.0
// Components: ['RP2040 Dual-Core ARM Cortex-M0+ MCU', 'Green Status LED 0603', 'TXB0104 4-Bit Bidirectional Voltage Level Translator', 'USB Type-C Receptacle Connector', 'W25Q16JVSSIQ 16Mbit QSPI NOR Boot Flash', 'BSS138 N-Channel MOSFET Level Shifter', 'ARM SWD 2x5 1.27mm Debug Header', '100nF Capacitor (decoupling_vdd_RP2040)', '100nF Capacitor (decoupling_vdd_LTST_C150GKT)', '100nF Capacitor (decoupling_vdd_TXB0104)', '100nF Capacitor (decoupling_vdd_USB_C_CONN)', '10uF Capacitor (bulk_cap_VIN_5V)', '10uF Capacitor (bulk_cap_3V3_REG)', '10uF Capacitor (ldo_input_cap_U_LDO1)', '10uF Capacitor (ldo_output_bulk_U_LDO1)', '100nF Capacitor (ldo_output_noise_U_LDO1)', '330Ω Resistor (led_series_LTST_C150GKT)', '10kΩ Resistor (reset_pullup_RUN)', '100nF Capacitor (reset_filter_RUN)', '10kΩ Resistor (boot_pullup_QSPI_SS)', '12MHz Crystal (main_crystal_12mhz)', '20pF Capacitor (crystal_load_cap_XIN)', '20pF Capacitor (crystal_load_cap_XOUT)', '10kΩ Resistor (levelshift_pullup_LTST-C150GKT_3.3V)', '10kΩ Resistor (levelshift_pullup_LTST-C150GKT_2.1V)', '10kΩ Resistor (levelshift_pullup_USB-C-CONN_3.3V)', '10kΩ Resistor (levelshift_pullup_USB-C-CONN_5.0V)', '33Ω Resistor (spi_sck_series_qspi_boot)', '10kΩ Resistor (spi_cs_pullup_W25Q16JVSSIQ)', '5.1kΩ Resistor (usbc_cc1_pulldown)', '5.1kΩ Resistor (usbc_cc2_pulldown)', '10µFF Cap (mcu_mandatory_Bulk_decoupling_for_IO_supply)', '1µFF Cap (mcu_mandatory_On-chip_regulator_output_decoupling_(man)', '1kΩΩ Resistor (mcu_mandatory_RP2040_HW_Guide:_1kΩ_between_XIN_and_GND)', '27ΩΩ Resistor (mcu_mandatory_USB_D+/D-_series_resistors_(2×_required))', 'AMS1117-3.3 LDO 5V→3.3V']

void init_all_peripherals() {
    // TODO: implement for rp2040
}

int main() {
    init_all_peripherals();
    return 0;
}
