# SPDX-License-Identifier: AGPL-3.0-or-later
"""Actuator seed data — motor drivers, servo controllers, audio amplifiers."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    {
        "mpn": "DRV8825",
        "manufacturer": "Texas Instruments",
        "name": "DRV8825 Stepper Motor Driver",
        "category": "actuator",
        "sub_type": "stepper-driver",
        "interface_types": ["GPIO"],
        "package": "HTSSOP-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "Bipolar stepper motor driver, 2.5A, 45V, up to 1/32 microstepping",
        "electrical_ratings": {
            "vdd_min": 8.2, "vdd_max": 45.0,
            "io_voltage_min": 2.5, "io_voltage_max": 5.25, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 2500.0, "current_draw_max_ma": 2500.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Set nRESET/nSLEEP HIGH, configure M0/M1/M2 microstepping, set DIR",
             "delay_after_ms": 2},
        ]},
        "unit_cost_usd": 4.00,
        "tags": ["stepper", "motor", "driver", "gpio"],
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/drv8825.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "actuator_type": "stepper-driver",
            "channels": 1,
            "output_current_max_ma": 2500,
            "output_voltage_max_v": 45.0,
            "h_bridge": True,
            "bidirectional": True,
            "current_sensing": True,
            "microstepping": "1/32",
            "amplifier_class": None,
            "output_power_w": None,
            "sample_rates_khz": None,
            "bit_depth": None,
            "pop_click_suppression": False,
            "resolution_bits": None,
            "update_rate_sps": None,
        },
    },
    {
        "mpn": "A4988",
        "manufacturer": "Allegro MicroSystems",
        "name": "A4988 Stepper Motor Driver",
        "category": "actuator",
        "sub_type": "stepper-driver",
        "interface_types": ["GPIO"],
        "package": "QFN-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "DMOS microstepping bipolar stepper motor driver, 2A, 35V",
        "electrical_ratings": {
            "vdd_min": 8.0, "vdd_max": 35.0,
            "io_voltage_min": 3.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 2000.0, "current_draw_max_ma": 2000.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Set nRESET/nSLEEP HIGH, configure MS1/MS2/MS3",
             "delay_after_ms": 1},
        ]},
        "unit_cost_usd": 3.50,
        "tags": ["stepper", "motor", "driver", "gpio"],
        "datasheet_url": "https://www.allegromicro.com/~/media/files/datasheets/a4988-datasheet.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "actuator_type": "stepper-driver",
            "channels": 1,
            "output_current_max_ma": 2000,
            "output_voltage_max_v": 35.0,
            "h_bridge": True,
            "bidirectional": True,
            "current_sensing": True,
            "microstepping": "1/16",
            "amplifier_class": None,
            "output_power_w": None,
            "sample_rates_khz": None,
            "bit_depth": None,
            "pop_click_suppression": False,
            "resolution_bits": None,
            "update_rate_sps": None,
        },
    },
    {
        "mpn": "PCA9685",
        "manufacturer": "NXP",
        "name": "PCA9685 16-Channel 12-Bit PWM/LED Driver",
        "category": "actuator",
        "sub_type": "servo-ctrl",
        "interface_types": ["I2C"],
        "package": "TSSOP-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "16-channel, 12-bit PWM I2C LED/servo controller",
        "electrical_ratings": {
            "vdd_min": 2.3, "vdd_max": 5.5,
            "io_voltage_min": 2.3, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 6.0, "current_draw_max_ma": 400.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"]},
        "known_i2c_addresses": [
            "0x40", "0x41", "0x42", "0x43", "0x44", "0x45", "0x46", "0x47",
            "0x48", "0x49", "0x4A", "0x4B", "0x4C", "0x4D", "0x4E", "0x4F",
        ],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x00", "value": "0x10", "description": "Sleep mode for prescaler"},
                 {"reg_addr": "0xFE", "value": "0x79", "description": "50Hz prescaler (servos)"},
                 {"reg_addr": "0x00", "value": "0x20", "description": "Wake, auto-increment"},
             ], "delay_after_ms": 1},
        ]},
        "unit_cost_usd": 3.00,
        "tags": ["pwm", "servo", "led", "driver", "16-channel"],
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/PCA9685.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf", "zephyr"],
        "capabilities": {
            "actuator_type": "servo-ctrl",
            "channels": 16,
            "output_current_max_ma": 25,
            "output_voltage_max_v": 5.5,
            "h_bridge": False,
            "bidirectional": False,
            "current_sensing": False,
            "microstepping": None,
            "amplifier_class": None,
            "output_power_w": None,
            "sample_rates_khz": None,
            "bit_depth": None,
            "pop_click_suppression": False,
            "resolution_bits": 12,
            "update_rate_sps": None,
        },
    },
    {
        "mpn": "TB6612FNG",
        "manufacturer": "Toshiba",
        "name": "TB6612FNG Dual DC Motor Driver",
        "category": "actuator",
        "sub_type": "motor-driver",
        "interface_types": ["GPIO"],
        "package": "SSOP-24",
        "mounting": "smd",
        "pin_count": 24,
        "description": "Dual H-bridge DC motor driver, 1.2A continuous, 3.2A peak",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 13.5,
            "io_voltage_min": 2.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1200.0, "current_draw_max_ma": 3200.0,
            "temp_min_c": -20.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Set STBY HIGH to enable, set AIN1/AIN2 + PWMA for motor A, BIN1/BIN2 + PWMB for B"},
        ]},
        "unit_cost_usd": 2.80,
        "tags": ["dc-motor", "h-bridge", "driver", "gpio"],
        "datasheet_url": "https://toshiba.semicon-storage.com/info/TB6612FNG_datasheet_en_20141001.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "actuator_type": "motor-driver",
            "channels": 2,
            "output_current_max_ma": 1200,
            "output_voltage_max_v": 13.5,
            "h_bridge": True,
            "bidirectional": True,
            "current_sensing": False,
            "microstepping": None,
            "amplifier_class": None,
            "output_power_w": None,
            "sample_rates_khz": None,
            "bit_depth": None,
            "pop_click_suppression": False,
            "resolution_bits": None,
            "update_rate_sps": None,
        },
    },
    {
        "mpn": "MAX98357AETE+T",
        "manufacturer": "Maxim Integrated",
        "name": "MAX98357A I2S Class-D Amplifier",
        "category": "actuator",
        "sub_type": "amplifier",
        "interface_types": ["I2S"],
        "package": "TQFN-16",
        "mounting": "smd",
        "pin_count": 16,
        "description": "3.2W filterless Class-D mono amplifier with I2S input, no MCLK needed",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 5.5,
            "io_voltage_min": 1.8, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 600.0, "current_draw_max_ma": 1500.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Configure I2S master (BCLK, LRCLK, DIN) — no register writes needed, auto-detects sample rate"},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["audio", "amplifier", "i2s", "class-d", "speaker"],
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX98357A-MAX98357B.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "actuator_type": "amplifier",
            "channels": 1,
            "output_current_max_ma": 1500,
            "output_voltage_max_v": 5.5,
            "h_bridge": False,
            "bidirectional": False,
            "current_sensing": False,
            "microstepping": None,
            "amplifier_class": "D",
            "output_power_w": 3.2,
            "sample_rates_khz": [8, 16, 32, 44.1, 48, 88.2, 96],
            "bit_depth": 32,
            "pop_click_suppression": True,
            "resolution_bits": None,
            "update_rate_sps": None,
        },
    },
    {
        "mpn": "PCM5102APWR",
        "manufacturer": "Texas Instruments",
        "name": "PCM5102A 32-bit 384kHz I2S DAC",
        "category": "actuator",
        "sub_type": "dac",
        "interface_types": ["I2S"],
        "package": "TSSOP-20",
        "mounting": "smd",
        "pin_count": 20,
        "description": "Stereo audio DAC with I2S input, 32-bit/384kHz, \u2212100dB THD+N, no MCLK",
        "electrical_ratings": {
            "vdd_min": 3.3, "vdd_max": 5.25,
            "io_voltage_min": 3.3, "io_voltage_max": 5.25, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 7.0, "current_draw_max_ma": 15.0,
            "temp_min_c": -25.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Tie FMT=0,XSMT=1 for I2S mode; configure I2S BCLK/LRCK/DATA from MCU"},
        ]},
        "unit_cost_usd": 3.50,
        "tags": ["audio", "dac", "i2s", "stereo", "hi-fi"],
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/pcm5102a.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "esp-idf"],
        "capabilities": {
            "actuator_type": "dac",
            "channels": 2,
            "output_current_max_ma": 15,
            "output_voltage_max_v": 3.3,
            "h_bridge": False,
            "bidirectional": False,
            "current_sensing": False,
            "microstepping": None,
            "amplifier_class": None,
            "output_power_w": None,
            "sample_rates_khz": [8, 16, 32, 44.1, 48, 96, 192, 384],
            "bit_depth": 32,
            "pop_click_suppression": True,
            "resolution_bits": 32,
            "update_rate_sps": 384000,
        },
    },

    # --- Seed Expansion (DB-6) ---
    {
        "mpn": "ULN2003A",
        "manufacturer": "Texas Instruments",
        "name": "ULN2003A Darlington Transistor Array",
        "category": "actuator",
        "sub_type": "relay-driver",
        "interface_types": ["GPIO"],
        "package": "PDIP-16",
        "mounting": "thth",
        "pin_count": 16,
        "description": "7-channel Darlington sink driver, 500mA/ch, 50V, for relays, solenoids, LEDs",
        "electrical_ratings": {
            "vdd_min": 5.0, "vdd_max": 50.0,
            "io_voltage_min": 3.3, "io_voltage_max": 5.0, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_max_ma": 3500.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Pull IN1-IN7 HIGH via MCU GPIO to energize corresponding OUT1-OUT7"},
        ]},
        "unit_cost_usd": 0.12,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/uln2003a.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython"],
        "capabilities": {
            "actuator_type": "relay-driver",
            "channels": 7,
            "output_current_max_ma": 500,
            "output_voltage_max_v": 50.0,
            "h_bridge": False,
            "bidirectional": False,
            "current_sensing": False,
            "logic_input_v": 5.0,
            "internal_flyback_diode": True,
        },
        "tags": ["relay", "driver", "darlington", "solenoid", "stepper", "sink"],
    },
    {
        "mpn": "IRLML6244TRPBF",
        "manufacturer": "Infineon",
        "name": "IRLML6244 N-Channel MOSFET 20V 6.3A SOT-23",
        "category": "actuator",
        "sub_type": "mosfet",
        "interface_types": ["GPIO"],
        "package": "SOT-23",
        "mounting": "smd",
        "pin_count": 3,
        "description": "Logic-level N-FET 20V/6.3A, Vgs_th=0.9V — low-side switch for 3.3V GPIO drive",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 20.0,
            "io_voltage_min": 2.5, "io_voltage_max": 10.0, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_max_ma": 6300.0,
            "temp_min_c": -55.0, "temp_max_c": 150.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Configure GPIO as output push-pull. HIGH turns FET on (load sink)."},
        ]},
        "unit_cost_usd": 0.15,
        "datasheet_url": "https://www.infineon.com/dgdl/irlml6244pbf.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "actuator_type": "mosfet",
            "channels": 1,
            "output_current_max_ma": 6300,
            "output_voltage_max_v": 20.0,
            "h_bridge": False,
            "bidirectional": False,
            "current_sensing": False,
            "vgs_threshold_v": 0.9,
            "rds_on_mohm": 19,
            "logic_level": True,
        },
        "tags": ["mosfet", "n-channel", "low-side", "switch", "logic-level", "sot-23"],
    },
]
