# SPDX-License-Identifier: AGPL-3.0-or-later
"""Communication modules seed data — RF, Ethernet, CAN, GNSS, I2C-Mux, USB-UART, RS485."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    {
        "mpn": "NEO-M8N",
        "manufacturer": "u-blox",
        "name": "NEO-M8N GNSS Module",
        "category": "comms",
        "sub_type": "gnss",
        "interface_types": ["UART", "I2C", "SPI"],
        "package": "SMD module",
        "mounting": "module",
        "pin_count": 24,
        "description": "u-blox M8 concurrent GNSS module (GPS, GLONASS, BeiDou, Galileo)",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 1.89,
            "io_voltage_min": 1.71, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 26.0, "current_draw_max_ma": 67.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"uart_max_baud": 921600},
        "known_i2c_addresses": ["0x42"], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 1000, "description": "Module startup"},
            {"phase": "configure", "order": 1,
             "description": "UBX-CFG-PRT: 9600 baud, enable NMEA"},
        ]},
        "unit_cost_usd": 35.00,
        "datasheet_url": "https://content.u-blox.com/sites/default/files/NEO-M8-FW3_DataSheet_UBX-15031086.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "protocol": "gnss",
            "constellations": ["gps", "glonass", "beidou", "galileo"],
            "concurrent_channels": 72,
            "tracking_channels": 22,
            "update_rate_hz": 10,
            "ttff_cold_s": 26,
            "ttff_hot_s": 1,
            "position_accuracy_m": 2.5,
            "rx_sensitivity_dbm": -167.0,
            "frequency_mhz": [1575],
            "antenna": "integrated",
            "pps_output": True,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["gps", "gnss", "navigation", "positioning", "uart"],
    },
    {
        "mpn": "SX1276",
        "manufacturer": "Semtech",
        "name": "SX1276 LoRa/FSK Transceiver",
        "category": "comms",
        "sub_type": "lora",
        "interface_types": ["SPI", "GPIO"],
        "package": "QFN-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "137-1020MHz long range LoRa/FSK transceiver",
        "electrical_ratings": {
            "vdd_min": 1.8, "vdd_max": 3.7,
            "io_voltage_min": 1.8, "io_voltage_max": 3.7, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 120.0, "current_draw_max_ma": 120.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 10000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x01", "value": "0x80", "description": "Sleep mode, LoRa"},
                 {"reg_addr": "0x1D", "value": "0x72", "description": "BW 125kHz, CR 4/5"},
                 {"reg_addr": "0x1E", "value": "0x74", "description": "SF7, CRC on"},
             ]},
            {"phase": "enable", "order": 1,
             "writes": [{"reg_addr": "0x01", "value": "0x81", "description": "Standby mode"}]},
        ]},
        "unit_cost_usd": 8.00,
        "datasheet_url": "https://semtech.my.salesforce.com/sfc/p/E0000000JelG/a/2R000000HT76/7Nka9W5WgugoZe.xwIHJy6ebj1hW8MlN150kkz5FHbA",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "protocol": "lora",
            "data_rate_bps": 37500,
            "tx_power_dbm": 20.0,
            "rx_sensitivity_dbm": -148.0,
            "range_m": 15000,
            "frequency_mhz": [137, 175, 410, 525, 862, 1020],
            "antenna": "ufl",
            "spreading_factors": [6, 7, 8, 9, 10, 11, 12],
            "lorawan": False,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["lora", "rf", "wireless", "long-range", "iot"],
    },
    {
        "mpn": "nRF24L01+",
        "manufacturer": "Nordic Semiconductor",
        "name": "nRF24L01+ 2.4GHz RF Transceiver",
        "category": "comms",
        "sub_type": "rf-transceiver",
        "interface_types": ["SPI", "GPIO"],
        "package": "QFN-20",
        "mounting": "smd",
        "pin_count": 20,
        "description": "2.4GHz ISM band transceiver with Enhanced ShockBurst",
        "electrical_ratings": {
            "vdd_min": 1.9, "vdd_max": 3.6,
            "io_voltage_min": 1.9, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 13.5, "current_draw_max_ma": 13.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 10000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x00", "value": "0x0E", "description": "Power up, CRC 2-byte, PTX"},
                 {"reg_addr": "0x05", "value": "0x4C", "description": "RF channel 76"},
                 {"reg_addr": "0x06", "value": "0x06", "description": "1Mbps, 0dBm"},
             ], "delay_after_ms": 2},
        ]},
        "unit_cost_usd": 1.80,
        "datasheet_url": "https://infocenter.nordicsemi.com/pdf/nRF24L01P_PS_v1.0.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "esp-idf"],
        "capabilities": {
            "protocol": "2.4ghz-proprietary",
            "data_rate_bps": 2000000,
            "tx_power_dbm": 0.0,
            "rx_sensitivity_dbm": -82.0,
            "range_m": 100,
            "frequency_mhz": [2400],
            "antenna": "pcb",
            "max_connections": 6,
            "pipe_count": 6,
            "auto_retransmit": True,
            "auto_ack": True,
            "payload_bytes": 32,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["rf", "wireless", "2.4ghz", "shockburst"],
    },
    {
        "mpn": "ENC28J60",
        "manufacturer": "Microchip",
        "name": "ENC28J60 Ethernet Controller",
        "category": "comms",
        "sub_type": "ethernet",
        "interface_types": ["SPI"],
        "package": "SSOP-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "10Base-T Ethernet controller with SPI interface, 8KB buffer",
        "electrical_ratings": {
            "vdd_min": 3.1, "vdd_max": 3.5,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 170.0, "current_draw_max_ma": 200.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 20000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x1F", "value": "0x80", "description": "System reset"}],
             "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "description": "Set RX/TX buffer boundaries, enable RX"},
        ]},
        "unit_cost_usd": 3.00,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/39662e.pdf",
        "status": "active",
        "library_support": ["arduino", "esp-idf"],
        "capabilities": {
            "protocol": "ethernet",
            "data_rate_bps": 10000000,
            "tcp_ip_stack": False,
            "full_duplex": True,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["ethernet", "network", "10base-t"],
    },
    {
        "mpn": "W5500",
        "manufacturer": "WIZnet",
        "name": "W5500 Hardwired TCP/IP Ethernet Controller",
        "category": "comms",
        "sub_type": "ethernet",
        "interface_types": ["SPI"],
        "package": "LQFP-48",
        "mounting": "smd",
        "pin_count": 48,
        "description": "Hardwired TCP/IP embedded Ethernet controller, 8 sockets, 80MHz SPI",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 3.6,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 132.0, "current_draw_max_ma": 160.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 80000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x0000", "value": "0x80", "description": "Software reset"}],
             "delay_after_ms": 2},
            {"phase": "configure", "order": 1,
             "description": "Set MAC, IP, gateway, subnet mask"},
        ]},
        "unit_cost_usd": 5.00,
        "datasheet_url": "https://docs.wiznet.io/img/products/w5500/W5500_ds_v110e.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "protocol": "ethernet",
            "data_rate_bps": 100000000,
            "tcp_ip_stack": True,
            "max_connections": 8,
            "full_duplex": True,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["ethernet", "network", "tcp-ip", "wiznet"],
    },
    {
        "mpn": "MCP2515",
        "manufacturer": "Microchip",
        "name": "MCP2515 CAN Bus Controller",
        "category": "comms",
        "sub_type": "can",
        "interface_types": ["SPI"],
        "package": "DIP-18",
        "mounting": "tht",
        "pin_count": 18,
        "description": "Stand-alone CAN controller with SPI interface, up to 1Mbps",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 5.5,
            "io_voltage_min": 2.7, "io_voltage_max": 5.5, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 5.0, "current_draw_max_ma": 10.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 10000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "", "value": "0xC0", "description": "SPI reset instruction"}],
             "delay_after_ms": 10},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x0F", "value": "0x80", "description": "Config mode"},
                 {"reg_addr": "0x2A", "value": "0x00", "description": "Bit timing 500kbps@8MHz"},
                 {"reg_addr": "0x0F", "value": "0x00", "description": "Normal operation"},
             ]},
        ]},
        "unit_cost_usd": 2.00,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/MCP2515-Stand-Alone-CAN-Controller-with-SPI-20001801J.pdf",
        "status": "active",
        "library_support": ["arduino", "esp-idf"],
        "capabilities": {
            "protocol": "can",
            "data_rate_bps": 1000000,
            "bus_nodes": 112,
            "full_duplex": False,
            "esd_protection_kv": None,
            "certifications": [],
        },
        "tags": ["can", "bus", "automotive"],
    },
    {
        "mpn": "CC1101",
        "manufacturer": "Texas Instruments",
        "name": "CC1101 Sub-1GHz RF Transceiver",
        "category": "comms",
        "sub_type": "rf-transceiver",
        "interface_types": ["SPI", "GPIO"],
        "package": "QLP-20",
        "mounting": "smd",
        "pin_count": 20,
        "description": "Low-power sub-1GHz RF transceiver (315/433/868/915MHz)",
        "electrical_ratings": {
            "vdd_min": 1.8, "vdd_max": 3.6,
            "io_voltage_min": 1.8, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 30.0, "current_draw_max_ma": 30.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 6500000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "", "value": "0x30", "description": "SRES strobe"}],
             "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "description": "Set frequency, modulation, data rate"},
        ]},
        "unit_cost_usd": 2.50,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/cc1101.pdf",
        "status": "active",
        "library_support": ["arduino", "esp-idf"],
        "capabilities": {
            "protocol": "sub-ghz",
            "modulation": ["2-fsk", "4-fsk", "gfsk", "msk", "ook", "ask"],
            "data_rate_bps": 500000,
            "tx_power_dbm": 12.0,
            "rx_sensitivity_dbm": -112.0,
            "range_m": 500,
            "frequency_mhz": [315, 433, 868, 915],
            "antenna": "ufl",
            "wake_on_radio": True,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["rf", "wireless", "sub-ghz", "433mhz", "868mhz"],
    },
    {
        "mpn": "TCA9548A",
        "manufacturer": "Texas Instruments",
        "name": "TCA9548A 1-to-8 I2C Bus Switch / Multiplexer",
        "category": "comms",
        "sub_type": "i2c-mux",
        "interface_types": ["I2C"],
        "package": "TSSOP-24",
        "mounting": "smd",
        "pin_count": 24,
        "description": (
            "8-channel I2C multiplexer with active-low reset. Enables up to 8 identical-address "
            "I2C slaves by routing them to independent channels."
        ),
        "electrical_ratings": {
            "vdd_min": 1.65, "vdd_max": 5.5,
            "io_voltage_min": 1.65, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.01, "current_draw_max_ma": 0.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x70", "0x71", "0x72", "0x73", "0x74", "0x75", "0x76", "0x77"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "description": "Assert RESET# low then high", "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "description": "Write channel-select byte (bit N=1 enables channel N)"},
        ]},
        "unit_cost_usd": 0.95,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/tca9548a.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "protocol": "i2c-mux",
            "channels": 8,
            "data_rate_bps": 400000,
            "voltage_translation": True,
            "active_low_reset": True,
        },
        "tags": ["i2c", "mux", "multiplexer", "bus-switch", "address-conflict"],
    },
    {
        "mpn": "CH340G",
        "manufacturer": "WCH",
        "name": "CH340G USB to UART Bridge",
        "category": "comms",
        "sub_type": "usb-uart",
        "interface_types": ["UART", "USB"],
        "package": "SOP-16",
        "mounting": "smd",
        "pin_count": 16,
        "description": "USB to serial UART bridge, up to 2Mbps, Windows/Linux/Mac driver",
        "electrical_ratings": {
            "vdd_min": 3.3, "vdd_max": 5.0,
            "io_voltage_min": 3.3, "io_voltage_max": 5.0, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 8.0, "current_draw_max_ma": 20.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"uart_max_baud": 2000000},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.30,
        "datasheet_url": "https://www.wch-ic.com/downloads/CH340DS1_PDF.html",
        "status": "active",
        "library_support": ["arduino"],
        "capabilities": {
            "protocol": "usb-uart",
            "data_rate_bps": 2000000,
            "max_baud": 2000000,
            "auto_reset": False,
            "os_native_driver": False,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["usb", "uart", "serial", "bridge", "ch340"],
    },
    {
        "mpn": "CP2102N-A02-GQFN28R",
        "manufacturer": "Silicon Labs",
        "name": "CP2102N USB to UART Bridge",
        "category": "comms",
        "sub_type": "usb-uart",
        "interface_types": ["UART", "USB"],
        "package": "QFN-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "USB to UART bridge, up to 3Mbps, integrated 5V regulator, auto-baud",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 5.0,
            "io_voltage_min": 1.8, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 10.0, "current_draw_max_ma": 25.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"uart_max_baud": 3000000},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 1.50,
        "datasheet_url": "https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf",
        "status": "active",
        "library_support": ["arduino"],
        "capabilities": {
            "protocol": "usb-uart",
            "data_rate_bps": 3000000,
            "max_baud": 3000000,
            "auto_reset": True,
            "os_native_driver": True,
            "certifications": ["fcc", "ce"],
        },
        "tags": ["usb", "uart", "serial", "bridge", "cp2102"],
    },
    {
        "mpn": "MAX485ESA+",
        "manufacturer": "Maxim Integrated",
        "name": "MAX485 RS-485/RS-422 Transceiver",
        "category": "comms",
        "sub_type": "rs485",
        "interface_types": ["UART"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Half-duplex RS-485/RS-422 transceiver, 2.5Mbps, 5V, low power",
        "electrical_ratings": {
            "vdd_min": 4.75, "vdd_max": 5.25,
            "io_voltage_min": 4.75, "io_voltage_max": 5.25, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.3, "current_draw_max_ma": 2.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"uart_max_baud": 2500000},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Set DE/RE pins: DE=HIGH enables driver (TX), DE=LOW+RE=LOW enables receiver (RX)"},
        ]},
        "unit_cost_usd": 0.80,
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX1487-MAX491.pdf",
        "status": "active",
        "library_support": ["arduino", "esp-idf"],
        "capabilities": {
            "protocol": "rs485",
            "data_rate_bps": 2500000,
            "bus_nodes": 32,
            "full_duplex": False,
            "auto_direction": False,
            "esd_protection_kv": 15.0,
            "certifications": [],
        },
        "tags": ["rs485", "rs422", "serial", "industrial", "half-duplex"],
    },

    # ===================================================================
    # P0.2 — CAN-FD Transceiver + Isolated CAN
    # ===================================================================

    # --- CAN-FD Transceiver (3.3V I/O variant) ---
    {
        "mpn": "MCP2562FD-E/SN",
        "manufacturer": "Microchip",
        "name": "MCP2562FD CAN-FD Transceiver",
        "category": "comms",
        "sub_type": "can-fd",
        "interface_types": ["CAN"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "CAN-FD transceiver supporting up to 8 Mbps data phase, 3.3V I/O, "
                       "5V bus supply, ±58V fault protection, AEC-Q100 automotive qualified, "
                       "low standby current 5uA. Drop-in upgrade from MCP2551",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 5.0, "current_draw_max_ma": 10.0,
            "abs_max_voltage": 58.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
            "sleep_current_ua": 5.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.95,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/MCP2561-2FD-Data-Sheet-DS20005167.pdf",
        "status": "active",
        "library_support": ["arduino", "esp-idf"],
        "capabilities": {
            "protocol": "can_fd",
            "data_rate_bps": 8000000,
            "bus_nodes": 112,
            "fault_protection_v": 58,
            "standby_current_ua": 5,
            "io_voltage_v": 3.3,
            "bus_voltage_v": 5.0,
            "aec_q100": True,
        },
        "tags": ["can-fd", "can", "transceiver", "automotive", "industrial", "3.3v"],
        "tier": "enterprise",
    },

    # --- Isolated CAN Transceiver ---
    {
        "mpn": "ISO1042BQDWRQ1",
        "manufacturer": "Texas Instruments",
        "name": "ISO1042 Isolated CAN Transceiver",
        "category": "comms",
        "sub_type": "isolated-can",
        "interface_types": ["CAN"],
        "package": "SOIC-16W",
        "mounting": "smd",
        "pin_count": 16,
        "description": "Isolated CAN transceiver with 5kVrms reinforced isolation, "
                       "CAN-FD up to 5 Mbps, integrated DC/DC for isolated supply, "
                       "AEC-Q100 automotive. For galvanic isolation between MCU and CAN bus",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_min": 3.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 30.0, "current_draw_max_ma": 60.0,
            "abs_max_voltage": 65.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 4.50,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/iso1042.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "protocol": "can_fd",
            "data_rate_bps": 5000000,
            "isolation_kvrms": 5.0,
            "reinforced_isolation": True,
            "integrated_dcdc": True,
            "fault_protection_v": 65,
            "io_voltage_v": 3.3,
            "aec_q100": True,
        },
        "tags": ["isolated", "can", "can-fd", "galvanic", "automotive", "industrial", "5kv"],
        "tier": "enterprise",
    },

    # ===================================================================
    # DB-6 Seed Expansion — CAN, ESD, RS485, Analog, Isolator
    # ===================================================================

    # --- NXP CAN Transceiver ---
    {
        "mpn": "TJA1051T/3",
        "manufacturer": "NXP Semiconductors",
        "name": "TJA1051T/3 3.3V CAN Bus Transceiver",
        "category": "comms",
        "sub_type": "can-transceiver",
        "interface_types": ["CAN", "GPIO"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "3.3V CAN transceiver, ISO 11898-2, 5Mbps, STB standby pin, SOIC-8",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 50.0, "current_draw_max_ma": 85.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"can_max_bitrate_bps": 5000000},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Pull STB LOW to enter normal mode. Configure CAN peripheral (TXD->pin1, RXD<-pin4)."},
        ]},
        "unit_cost_usd": 0.85,
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/TJA1051.pdf",
        "status": "active",
        "library_support": ["esp-idf", "stm32hal", "zephyr"],
        "capabilities": {
            "protocol": "can",
            "can_version": "2.0B",
            "data_rate_bps": 5000000,
            "bus_nodes": 110,
            "differential": True,
            "termination_builtin": False,
            "esd_protection_kv": 8.0,
            "standby_mode": True,
            "iso_11898": True,
        },
        "tags": ["can", "canbus", "transceiver", "3.3v", "automotive", "industrial"],
    },

    # --- USB ESD Protection ---
    {
        "mpn": "USBLC6-2SC6",
        "manufacturer": "STMicroelectronics",
        "name": "USBLC6-2SC6 USB ESD Protection",
        "category": "comms",
        "sub_type": "esd-protection",
        "interface_types": ["USB"],
        "package": "SOT-23-6",
        "mounting": "smd",
        "pin_count": 6,
        "description": "USB ESD protection TVS array, 0.9pF, SOT-23-6 — per USB spec recommendation",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 5.5,
            "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.18,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/usblc6-2.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "protection_type": "esd",
            "channels": 2,
            "capacitance_pf": 0.9,
            "clamping_voltage_v": 7.0,
            "iec_61000_4_2_kv": 15.0,
            "usb_2_compatible": True,
        },
        "tags": ["esd", "protection", "usb", "tvs", "iec61000", "surge"],
    },

    # --- 3.3V RS-485 Transceiver ---
    {
        "mpn": "SP3485EN-L/TR",
        "manufacturer": "Sipex / MaxLinear",
        "name": "SP3485 3.3V RS-485/RS-422 Transceiver",
        "category": "comms",
        "sub_type": "rs485-transceiver",
        "interface_types": ["RS485", "UART"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "3.3V RS-485 transceiver, 10Mbps, SOIC-8, pin-compatible with MAX485",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 3.6,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.3, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"uart_max_baud": 10000000},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Set DE/~RE: DE=HIGH for TX, DE=LOW+~RE=LOW for RX"},
        ]},
        "unit_cost_usd": 0.40,
        "datasheet_url": "https://www.maxlinear.com/ds/sp3485.pdf",
        "status": "active",
        "library_support": ["arduino", "esp-idf"],
        "capabilities": {
            "protocol": "rs485",
            "data_rate_bps": 10000000,
            "bus_nodes": 32,
            "full_duplex": False,
            "auto_direction": False,
            "esd_protection_kv": 15.0,
        },
        "tags": ["rs485", "serial", "3.3v", "industrial", "half-duplex"],
    },

    # --- USB ESD/TVS Protection (alternative) ---
    {
        "mpn": "PRTR5V0U2X",
        "manufacturer": "Nexperia",
        "name": "PRTR5V0U2X USB ESD/TVS Protection SOT-363",
        "category": "comms",
        "sub_type": "esd-protection",
        "interface_types": ["USB"],
        "package": "SOT-363",
        "mounting": "smd",
        "pin_count": 6,
        "description": "Bidirectional ESD/TVS for USB D+/D- lines, 0.35pF, SOT-363",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 5.5,
            "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.20,
        "datasheet_url": "https://assets.nexperia.com/documents/data-sheet/PRTR5V0U2X.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "protection_type": "esd",
            "channels": 2,
            "capacitance_pf": 0.35,
            "clamping_voltage_v": 6.0,
            "iec_61000_4_2_kv": 8.0,
            "usb_2_compatible": True,
        },
        "tags": ["esd", "protection", "usb", "tvs"],
    },

    # --- Dual Op-Amp ---
    {
        "mpn": "LM358",
        "manufacturer": "Texas Instruments",
        "name": "LM358 Dual Op-Amp",
        "category": "comms",
        "sub_type": "opamp",
        "interface_types": ["analog"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "General-purpose dual op-amp, single-supply 3V-32V, rail-to-input",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 32.0,
            "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.0, "current_draw_max_ma": 2.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"gbw_hz": 1000000},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.10,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/lm358.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "channels": 2,
            "gain_bandwidth_mhz": 1.0,
            "slew_rate_vus": 0.3,
            "input_offset_mv": 7.0,
            "single_supply": True,
            "rail_to_rail_output": False,
        },
        "tags": ["opamp", "analog", "amplifier", "single-supply", "general-purpose"],
    },

    # --- Dual Comparator ---
    {
        "mpn": "LM393",
        "manufacturer": "Texas Instruments",
        "name": "LM393 Dual Comparator",
        "category": "comms",
        "sub_type": "comparator",
        "interface_types": ["analog"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Dual voltage comparator, open-collector output, single or dual supply",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 36.0,
            "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.8, "current_draw_max_ma": 2.5,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"response_time_us": 1.3},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.09,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/lm393-n.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "channels": 2,
            "response_time_us": 1.3,
            "open_collector_output": True,
            "single_supply": True,
        },
        "tags": ["comparator", "analog", "open-collector", "single-supply"],
    },

    # --- Digital Isolator ---
    {
        "mpn": "ADuM1201ARZ",
        "manufacturer": "Analog Devices",
        "name": "ADuM1201 Dual-Channel Digital Isolator",
        "category": "comms",
        "sub_type": "digital-isolator",
        "interface_types": ["GPIO", "UART"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Dual iCoupler digital isolator, 2.5kVrms, 100Mbps, bidirectional",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 5.5,
            "io_voltage_min": 2.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.5, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 105.0,
        },
        "timing_caps": {"max_data_rate_mbps": 100},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 2.40,
        "datasheet_url": "https://www.analog.com/media/en/technical-documentation/data-sheets/ADuM1201.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "channels": 2,
            "isolation_voltage_vrms": 2500,
            "max_data_rate_mbps": 100,
            "bidirectional": True,
            "propagation_delay_ns": 22,
        },
        "tags": ["isolator", "digital-isolator", "uart", "spi", "safety", "industrial"],
    },
]
