# SPDX-License-Identifier: AGPL-3.0-or-later
"""Display seed data — OLED, TFT, LED drivers, E-Ink."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    {
        "mpn": "SSD1306",
        "manufacturer": "Solomon Systech",
        "name": "SSD1306 OLED Display Controller",
        "category": "display",
        "sub_type": "oled",
        "interface_types": ["I2C", "SPI"],
        "package": "COG module",
        "mounting": "module",
        "pin_count": 4,
        "description": "128x64 monochrome OLED display controller",
        "electrical_ratings": {
            "vdd_min": 1.65, "vdd_max": 3.3,
            "io_voltage_min": 1.65, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 9.0, "current_draw_max_ma": 25.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 10000000, "spi_modes": [0, 3],
        },
        "known_i2c_addresses": ["0x3C", "0x3D"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x00", "value": "0xAE", "description": "Display OFF"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x00", "value": "0xD5", "description": "Set display clock div"},
                 {"reg_addr": "0x00", "value": "0x80", "description": "Clock div ratio"},
                 {"reg_addr": "0x00", "value": "0xA8", "description": "Set multiplex"},
                 {"reg_addr": "0x00", "value": "0x3F", "description": "Multiplex ratio 64"},
                 {"reg_addr": "0x00", "value": "0x8D", "description": "Charge pump"},
                 {"reg_addr": "0x00", "value": "0x14", "description": "Enable charge pump"},
             ]},
            {"phase": "enable", "order": 2,
             "writes": [{"reg_addr": "0x00", "value": "0xAF", "description": "Display ON"}]},
        ]},
        "unit_cost_usd": 5.00,
        "tags": ["display", "oled", "128x64"],
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "display_type": "oled",
            "controller_ic": "SSD1306",
            "resolution_x": 128,
            "resolution_y": 64,
            "color_depth": "mono",
            "colors": 2,
            "diagonal_inch": 0.96,
            "refresh_rate_hz": 60,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": False,
            "framebuffer_bytes": 1024,
            "builtin_ram_bytes": 1024,
            "sunlight_readable": False,
            "digit_count": None,
            "cascade_max": None,
            "dimming_levels": 256,
            "graphics_lib": ["u8g2", "adafruit-gfx", "adafruit-ssd1306"],
        },
    },
    {
        "mpn": "SH1106",
        "manufacturer": "Sino Wealth",
        "name": "SH1106 132x64 OLED Display Controller",
        "category": "display",
        "sub_type": "oled",
        "interface_types": ["I2C", "SPI"],
        "package": "COG module",
        "mounting": "module",
        "pin_count": 4,
        "description": "132x64 OLED/PLED segment/common driver (SSD1306-like)",
        "electrical_ratings": {
            "vdd_min": 1.65, "vdd_max": 3.3,
            "io_voltage_min": 1.65, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 8.0, "current_draw_max_ma": 20.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 4000000, "spi_modes": [0],
        },
        "known_i2c_addresses": ["0x3C", "0x3D"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0xAE", "value": "", "description": "Display OFF"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0xD5", "value": "0x80", "description": "Clock default"},
                 {"reg_addr": "0xA8", "value": "0x3F", "description": "Multiplex 64"},
                 {"reg_addr": "0x8D", "value": "0x14", "description": "Enable charge pump"},
             ]},
            {"phase": "enable", "order": 2,
             "writes": [{"reg_addr": "0xAF", "value": "", "description": "Display ON"}]},
        ]},
        "unit_cost_usd": 4.50,
        "tags": ["display", "oled", "132x64"],
        "datasheet_url": "https://www.velleman.eu/downloads/29/infosheets/sh1106_datasheet.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "display_type": "oled",
            "controller_ic": "SH1106",
            "resolution_x": 132,
            "resolution_y": 64,
            "color_depth": "mono",
            "colors": 2,
            "diagonal_inch": 1.3,
            "refresh_rate_hz": 60,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": False,
            "framebuffer_bytes": 1056,
            "builtin_ram_bytes": 1056,
            "sunlight_readable": False,
            "digit_count": None,
            "cascade_max": None,
            "dimming_levels": 256,
            "graphics_lib": ["u8g2", "adafruit-gfx"],
        },
    },
    {
        "mpn": "ST7735S",
        "manufacturer": "Sitronix",
        "name": "ST7735 128x160 TFT LCD Controller",
        "category": "display",
        "sub_type": "tft",
        "interface_types": ["SPI"],
        "package": "COG module",
        "mounting": "module",
        "pin_count": 8,
        "description": "262K color 128x160 TFT LCD driver with SPI interface",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 4.8,
            "io_voltage_min": 1.7, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 4.0, "current_draw_max_ma": 15.0,
            "temp_min_c": -30.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 15000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x01", "value": "", "description": "Software reset"}],
             "delay_after_ms": 150},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x11", "value": "", "description": "Sleep out"},
                 {"reg_addr": "0x3A", "value": "0x05", "description": "16-bit color RGB565"},
                 {"reg_addr": "0x36", "value": "0x08", "description": "BGR order"},
             ], "delay_after_ms": 150},
            {"phase": "enable", "order": 2,
             "writes": [{"reg_addr": "0x29", "value": "", "description": "Display ON"}]},
        ]},
        "unit_cost_usd": 5.00,
        "tags": ["display", "tft", "lcd", "color", "128x160"],
        "datasheet_url": "https://www.displayfuture.com/Display/datasheet/controller/ST7735.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "display_type": "tft",
            "controller_ic": "ST7735S",
            "resolution_x": 128,
            "resolution_y": 160,
            "color_depth": "rgb565",
            "colors": 65536,
            "diagonal_inch": 1.8,
            "refresh_rate_hz": 60,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": True,
            "framebuffer_bytes": 40960,
            "builtin_ram_bytes": 132480,
            "sunlight_readable": False,
            "digit_count": None,
            "cascade_max": None,
            "dimming_levels": None,
            "graphics_lib": ["adafruit-gfx", "adafruit-st7735", "tft_espi"],
        },
    },
    {
        "mpn": "ST7789V",
        "manufacturer": "Sitronix",
        "name": "ST7789 240x320 TFT LCD Controller",
        "category": "display",
        "sub_type": "ips",
        "interface_types": ["SPI"],
        "package": "COG module",
        "mounting": "module",
        "pin_count": 8,
        "description": "262K color 240x320 TFT LCD driver with SPI interface",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 4.8,
            "io_voltage_min": 1.7, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 5.0, "current_draw_max_ma": 20.0,
            "temp_min_c": -30.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 62500000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x01", "value": "", "description": "Software reset"}],
             "delay_after_ms": 150},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x11", "value": "", "description": "Sleep out"},
                 {"reg_addr": "0x3A", "value": "0x55", "description": "16-bit color RGB565"},
                 {"reg_addr": "0x21", "value": "", "description": "Display inversion ON (IPS)"},
             ], "delay_after_ms": 50},
            {"phase": "enable", "order": 2,
             "writes": [{"reg_addr": "0x29", "value": "", "description": "Display ON"}]},
        ]},
        "unit_cost_usd": 8.00,
        "tags": ["display", "tft", "lcd", "color", "240x320", "ips"],
        "datasheet_url": "https://www.rhydolabz.com/documents/33/ST7789.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "display_type": "ips",
            "controller_ic": "ST7789V",
            "resolution_x": 240,
            "resolution_y": 320,
            "color_depth": "rgb565",
            "colors": 65536,
            "diagonal_inch": 2.0,
            "refresh_rate_hz": 60,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": True,
            "framebuffer_bytes": 153600,
            "builtin_ram_bytes": 172800,
            "sunlight_readable": False,
            "digit_count": None,
            "cascade_max": None,
            "dimming_levels": None,
            "graphics_lib": ["adafruit-gfx", "adafruit-st7789", "tft_espi"],
        },
    },
    {
        "mpn": "ILI9341",
        "manufacturer": "Ilitek",
        "name": "ILI9341 240x320 TFT LCD Controller",
        "category": "display",
        "sub_type": "tft",
        "interface_types": ["SPI"],
        "package": "COG module",
        "mounting": "module",
        "pin_count": 9,
        "description": "262K color 240x320 TFT LCD single-chip driver",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 3.6,
            "io_voltage_min": 1.65, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 7.0, "current_draw_max_ma": 20.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 10000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x01", "value": "", "description": "Software reset"}],
             "delay_after_ms": 150},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x11", "value": "", "description": "Sleep out"},
                 {"reg_addr": "0x3A", "value": "0x55", "description": "16-bit color RGB565"},
                 {"reg_addr": "0x36", "value": "0x48", "description": "Memory access BGR"},
             ], "delay_after_ms": 150},
            {"phase": "enable", "order": 2,
             "writes": [{"reg_addr": "0x29", "value": "", "description": "Display ON"}]},
        ]},
        "unit_cost_usd": 7.00,
        "tags": ["display", "tft", "lcd", "color", "240x320"],
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "display_type": "tft",
            "controller_ic": "ILI9341",
            "resolution_x": 240,
            "resolution_y": 320,
            "color_depth": "rgb565",
            "colors": 65536,
            "diagonal_inch": 2.4,
            "refresh_rate_hz": 60,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": True,
            "framebuffer_bytes": 153600,
            "builtin_ram_bytes": 172800,
            "sunlight_readable": False,
            "digit_count": None,
            "cascade_max": None,
            "dimming_levels": None,
            "graphics_lib": ["adafruit-gfx", "adafruit-ili9341", "tft_espi", "lvgl"],
        },
    },
    {
        "mpn": "MAX7219",
        "manufacturer": "Maxim Integrated",
        "name": "MAX7219 8-Digit LED Display Driver",
        "category": "display",
        "sub_type": "led-driver",
        "interface_types": ["SPI"],
        "package": "DIP-24",
        "mounting": "tht",
        "pin_count": 24,
        "description": "8-digit LED display driver, SPI, cascade-able for LED matrices",
        "electrical_ratings": {
            "vdd_min": 4.0, "vdd_max": 5.5,
            "io_voltage_min": 3.5, "io_voltage_max": 5.5, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 330.0, "current_draw_max_ma": 500.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 10000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x0C", "value": "0x00", "description": "Shutdown mode"},
                 {"reg_addr": "0x0F", "value": "0x00", "description": "Test off"},
                 {"reg_addr": "0x09", "value": "0x00", "description": "No BCD decode"},
                 {"reg_addr": "0x0B", "value": "0x07", "description": "Scan 8 digits"},
                 {"reg_addr": "0x0A", "value": "0x07", "description": "Medium intensity"},
                 {"reg_addr": "0x0C", "value": "0x01", "description": "Normal operation"},
             ]},
        ]},
        "unit_cost_usd": 3.00,
        "tags": ["display", "led", "7-segment", "matrix"],
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "display_type": "led-matrix",
            "controller_ic": "MAX7219",
            "resolution_x": 8,
            "resolution_y": 8,
            "color_depth": "mono",
            "colors": 2,
            "diagonal_inch": None,
            "refresh_rate_hz": 800,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": False,
            "framebuffer_bytes": 8,
            "builtin_ram_bytes": 8,
            "sunlight_readable": True,
            "digit_count": 8,
            "cascade_max": 8,
            "dimming_levels": 16,
            "graphics_lib": ["md-max72xx", "ledcontrol"],
        },
    },
    {
        "mpn": "HT16K33",
        "manufacturer": "Holtek",
        "name": "HT16K33 LED Controller with I2C",
        "category": "display",
        "sub_type": "led-driver",
        "interface_types": ["I2C"],
        "package": "SOP-28",
        "mounting": "smd",
        "pin_count": 28,
        "description": "RAM mapping 16\u00d78 LED controller with keyscan, I2C interface",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_min": 3.0, "io_voltage_max": 5.5, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 150.0, "current_draw_max_ma": 150.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x70", "0x71", "0x72", "0x73", "0x74", "0x75", "0x76", "0x77"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x21", "value": "", "description": "Oscillator ON"},
                 {"reg_addr": "0xE0", "value": "", "description": "Max dimming"},
                 {"reg_addr": "0x81", "value": "", "description": "Display ON, no blink"},
             ]},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["display", "led", "7-segment", "matrix"],
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/ht16K33v110.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "display_type": "led-matrix",
            "controller_ic": "HT16K33",
            "resolution_x": 16,
            "resolution_y": 8,
            "color_depth": "mono",
            "colors": 2,
            "diagonal_inch": None,
            "refresh_rate_hz": 100,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": False,
            "framebuffer_bytes": 16,
            "builtin_ram_bytes": 16,
            "sunlight_readable": True,
            "digit_count": 8,
            "cascade_max": 8,
            "dimming_levels": 16,
            "graphics_lib": ["adafruit-ht16k33", "adafruit-led-backpack"],
        },
    },
    {
        "mpn": "TM1637",
        "manufacturer": "Titan Micro Electronics",
        "name": "TM1637 4-Digit 7-Segment Display Driver",
        "category": "display",
        "sub_type": "7seg",
        "interface_types": ["GPIO"],
        "package": "SOP-20",
        "mounting": "smd",
        "pin_count": 20,
        "description": "4-digit 7-segment LED driver with 2-wire serial interface (CLK+DIO)",
        "electrical_ratings": {
            "vdd_min": 3.3, "vdd_max": 5.5,
            "io_voltage_min": 3.3, "io_voltage_max": 5.5, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 80.0, "current_draw_max_ma": 130.0,
            "temp_min_c": -20.0, "temp_max_c": 80.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Send 0x40 (data cmd), 0xC0 (addr 0), 4 segment bytes, 0x88 (display ON)"},
        ]},
        "unit_cost_usd": 0.50,
        "tags": ["display", "7-segment", "4-digit", "led", "gpio"],
        "datasheet_url": "https://www.mcielectronics.cl/website_MCI/static/documents/Datasheet_TM1637.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "display_type": "7seg",
            "controller_ic": "TM1637",
            "resolution_x": None,
            "resolution_y": None,
            "color_depth": "mono",
            "colors": 2,
            "diagonal_inch": 0.56,
            "refresh_rate_hz": None,
            "partial_refresh": False,
            "full_refresh_ms": None,
            "touch_integrated": False,
            "backlight": False,
            "framebuffer_bytes": 4,
            "builtin_ram_bytes": 6,
            "sunlight_readable": True,
            "digit_count": 4,
            "cascade_max": None,
            "dimming_levels": 8,
            "graphics_lib": ["tm1637"],
        },
    },
    {
        "mpn": "UC8151C",
        "manufacturer": "Ultrachip",
        "name": "UC8151 2.13\" E-Ink Display Controller",
        "category": "display",
        "sub_type": "epaper",
        "interface_types": ["SPI"],
        "package": "COG module",
        "mounting": "module",
        "pin_count": 8,
        "description": "2.13\" 250x122 e-paper display driver, partial refresh, SPI",
        "electrical_ratings": {
            "vdd_min": 2.3, "vdd_max": 3.6,
            "io_voltage_min": 1.8, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 3.0, "current_draw_max_ma": 20.0,
            "temp_min_c": 0.0, "temp_max_c": 50.0,
        },
        "timing_caps": {"spi_max_clock_hz": 2000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10, "description": "HW reset via RST pin"},
            {"phase": "configure", "order": 1,
             "description": "Send init sequence: booster, LUT, resolution"},
            {"phase": "enable", "order": 2,
             "description": "Transfer frame buffer, trigger full/partial refresh"},
        ]},
        "unit_cost_usd": 12.00,
        "tags": ["display", "e-ink", "e-paper", "low-power", "2.13inch"],
        "datasheet_url": "https://www.waveshare.com/w/upload/5/5d/2.13inch_e-Paper_HAT_V4_Specification.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "display_type": "epaper",
            "controller_ic": "UC8151C",
            "resolution_x": 250,
            "resolution_y": 122,
            "color_depth": "mono",
            "colors": 2,
            "diagonal_inch": 2.13,
            "refresh_rate_hz": None,
            "partial_refresh": True,
            "full_refresh_ms": 2000,
            "touch_integrated": False,
            "backlight": False,
            "framebuffer_bytes": 3840,
            "builtin_ram_bytes": 5120,
            "sunlight_readable": True,
            "digit_count": None,
            "cascade_max": None,
            "dimming_levels": None,
            "graphics_lib": ["gooddisplay-epd", "adafruit-epd", "waveshare-epd"],
        },
    },
]
