# SPDX-License-Identifier: AGPL-3.0-or-later
"""MCU seed data."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    {
        "mpn": "ESP32-WROOM-32",
        "manufacturer": "Espressif",
        "name": "ESP32 Wi-Fi+BT Module",
        "category": "mcu",
        "sub_type": "soc-wifi",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM", "I2S", "CAN", "SDIO"],
        "package": "SMD module (18×25.5mm)",
        "mounting": "module",
        "pin_count": 38,
        "description": "Dual-core Xtensa LX6 MCU with Wi-Fi and Bluetooth, 4MB flash",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 3.6,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "logic_high_min": 2.475, "logic_low_max": 0.825,
            "current_draw_typical_ma": 80.0, "current_draw_max_ma": 500.0,
            "abs_max_voltage": 3.6, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 40.0,
            "sleep_current_ua": 10.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 80000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 5000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 100, "description": "Power-on reset"},
            {"phase": "configure", "order": 1, "description": "Init I2C/SPI via SDK"},
        ]},
        "unit_cost_usd": 3.50,
        "datasheet_url": "https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf",
        "status": "active",
        "library_support": ["esp-idf", "arduino", "micropython", "circuitpython"],
        "capabilities": {
            "cpu_arch": "xtensa-lx6",
            "cpu_cores": 2,
            "cpu_mhz": 240,
            "fpu": False,
            "flash_kb": 4096,
            "ram_kb": 520,
            "gpio_count": 34,
            "adc_channels": 18,
            "adc_resolution_bits": 12,
            "dac_channels": 2,
            "pwm_channels": 16,
            "i2c_count": 2,
            "spi_count": 3,
            "uart_count": 3,
            "i2s_count": 2,
            "can_count": 1,
            "usb": "none",
            "wifi": "802.11bgn",
            "bluetooth": "classic+ble4.2",
            "secure_boot": True,
            "flash_encryption": True,
            "crypto_hw": ["aes", "sha", "rsa"],
            "debug_interface": "jtag",
            "rtc_builtin": True,
            "ext_crystal_required": False,
            "ext_flash_required": False,
            "sdk": ["esp-idf", "arduino", "micropython", "circuitpython"],
        },
        "tags": ["wifi", "bluetooth", "dual-core", "esp32"],
    },
    {
        "mpn": "ESP32-S3-WROOM-1",
        "manufacturer": "Espressif",
        "name": "ESP32-S3 Wi-Fi+BT Module with AI Accelerator",
        "category": "mcu",
        "sub_type": "soc-wifi",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM", "USB", "I2S", "SDIO"],
        "package": "SMD module (18×25.5mm)",
        "mounting": "module",
        "pin_count": 41,
        "description": "Dual-core Xtensa LX7 240MHz, Wi-Fi+BLE5, USB OTG, 8MB flash, vector instructions",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 3.6,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 100.0, "current_draw_max_ma": 500.0,
            "abs_max_voltage": 3.6, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 40.0,
            "sleep_current_ua": 7.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 800000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 80000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 5000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 100, "description": "Power-on reset"},
            {"phase": "configure", "order": 1, "description": "Init peripherals via ESP-IDF SDK"},
        ]},
        "unit_cost_usd": 4.50,
        "datasheet_url": "https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf",
        "status": "active",
        "library_support": ["esp-idf", "arduino", "micropython", "circuitpython"],
        "capabilities": {
            "cpu_arch": "xtensa-lx7",
            "cpu_cores": 2,
            "cpu_mhz": 240,
            "fpu": True,
            "flash_kb": 8192,
            "ram_kb": 512,
            "gpio_count": 45,
            "adc_channels": 20,
            "adc_resolution_bits": 12,
            "dac_channels": 0,
            "pwm_channels": 8,
            "i2c_count": 2,
            "spi_count": 3,
            "uart_count": 3,
            "i2s_count": 2,
            "can_count": 1,
            "usb": "otg",
            "wifi": "802.11bgn",
            "bluetooth": "ble5.0",
            "secure_boot": True,
            "flash_encryption": True,
            "crypto_hw": ["aes", "sha", "rsa"],
            "debug_interface": "jtag",
            "rtc_builtin": True,
            "ext_crystal_required": False,
            "ext_flash_required": False,
            "sdk": ["esp-idf", "arduino", "micropython", "circuitpython"],
        },
        "tags": ["wifi", "bluetooth", "dual-core", "esp32", "esp32-s3", "usb", "ai", "vector"],
    },
    {
        "mpn": "ESP32-C3-MINI-1",
        "manufacturer": "Espressif",
        "name": "ESP32-C3 RISC-V Wi-Fi+BLE Module",
        "category": "mcu",
        "sub_type": "soc-wifi",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM"],
        "package": "SMD module (13×16.6mm)",
        "mounting": "module",
        "pin_count": 53,
        "description": "Single-core RISC-V 160MHz, Wi-Fi+BLE5, 4MB flash, ultra-low cost",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 3.6,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 60.0, "current_draw_max_ma": 350.0,
            "abs_max_voltage": 3.6, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 40.0,
            "sleep_current_ua": 5.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 60000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 5000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 100, "description": "Power-on reset"},
            {"phase": "configure", "order": 1, "description": "Init peripherals via ESP-IDF SDK"},
        ]},
        "unit_cost_usd": 1.80,
        "datasheet_url": "https://www.espressif.com/sites/default/files/documentation/esp32-c3-mini-1_datasheet_en.pdf",
        "status": "active",
        "library_support": ["esp-idf", "arduino", "micropython", "circuitpython"],
        "capabilities": {
            "cpu_arch": "risc-v",
            "cpu_cores": 1,
            "cpu_mhz": 160,
            "fpu": False,
            "flash_kb": 4096,
            "ram_kb": 400,
            "gpio_count": 22,
            "adc_channels": 6,
            "adc_resolution_bits": 12,
            "dac_channels": 0,
            "pwm_channels": 6,
            "i2c_count": 1,
            "spi_count": 2,
            "uart_count": 2,
            "i2s_count": 1,
            "can_count": 0,
            "usb": "fs",
            "wifi": "802.11bgn",
            "bluetooth": "ble5.0",
            "secure_boot": True,
            "flash_encryption": True,
            "crypto_hw": ["aes", "sha"],
            "debug_interface": "jtag",
            "rtc_builtin": True,
            "ext_crystal_required": False,
            "ext_flash_required": False,
            "sdk": ["esp-idf", "arduino", "micropython", "circuitpython"],
        },
        "tags": ["wifi", "bluetooth", "risc-v", "esp32", "esp32-c3", "low-cost"],
    },
    {
        "mpn": "STM32F103C8T6",
        "manufacturer": "STMicroelectronics",
        "name": "STM32F103 Cortex-M3 MCU",
        "category": "mcu",
        "sub_type": "mcu-arm",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM", "CAN", "USB"],
        "package": "LQFP-48",
        "mounting": "smd",
        "pin_count": 48,
        "description": "ARM Cortex-M3 72MHz MCU, 64KB flash, 20KB SRAM",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 3.6,
            "io_voltage_min": 2.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "logic_high_min": 2.0, "logic_low_max": 0.8,
            "current_draw_typical_ma": 36.0, "current_draw_max_ma": 150.0,
            "abs_max_voltage": 4.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 25.0,
            "sleep_current_ua": 2.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 18000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 4500000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10},
            {"phase": "configure", "order": 1, "description": "Enable GPIO clocks, configure I2C/SPI"},
        ]},
        "unit_cost_usd": 2.20,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/stm32f103c8.pdf",
        "status": "active",
        "library_support": ["stm32-hal", "arduino", "micropython", "zephyr", "mbed"],
        "capabilities": {
            "cpu_arch": "cortex-m3",
            "cpu_cores": 1,
            "cpu_mhz": 72,
            "fpu": False,
            "flash_kb": 64,
            "ram_kb": 20,
            "gpio_count": 37,
            "adc_channels": 10,
            "adc_resolution_bits": 12,
            "dac_channels": 0,
            "pwm_channels": 15,
            "i2c_count": 2,
            "spi_count": 2,
            "uart_count": 3,
            "i2s_count": 0,
            "can_count": 1,
            "usb": "fs",
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": False,
            "flash_encryption": False,
            "crypto_hw": [],
            "debug_interface": "swd",
            "rtc_builtin": True,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["stm32-hal", "arduino", "mbed", "zephyr"],
        },
        "tags": ["arm", "cortex-m3", "stm32", "5v-tolerant"],
    },
    {
        "mpn": "STM32F411CEU6",
        "manufacturer": "STMicroelectronics",
        "name": "STM32F411 Cortex-M4 MCU (Black Pill)",
        "category": "mcu",
        "sub_type": "mcu-arm",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM", "USB", "I2S"],
        "package": "UFQFPN-48",
        "mounting": "smd",
        "pin_count": 48,
        "description": "ARM Cortex-M4F 100MHz, 512KB flash, 128KB SRAM, USB FS, FPU",
        "electrical_ratings": {
            "vdd_min": 1.7, "vdd_max": 3.6,
            "io_voltage_min": 1.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 50.0, "current_draw_max_ma": 200.0,
            "abs_max_voltage": 4.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 25.0,
            "sleep_current_ua": 1.8,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 50000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 12500000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10},
            {"phase": "configure", "order": 1, "description": "Enable clocks, init HAL peripherals"},
        ]},
        "unit_cost_usd": 3.50,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/stm32f411ce.pdf",
        "status": "active",
        "library_support": ["stm32-hal", "arduino", "micropython", "zephyr", "mbed"],
        "capabilities": {
            "cpu_arch": "cortex-m4f",
            "cpu_cores": 1,
            "cpu_mhz": 100,
            "fpu": True,
            "flash_kb": 512,
            "ram_kb": 128,
            "gpio_count": 36,
            "adc_channels": 16,
            "adc_resolution_bits": 12,
            "dac_channels": 0,
            "pwm_channels": 11,
            "i2c_count": 3,
            "spi_count": 5,
            "uart_count": 3,
            "i2s_count": 5,
            "can_count": 0,
            "usb": "fs",
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": False,
            "flash_encryption": False,
            "crypto_hw": [],
            "debug_interface": "swd",
            "rtc_builtin": True,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["stm32-hal", "arduino", "micropython", "mbed", "zephyr"],
        },
        "tags": ["arm", "cortex-m4", "stm32", "5v-tolerant", "black-pill", "usb", "fpu"],
    },
    {
        "mpn": "RP2040",
        "manufacturer": "Raspberry Pi Ltd",
        "name": "RP2040 Dual-Core ARM Cortex-M0+ MCU",
        "category": "mcu",
        "sub_type": "mcu-arm",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM", "USB"],
        "package": "QFN-56",
        "mounting": "smd",
        "pin_count": 56,
        "description": "Dual-core Cortex-M0+ at 133 MHz, 264KB SRAM, flexible PIO state machines, no internal flash",
        "electrical_ratings": {
            "vdd_min": 1.8, "vdd_max": 3.6,
            "io_voltage_min": 1.8, "io_voltage_max": 3.3, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "logic_high_min": 2.0, "logic_low_max": 0.8,
            "current_draw_typical_ma": 25.0, "current_draw_max_ma": 120.0,
            "abs_max_voltage": 3.63, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 12.0,
            "sleep_current_ua": 180.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"],
            "spi_max_clock_hz": 62500000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 31250000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10, "description": "Power-on reset"},
            {"phase": "configure", "order": 1, "description": "Init I2C/SPI via SDK, configure GPIO"},
        ]},
        "unit_cost_usd": 1.00,
        "datasheet_url": "https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf",
        "status": "active",
        "library_support": ["pico-sdk", "arduino", "micropython", "circuitpython"],
        "capabilities": {
            "cpu_arch": "cortex-m0+",
            "cpu_cores": 2,
            "cpu_mhz": 133,
            "fpu": False,
            "flash_kb": 0,
            "ram_kb": 264,
            "gpio_count": 30,
            "adc_channels": 4,
            "adc_resolution_bits": 12,
            "dac_channels": 0,
            "pwm_channels": 16,
            "i2c_count": 2,
            "spi_count": 2,
            "uart_count": 2,
            "i2s_count": 0,
            "can_count": 0,
            "usb": "fs",
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": False,
            "flash_encryption": False,
            "crypto_hw": [],
            "debug_interface": "swd",
            "rtc_builtin": True,
            "ext_crystal_required": True,
            "ext_flash_required": True,
            "pio_state_machines": 8,
            "sdk": ["pico-sdk", "arduino", "micropython", "circuitpython"],
        },
        "tags": ["rp2040", "pico", "pio", "dual-core", "cortex-m0"],
    },
    {
        "mpn": "nRF52840",
        "manufacturer": "Nordic Semiconductor",
        "name": "nRF52840 BLE 5.3 + Zigbee + Thread SoC",
        "category": "mcu",
        "sub_type": "soc-ble",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM", "USB", "BLE"],
        "package": "AQFN-94",
        "mounting": "smd",
        "pin_count": 94,
        "description": "Arm Cortex-M4F 64 MHz, BLE 5.3, IEEE 802.15.4, USB, 1 MB flash, 256 KB RAM",
        "electrical_ratings": {
            "vdd_min": 1.7, "vdd_max": 3.6,
            "io_voltage_min": 1.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "logic_high_min": 0.7, "logic_low_max": 0.3,
            "current_draw_typical_ma": 4.8, "current_draw_max_ma": 22.0,
            "abs_max_voltage": 3.9, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 15.0,
            "sleep_current_ua": 1.5,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 32000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 1000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10},
            {"phase": "configure", "order": 1, "description": "Enable TWI/SPI peripherals, BLE stack init"},
        ]},
        "unit_cost_usd": 4.20,
        "datasheet_url": "https://infocenter.nordicsemi.com/pdf/nRF52840_PS_v1.7.pdf",
        "status": "active",
        "library_support": ["nrf-connect-sdk", "zephyr", "arduino", "circuitpython", "micropython"],
        "capabilities": {
            "cpu_arch": "cortex-m4f",
            "cpu_cores": 1,
            "cpu_mhz": 64,
            "fpu": True,
            "flash_kb": 1024,
            "ram_kb": 256,
            "gpio_count": 48,
            "adc_channels": 8,
            "adc_resolution_bits": 12,
            "dac_channels": 0,
            "pwm_channels": 16,
            "i2c_count": 2,
            "spi_count": 3,
            "uart_count": 2,
            "i2s_count": 1,
            "can_count": 0,
            "usb": "fs",
            "wifi": "none",
            "bluetooth": "ble5.3",
            "zigbee": True,
            "thread": True,
            "matter": True,
            "secure_boot": True,
            "flash_encryption": False,
            "crypto_hw": ["aes", "ecb", "ccm"],
            "debug_interface": "swd",
            "rtc_builtin": True,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["nrf-connect-sdk", "zephyr", "arduino", "circuitpython"],
        },
        "tags": ["ble", "bluetooth", "zigbee", "thread", "nrf52", "cortex-m4", "low-power"],
    },
    {
        "mpn": "ATmega328P",
        "manufacturer": "Microchip",
        "name": "ATmega328P 8-bit AVR MCU",
        "category": "mcu",
        "sub_type": "mcu-avr",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM"],
        "package": "DIP-28",
        "mounting": "tht",
        "pin_count": 28,
        "description": "8-bit AVR 20MHz, 32KB flash, 2KB SRAM — Arduino Uno core",
        "electrical_ratings": {
            "vdd_min": 1.8, "vdd_max": 5.5,
            "io_voltage_min": 1.8, "io_voltage_max": 5.5, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 12.0, "current_draw_max_ma": 60.0,
            "abs_max_voltage": 6.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 40.0,
            "sleep_current_ua": 0.75,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 8000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 1000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 20, "description": "Power-on reset"},
            {"phase": "configure", "order": 1, "description": "Set fuses, init Wire/SPI"},
        ]},
        "unit_cost_usd": 2.00,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/ATmega328P-DS40002061B.pdf",
        "status": "active",
        "library_support": ["arduino", "avr-gcc"],
        "capabilities": {
            "cpu_arch": "avr",
            "cpu_cores": 1,
            "cpu_mhz": 20,
            "fpu": False,
            "flash_kb": 32,
            "ram_kb": 2,
            "gpio_count": 23,
            "adc_channels": 6,
            "adc_resolution_bits": 10,
            "dac_channels": 0,
            "pwm_channels": 6,
            "i2c_count": 1,
            "spi_count": 1,
            "uart_count": 1,
            "i2s_count": 0,
            "can_count": 0,
            "usb": "none",
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": False,
            "flash_encryption": False,
            "crypto_hw": [],
            "debug_interface": "isp",
            "rtc_builtin": False,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["arduino", "avr-gcc"],
        },
        "tags": ["avr", "arduino", "8-bit", "5v-tolerant", "atmega"],
    },
    {
        "mpn": "ATmega2560",
        "manufacturer": "Microchip",
        "name": "ATmega2560 8-bit AVR MCU (Arduino Mega core)",
        "category": "mcu",
        "sub_type": "mcu-avr",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "PWM"],
        "package": "TQFP-100",
        "mounting": "smd",
        "pin_count": 100,
        "description": "8-bit AVR 16MHz, 256KB flash, 8KB SRAM — Arduino Mega core",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_min": 4.5, "io_voltage_max": 5.5, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 30.0, "current_draw_max_ma": 200.0,
            "abs_max_voltage": 6.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 40.0,
            "sleep_current_ua": 1.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 8000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 1000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 20, "description": "Power-on reset"},
            {"phase": "configure", "order": 1, "description": "Set fuses, init Wire/SPI"},
        ]},
        "unit_cost_usd": 8.50,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/ATmega2560-Datasheet.pdf",
        "status": "active",
        "library_support": ["arduino", "avr-gcc"],
        "capabilities": {
            "cpu_arch": "avr",
            "cpu_cores": 1,
            "cpu_mhz": 16,
            "fpu": False,
            "flash_kb": 256,
            "ram_kb": 8,
            "gpio_count": 86,
            "adc_channels": 16,
            "adc_resolution_bits": 10,
            "dac_channels": 0,
            "pwm_channels": 15,
            "i2c_count": 1,
            "spi_count": 1,
            "uart_count": 4,
            "i2s_count": 0,
            "can_count": 0,
            "usb": "none",
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": False,
            "flash_encryption": False,
            "crypto_hw": [],
            "debug_interface": "isp",
            "rtc_builtin": False,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["arduino", "avr-gcc"],
        },
        "tags": ["avr", "arduino", "8-bit", "5v-tolerant", "atmega", "mega"],
    },
    {
        "mpn": "STM32G431CBU6",
        "manufacturer": "STMicroelectronics",
        "name": "STM32G431 Cortex-M4 MCU with FDCAN",
        "category": "mcu",
        "sub_type": "mcu-stm32",
        "interface_types": ["I2C", "SPI", "UART", "CAN", "ADC", "DAC", "GPIO", "PWM"],
        "package": "UFQFPN-48",
        "mounting": "smd",
        "pin_count": 48,
        "description": "STM32G4 Cortex-M4 170MHz, 128KB flash, 32KB SRAM, FDCAN",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 3.6,
            "io_voltage_min": 1.71, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 24.0, "current_draw_max_ma": 100.0,
            "abs_max_voltage": 4.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 25.0,
            "sleep_current_ua": 1.5,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"],
            "spi_max_clock_hz": 42500000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 10000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10},
            {"phase": "configure", "order": 1, "description": "Enable RCC clocks, configure HAL peripherals"},
        ]},
        "unit_cost_usd": 3.50,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/stm32g431cb.pdf",
        "status": "active",
        "library_support": ["stm32-hal", "arduino", "zephyr", "mbed"],
        "capabilities": {
            "cpu_arch": "arm-m4f",
            "cpu_cores": 1,
            "cpu_mhz": 170,
            "fpu": True,
            "flash_kb": 128,
            "ram_kb": 32,
            "gpio_count": 38,
            "adc_channels": 12,
            "adc_resolution_bits": 12,
            "dac_channels": 2,
            "pwm_channels": 16,
            "i2c_count": 3,
            "spi_count": 3,
            "uart_count": 3,
            "i2s_count": 1,
            "can_count": 1,
            "usb": "fs",
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": False,
            "flash_encryption": False,
            "crypto_hw": ["aes"],
            "debug_interface": "swd",
            "rtc_builtin": True,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["stm32-hal", "arduino", "zephyr", "mbed"],
        },
        "tags": ["stm32", "g4", "cortex-m4", "fdcan", "motor-control"],
    },
    {
        "mpn": "STM32H743VIT6",
        "manufacturer": "STMicroelectronics",
        "name": "STM32H743 Cortex-M7 MCU",
        "category": "mcu",
        "sub_type": "mcu-arm",
        "interface_types": ["I2C", "SPI", "UART", "GPIO", "ADC", "DAC", "PWM", "CAN", "USB", "SDMMC", "I2S", "QSPI"],
        "package": "LQFP-100",
        "mounting": "smd",
        "pin_count": 100,
        "description": "ARM Cortex-M7 480MHz MCU, 2MB flash, 1MB SRAM, FPU+DSP, Ethernet, USB HS",
        "electrical_ratings": {
            "vdd_min": 1.62, "vdd_max": 3.6,
            "io_voltage_min": 1.62, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "logic_high_min": 2.0, "logic_low_max": 0.8,
            "current_draw_typical_ma": 100.0, "current_draw_max_ma": 550.0,
            "abs_max_voltage": 4.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
            "drive_strength_ma": 25.0,
            "sleep_current_ua": 2.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"],
            "spi_max_clock_hz": 150000000, "spi_modes": [0, 1, 2, 3],
            "uart_max_baud": 15000000,
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 10},
            {"phase": "configure", "order": 1, "description": "Enable RCC clocks, configure HAL peripherals"},
        ]},
        "unit_cost_usd": 12.50,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/stm32h743vi.pdf",
        "status": "active",
        "library_support": ["stm32-hal", "zephyr", "mbed", "freertos"],
        "capabilities": {
            "cpu_arch": "cortex-m7",
            "cpu_cores": 1,
            "cpu_mhz": 480,
            "fpu": True,
            "dsp": True,
            "flash_kb": 2048,
            "ram_kb": 1024,
            "gpio_count": 114,
            "adc_channels": 20,
            "adc_resolution_bits": 16,
            "dac_channels": 2,
            "pwm_channels": 32,
            "i2c_count": 4,
            "spi_count": 6,
            "uart_count": 4,
            "i2s_count": 3,
            "can_count": 2,
            "usb": "hs",
            "ethernet": True,
            "wifi": "none",
            "bluetooth": "none",
            "secure_boot": True,
            "flash_encryption": True,
            "crypto_hw": ["aes", "sha", "rng", "hash"],
            "debug_interface": "swd",
            "rtc_builtin": True,
            "ext_crystal_required": True,
            "ext_flash_required": False,
            "sdk": ["stm32-hal", "zephyr", "mbed", "freertos"],
        },
        "tags": ["arm", "cortex-m7", "stm32", "stm32h7", "high-performance", "fpu", "dsp", "ethernet"],
    },
]
