# SPDX-License-Identifier: AGPL-3.0-or-later
"""Memory seed data — NOR Flash, EEPROM, SRAM."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    {
        "mpn": "W25Q128JV",
        "manufacturer": "Winbond",
        "name": "W25Q128 128Mbit SPI NOR Flash",
        "category": "memory",
        "sub_type": "nor-flash",
        "interface_types": ["SPI"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "128Mbit (16MB) SPI NOR Flash memory",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 3.6,
            "io_voltage_min": 1.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 4.0, "current_draw_max_ma": 25.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 133000000, "spi_modes": [0, 3]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x9F", "expected_value": "0xEF4018", "description": "JEDEC ID"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x06", "value": "", "description": "Write enable"},
                 {"reg_addr": "0x01", "value": "0x00", "description": "Clear block protect"},
             ], "delay_after_ms": 15},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["flash", "memory", "spi", "nor", "storage"],
        "datasheet_url": "https://www.winbond.com/resource-files/w25q128jv%20revf%2003272018%20plus.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf", "zephyr"],
        "capabilities": {
            "memory_type": "nor-flash",
            "capacity_bytes": 16777216,
            "page_size_bytes": 256,
            "sector_size_bytes": 4096,
            "write_endurance_cycles": 100000,
            "data_retention_years": 20,
            "byte_addressable": False,
            "quad_spi": True,
            "xip_support": True,
            "ecc_builtin": False,
        },
    },
    {
        "mpn": "AT24C256",
        "manufacturer": "Microchip",
        "name": "AT24C256 256Kbit I2C EEPROM",
        "category": "memory",
        "sub_type": "eeprom",
        "interface_types": ["I2C"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "256Kbit (32KB) I2C serial EEPROM",
        "electrical_ratings": {
            "vdd_min": 1.7, "vdd_max": 5.5,
            "io_voltage_min": 1.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.0, "current_draw_max_ma": 3.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"]},
        "known_i2c_addresses": ["0x50", "0x51", "0x52", "0x53"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x0000", "description": "Read first byte to verify comms"}]},
        ]},
        "unit_cost_usd": 0.80,
        "tags": ["eeprom", "memory", "i2c", "storage"],
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/AT24C256C-I2C-Compatible-Two-Wire-Serial-EEPROM-20006270A.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf", "zephyr"],
        "capabilities": {
            "memory_type": "eeprom",
            "capacity_bytes": 32768,
            "page_size_bytes": 64,
            "sector_size_bytes": None,
            "write_endurance_cycles": 1000000,
            "data_retention_years": 100,
            "byte_addressable": True,
            "quad_spi": False,
            "xip_support": False,
            "ecc_builtin": False,
        },
    },
    {
        "mpn": "AT24C32",
        "manufacturer": "Microchip",
        "name": "AT24C32 32Kbit I2C EEPROM",
        "category": "memory",
        "sub_type": "eeprom",
        "interface_types": ["I2C"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "32Kbit (4KB) I2C serial EEPROM",
        "electrical_ratings": {
            "vdd_min": 1.7, "vdd_max": 5.5,
            "io_voltage_min": 1.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.0, "current_draw_max_ma": 3.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x50", "0x51", "0x52", "0x53", "0x54", "0x55", "0x56", "0x57"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x0000", "description": "Read first byte"}]},
        ]},
        "unit_cost_usd": 0.50,
        "tags": ["eeprom", "memory", "i2c", "storage"],
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/doc0336.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "memory_type": "eeprom",
            "capacity_bytes": 4096,
            "page_size_bytes": 32,
            "sector_size_bytes": None,
            "write_endurance_cycles": 1000000,
            "data_retention_years": 100,
            "byte_addressable": True,
            "quad_spi": False,
            "xip_support": False,
            "ecc_builtin": False,
        },
    },
    {
        "mpn": "23LC1024",
        "manufacturer": "Microchip",
        "name": "23LC1024 1Mbit SPI SRAM",
        "category": "memory",
        "sub_type": "sram",
        "interface_types": ["SPI"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "1Mbit (128KB) SPI serial SRAM — volatile, instant write",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 3.6,
            "io_voltage_min": 2.5, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 3.0, "current_draw_max_ma": 5.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"spi_max_clock_hz": 20000000, "spi_modes": [0, 3]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [{"reg_addr": "0x01", "value": "0x00", "description": "Byte mode"}]},
        ]},
        "unit_cost_usd": 2.00,
        "tags": ["sram", "memory", "spi", "volatile"],
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/20005142C.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "memory_type": "sram",
            "capacity_bytes": 131072,
            "page_size_bytes": 32,
            "sector_size_bytes": None,
            "write_endurance_cycles": None,
            "data_retention_years": None,
            "byte_addressable": True,
            "quad_spi": False,
            "xip_support": False,
            "ecc_builtin": False,
        },
    },
]
