# SPDX-License-Identifier: AGPL-3.0-or-later
"""Other/misc seed data — RTC, GPIO expanders, DAC, level shifters, shift registers."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    # -------------------------------------------------------------------------
    # Real-Time Clocks
    # -------------------------------------------------------------------------
    {
        "mpn": "DS3231SN",
        "manufacturer": "Maxim Integrated",
        "name": "DS3231 High-Accuracy RTC",
        "category": "other",
        "sub_type": "rtc",
        "interface_types": ["I2C"],
        "package": "SOIC-16",
        "mounting": "smd",
        "pin_count": 16,
        "description": "Extremely accurate I2C RTC with integrated TCXO and crystal, \u00b12ppm accuracy",
        "electrical_ratings": {
            "vdd_min": 2.3, "vdd_max": 5.5,
            "io_voltage_min": 2.3, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.2, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x68"],
        "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x0F", "description": "Read status register, clear OSF flag if set"}]},
            {"phase": "configure", "order": 1,
             "writes": [{"reg_addr": "0x0E", "value": "0x00", "description": "Disable SQW output, enable oscillator"}]},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["rtc", "clock", "i2c", "tcxo", "battery-backup"],
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/DS3231.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf", "zephyr"],
        "capabilities": {
            "accuracy_ppm": 2,
            "tcxo_builtin": True,
            "crystal_required": False,
            "battery_backup": True,
            "alarm_count": 2,
            "sqw_output": True,
            "temp_sensor_builtin": True,
            "sram_bytes": 0,
        },
    },
    {
        "mpn": "PCF8563T",
        "manufacturer": "NXP",
        "name": "PCF8563 Low-Power RTC",
        "category": "other",
        "sub_type": "rtc",
        "interface_types": ["I2C"],
        "package": "SO-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Low-power RTC with I2C, alarm, timer, programmable clock output",
        "electrical_ratings": {
            "vdd_min": 1.0, "vdd_max": 5.5,
            "io_voltage_min": 1.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.0004, "current_draw_max_ma": 0.01,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x51"],
        "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x00", "value": "0x00", "description": "Clear Control_status_1 (start RTC)"},
                 {"reg_addr": "0x01", "value": "0x00", "description": "Clear Control_status_2"},
             ], "delay_after_ms": 1},
        ]},
        "unit_cost_usd": 0.60,
        "tags": ["rtc", "clock", "i2c", "low-power", "battery-backup"],
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "accuracy_ppm": 20,
            "tcxo_builtin": False,
            "crystal_required": True,
            "battery_backup": True,
            "alarm_count": 1,
            "sqw_output": True,
            "temp_sensor_builtin": False,
            "sram_bytes": 0,
        },
    },
    # -------------------------------------------------------------------------
    # GPIO Expanders
    # -------------------------------------------------------------------------
    {
        "mpn": "MCP23017",
        "manufacturer": "Microchip",
        "name": "MCP23017 16-Bit I2C GPIO Expander",
        "category": "other",
        "sub_type": "gpio-expander",
        "interface_types": ["I2C"],
        "package": "DIP-28",
        "mounting": "tht",
        "pin_count": 28,
        "description": "16-bit bidirectional I/O expander with I2C interface, configurable interrupt output",
        "electrical_ratings": {
            "vdd_min": 1.8, "vdd_max": 5.5,
            "io_voltage_min": 1.8, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.0, "current_draw_max_ma": 8.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 1700000, "i2c_modes": ["standard", "fast", "fast_plus"]},
        "known_i2c_addresses": [
            "0x20", "0x21", "0x22", "0x23", "0x24", "0x25", "0x26", "0x27",
        ],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x00", "value": "0xFF", "description": "IODIRA: all port A pins as input (default)"},
                 {"reg_addr": "0x01", "value": "0xFF", "description": "IODIRB: all port B pins as input (default)"},
             ]},
        ]},
        "unit_cost_usd": 1.20,
        "tags": ["gpio", "expander", "i2c", "16-bit", "interrupt"],
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf", "zephyr"],
        "capabilities": {
            "gpio_count": 16,
            "interrupt_output": True,
            "pull_up_builtin": True,
            "open_drain": False,
            "push_pull": True,
            "drive_strength_ma": 25,
        },
    },
    {
        "mpn": "PCF8574T",
        "manufacturer": "NXP",
        "name": "PCF8574 8-Bit I2C GPIO Expander",
        "category": "other",
        "sub_type": "gpio-expander",
        "interface_types": ["I2C"],
        "package": "SO-16",
        "mounting": "smd",
        "pin_count": 16,
        "description": "8-bit quasi-bidirectional I/O expander with I2C, common for HD44780 LCD adapters",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 6.0,
            "io_voltage_min": 2.5, "io_voltage_max": 6.0, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.1, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x20", "0x21", "0x22", "0x23", "0x24", "0x25", "0x26", "0x27"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [{"reg_addr": "none", "value": "0xFF", "description": "Write 0xFF to set all pins high (input mode)"}]},
        ]},
        "unit_cost_usd": 0.40,
        "tags": ["gpio", "expander", "i2c", "8-bit", "lcd"],
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/PCF8574_PCF8574A.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "gpio_count": 8,
            "interrupt_output": True,
            "pull_up_builtin": True,
            "open_drain": True,
            "push_pull": False,
            "drive_strength_ma": 20,
        },
    },
    # -------------------------------------------------------------------------
    # DAC
    # -------------------------------------------------------------------------
    {
        "mpn": "MCP4725A0T-E/OT",
        "manufacturer": "Microchip",
        "name": "MCP4725 12-Bit DAC with EEPROM",
        "category": "other",
        "sub_type": "dac",
        "interface_types": ["I2C"],
        "package": "SOT-23-6",
        "mounting": "smd",
        "pin_count": 6,
        "description": "Single-channel 12-bit DAC with I2C interface and on-board non-volatile EEPROM",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 5.5,
            "io_voltage_min": 2.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.21, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x60", "0x61"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Write fast-mode command: 2-byte write with D11..D0 to set output voltage"},
        ]},
        "unit_cost_usd": 0.90,
        "tags": ["dac", "analog", "i2c", "12-bit", "eeprom"],
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/22039d.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "dac_channels": 1,
            "resolution_bits": 12,
            "output_buffer": True,
            "eeprom_storage": True,
        },
    },
    # -------------------------------------------------------------------------
    # Level Shifters / Logic Translation
    # -------------------------------------------------------------------------
    {
        "mpn": "TXS0108EPWR",
        "manufacturer": "Texas Instruments",
        "name": "TXS0108E 8-Bit Bidirectional Level Shifter",
        "category": "other",
        "sub_type": "level-shifter",
        "interface_types": ["GPIO", "SPI", "UART"],
        "package": "TSSOP-20",
        "mounting": "smd",
        "pin_count": 20,
        "description": "8-bit auto-dir bidirectional level shifter, 1.2V\u20133.6V \u2194 1.65V\u20135.5V, 100 Mbps",
        "electrical_ratings": {
            "vdd_min": 1.2, "vdd_max": 3.6,  # VCCA side
            "io_voltage_min": 1.65, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 2.0, "current_draw_max_ma": 50.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Drive OE pin HIGH to enable outputs; both VCCA and VCCB must be powered"},
        ]},
        "unit_cost_usd": 0.80,
        "tags": ["level-shifter", "logic", "bidirectional", "5v", "3.3v"],
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/txs0108e.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "channels": 8,
            "direction": "bidirectional",
            "vcca_min": 1.2,
            "vcca_max": 3.6,
            "vccb_min": 1.65,
            "vccb_max": 5.5,
            "max_data_rate_mbps": 100,
            "i2c_compatible": False,
        },
    },
    # -------------------------------------------------------------------------
    # Shift Registers
    # -------------------------------------------------------------------------
    {
        "mpn": "SN74HC595N",
        "manufacturer": "Texas Instruments",
        "name": "74HC595 8-Bit Shift Register with Output Latch",
        "category": "other",
        "sub_type": "shift-register",
        "interface_types": ["SPI", "GPIO"],
        "package": "DIP-16",
        "mounting": "tht",
        "pin_count": 16,
        "description": "8-bit serial-in/parallel-out shift register with output latches, daisychainable",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 6.0,
            "io_voltage_min": 2.0, "io_voltage_max": 6.0, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 80.0, "current_draw_max_ma": 160.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"spi_max_clock_hz": 25000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Hold SRCLR HIGH, OE LOW. Shift bits via SER+SRCLK, pulse RCLK to latch"},
        ]},
        "unit_cost_usd": 0.25,
        "tags": ["shift-register", "gpio", "spi", "serial", "parallel-out"],
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/sn74hc595.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "shift_type": "sipo",
            "bits": 8,
            "cascade": True,
            "output_latch": True,
            "output_enable_pin": True,
            "output_current_ma": 6,
        },
    },
    # -------------------------------------------------------------------------
    # Analog Multiplexer
    # -------------------------------------------------------------------------
    {
        "mpn": "CD74HC4051E",
        "manufacturer": "Texas Instruments",
        "name": "74HC4051 8-Channel Analog Multiplexer",
        "category": "other",
        "sub_type": "analog-mux",
        "interface_types": ["GPIO"],
        "package": "DIP-16",
        "mounting": "tht",
        "pin_count": 16,
        "description": "8-channel single-ended analog mux/demux with three digital select lines",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 6.0,
            "io_voltage_min": 2.0, "io_voltage_max": 6.0, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.08, "current_draw_max_ma": 1.0,
            "temp_min_c": -55.0, "temp_max_c": 125.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.30,
        "tags": ["mux", "analog", "gpio", "8-channel", "select"],
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/cd74hc4051.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "mux_channels": 8,
            "bidirectional": True,
            "on_resistance_ohm": 70,
            "bandwidth_mhz": 240,
            "break_before_make": True,
        },
    },

    # ===================================================================
    # P0.2 — Instrumentation Amplifier
    # ===================================================================
    {
        "mpn": "INA128UA",
        "manufacturer": "Texas Instruments",
        "name": "INA128 Instrumentation Amplifier",
        "category": "analog",
        "sub_type": "inamp",
        "interface_types": ["GPIO"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Precision instrumentation amplifier, gain 1–10000 set by single "
                       "external resistor (G = 1 + 50kΩ/Rg), 120dB CMRR, low offset 50µV, "
                       "±18V supply. For bridge sensors, strain gauges, medical instrumentation",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 36.0,
            "io_voltage_min": -18.0, "io_voltage_max": 18.0, "io_voltage_nominal": 5.0,
            "current_draw_typical_ma": 0.7, "current_draw_max_ma": 1.0,
            "abs_max_voltage": 40.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 3.50,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ina128.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "instrumentation_amplifier",
            "gain_min": 1,
            "gain_max": 10000,
            "gain_formula": "1 + 50000/Rg",
            "cmrr_db": 120,
            "input_offset_voltage_uv": 50,
            "input_bias_current_na": 5,
            "bandwidth_mhz": 1.3,
            "slew_rate_v_per_us": 4.0,
            "supply_dual": True,
            "supply_single": True,
        },
        "tags": ["inamp", "instrumentation", "precision", "bridge", "strain-gauge", "differential", "analog"],
        "tier": "enterprise",
    },

    # ===================================================================
    # P0.4 — Connector Templates
    # ===================================================================

    # --- JST-PH 2-pin (LiPo battery) ---
    {
        "mpn": "B2B-PH-K-S",
        "manufacturer": "JST",
        "name": "JST-PH 2-Pin Battery Connector",
        "category": "connector",
        "sub_type": "jst-ph",
        "interface_types": [],
        "package": "THT-2PIN",
        "mounting": "tht",
        "pin_count": 2,
        "description": "JST-PH 2-pin right-angle header, 2mm pitch, standard LiPo battery "
                       "connector used by Adafruit, SparkFun, and most hobby LiPo packs. "
                       "Rated 2A per pin, 100V",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 100.0,
            "current_draw_max_ma": 2000.0,
            "temp_min_c": -25.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.10,
        "datasheet_url": "https://www.jst-mfg.com/product/pdf/eng/ePH.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "connector_type": "jst-ph",
            "pitch_mm": 2.0,
            "pins": 2,
            "current_per_pin_a": 2.0,
            "voltage_max_v": 100.0,
            "mating_cycles": 30,
            "application": "battery",
        },
        "tags": ["connector", "jst-ph", "battery", "lipo", "2-pin", "2mm"],
        "tier": "community",
    },

    # --- JST-XH 4-pin (Board-to-Board) ---
    {
        "mpn": "B4B-XH-A",
        "manufacturer": "JST",
        "name": "JST-XH 4-Pin Board Connector",
        "category": "connector",
        "sub_type": "jst-xh",
        "interface_types": [],
        "package": "THT-4PIN",
        "mounting": "tht",
        "pin_count": 4,
        "description": "JST-XH 4-pin vertical header, 2.5mm pitch, common for board-to-board "
                       "power and signal connections. Rated 3A per pin, 250V. "
                       "Used for I2C, motor, stepper connections",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 250.0,
            "current_draw_max_ma": 3000.0,
            "temp_min_c": -25.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.12,
        "datasheet_url": "https://www.jst-mfg.com/product/pdf/eng/eXH.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "connector_type": "jst-xh",
            "pitch_mm": 2.5,
            "pins": 4,
            "current_per_pin_a": 3.0,
            "voltage_max_v": 250.0,
            "mating_cycles": 30,
            "application": "board-to-board",
        },
        "tags": ["connector", "jst-xh", "board-to-board", "4-pin", "2.5mm", "power", "signal"],
        "tier": "community",
    },

    # --- Screw Terminal 3-pin (24V + GND + Shield) ---
    {
        "mpn": "CONN-SCREW-3PIN-508",
        "manufacturer": "Generic",
        "name": "3-Pin 5.08mm Screw Terminal",
        "category": "connector",
        "sub_type": "screw-terminal",
        "interface_types": [],
        "package": "THT-3PIN",
        "mounting": "tht",
        "pin_count": 3,
        "description": "3-pin 5.08mm pitch PCB screw terminal block. For 24V industrial "
                       "power input (VIN, GND, Shield/PE). Rated 10A, 300V. "
                       "Accepts 12-24 AWG wire",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 300.0,
            "current_draw_max_ma": 10000.0,
            "temp_min_c": -40.0, "temp_max_c": 105.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.25,
        "datasheet_url": "",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "connector_type": "screw-terminal",
            "pitch_mm": 5.08,
            "pins": 3,
            "current_per_pin_a": 10.0,
            "voltage_max_v": 300.0,
            "wire_gauge_awg_min": 12,
            "wire_gauge_awg_max": 24,
            "application": "industrial-power",
        },
        "tags": ["connector", "screw-terminal", "3-pin", "5.08mm", "24v", "industrial", "power"],
        "tier": "community",
    },

    # --- M12 4-pin Template (Industrial Sensor) ---
    {
        "mpn": "CONN-M12-4PIN",
        "manufacturer": "Generic",
        "name": "M12 4-Pin A-coded Connector",
        "category": "connector",
        "sub_type": "m12",
        "interface_types": [],
        "package": "Panel-mount",
        "mounting": "tht",
        "pin_count": 4,
        "description": "M12 4-pin A-coded panel-mount connector, IP67 rated. "
                       "Industrial standard for sensor connections (IEC 61076-2-101). "
                       "Pin 1: VCC, Pin 2: Signal+, Pin 3: GND, Pin 4: Signal-",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 250.0,
            "current_draw_max_ma": 4000.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 3.50,
        "datasheet_url": "",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "connector_type": "m12",
            "coding": "A",
            "pins": 4,
            "ip_rating": "IP67",
            "current_per_pin_a": 4.0,
            "voltage_max_v": 250.0,
            "standard": "IEC 61076-2-101",
            "application": "industrial-sensor",
        },
        "tags": ["connector", "m12", "industrial", "ip67", "sensor", "4-pin", "panel-mount"],
        "tier": "enterprise",
    },

    # --- RJ45 with Integrated Magnetics (Ethernet) ---
    {
        "mpn": "HR911105A",
        "manufacturer": "Hanrun",
        "name": "HR911105A RJ45 with Magnetics",
        "category": "connector",
        "sub_type": "rj45",
        "interface_types": ["Ethernet"],
        "package": "THT-RJ45",
        "mounting": "tht",
        "pin_count": 16,
        "description": "RJ45 connector with integrated magnetics (1:1 transformer) and "
                       "LED indicators (green link, orange activity). Standard 10/100 "
                       "Ethernet jack. Compatible with LAN8720A, KSZ8081, ENC28J60",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 5.5,
            "current_draw_max_ma": 350.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 1.20,
        "datasheet_url": "https://datasheet.lcsc.com/szlcsc/HR911105A_C12074.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "connector_type": "rj45",
            "integrated_magnetics": True,
            "transformer_ratio": "1:1",
            "led_indicators": True,
            "speed_mbps": 100,
            "standard": "10/100BASE-T",
            "application": "ethernet",
        },
        "tags": ["connector", "rj45", "ethernet", "magnetics", "transformer", "10/100", "led"],
        "tier": "community",
    },
]
