# SPDX-License-Identifier: AGPL-3.0-or-later
"""Power management seed data — LDOs, buck/boost converters, chargers, fuel gauges."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    {
        "mpn": "AMS1117-3.3",
        "manufacturer": "Advanced Monolithic Systems",
        "name": "AMS1117-3.3 LDO Voltage Regulator",
        "category": "power",
        "sub_type": "ldo",
        "interface_types": ["GPIO"],
        "package": "SOT-223",
        "mounting": "smd",
        "pin_count": 3,
        "description": "1A LDO regulator, 5V→3.3V, 1.3V dropout — standard dev-board regulator",
        "electrical_ratings": {
            "vdd_min": 4.6, "vdd_max": 15.0,
            "io_voltage_nominal": 3.3,
            "current_draw_max_ma": 1000.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
            "quiescent_current_ua": 5000.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.30,
        "datasheet_url": "http://www.advanced-monolithic.com/pdf/ds1117.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "ldo",
            "output_voltage_v": 3.3,
            "output_voltage_adjustable": False,
            "output_current_max_ma": 1000,
            "input_voltage_min": 4.6,
            "input_voltage_max": 15.0,
            "dropout_voltage_mv": 1300,
            "quiescent_current_ua": 5000,
            "enable_pin": False,
            "power_good_pin": False,
            "soft_start": False,
            "short_circuit_protection": True,
            "thermal_shutdown": True,
            "output_cap_uf": 22,
            "input_cap_uf": 10,
        },
        "tags": ["ldo", "power", "3.3v", "regulator", "linear"],
    },
    {
        "mpn": "AP2112K-3.3TRG1",
        "manufacturer": "Diodes Inc",
        "name": "AP2112K 600mA CMOS LDO Regulator",
        "category": "power",
        "sub_type": "ldo",
        "interface_types": ["GPIO"],
        "package": "SOT-25",
        "mounting": "smd",
        "pin_count": 5,
        "description": "600mA LDO, 300mV dropout, 55µA quiescent, EN pin — low-noise RF/audio designs",
        "electrical_ratings": {
            "vdd_min": 2.5, "vdd_max": 6.0,
            "io_voltage_nominal": 3.3,
            "current_draw_max_ma": 600.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
            "quiescent_current_ua": 55.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.25,
        "datasheet_url": "https://www.diodes.com/assets/Datasheets/AP2112.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "ldo",
            "output_voltage_v": 3.3,
            "output_voltage_adjustable": False,
            "output_current_max_ma": 600,
            "input_voltage_min": 2.5,
            "input_voltage_max": 6.0,
            "dropout_voltage_mv": 300,
            "quiescent_current_ua": 55,
            "enable_pin": True,
            "power_good_pin": False,
            "soft_start": False,
            "short_circuit_protection": True,
            "thermal_shutdown": True,
            "output_cap_uf": 1.0,
            "input_cap_uf": 1.0,
        },
        "tags": ["ldo", "power", "3.3v", "regulator", "low-noise", "rf"],
    },
    {
        "mpn": "MCP1700-3302E",
        "manufacturer": "Microchip",
        "name": "MCP1700 250mA Ultra-Low Quiescent LDO",
        "category": "power",
        "sub_type": "ldo",
        "interface_types": ["GPIO"],
        "package": "SOT-23-3",
        "mounting": "smd",
        "pin_count": 3,
        "description": "250mA LDO, 178mV dropout, 1.6µA quiescent — ideal for battery-powered IoT",
        "electrical_ratings": {
            "vdd_min": 2.3, "vdd_max": 6.0,
            "io_voltage_nominal": 3.3,
            "current_draw_typical_ma": 0.0016, "current_draw_max_ma": 250.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
            "quiescent_current_ua": 1.6,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.50,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/20001826E.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "ldo",
            "output_voltage_v": 3.3,
            "output_voltage_adjustable": False,
            "output_current_max_ma": 250,
            "input_voltage_min": 2.3,
            "input_voltage_max": 6.0,
            "dropout_voltage_mv": 178,
            "quiescent_current_ua": 1.6,
            "enable_pin": False,
            "power_good_pin": False,
            "soft_start": False,
            "short_circuit_protection": True,
            "thermal_shutdown": True,
            "output_cap_uf": 1.0,
            "input_cap_uf": 1.0,
        },
        "tags": ["ldo", "power", "3.3v", "regulator", "low-power", "battery"],
    },
    {
        "mpn": "MP2307DN",
        "manufacturer": "MPS",
        "name": "MP2307 3A 23V Synchronous Buck Converter",
        "category": "power",
        "sub_type": "buck",
        "interface_types": ["GPIO"],
        "package": "SOIC-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "3A synchronous buck converter, 4.75–23V in, adjustable out, 340kHz",
        "electrical_ratings": {
            "vdd_min": 4.75, "vdd_max": 23.0,
            "current_draw_max_ma": 3000.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 1800.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.80,
        "datasheet_url": "https://www.monolithicpower.com/en/documentview/productdocument/index/version/2/document_type/Datasheet/lang/en/sku/MP2307DN-LF-Z/",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "buck",
            "output_voltage_v": None,
            "output_voltage_adjustable": True,
            "output_current_max_ma": 3000,
            "input_voltage_min": 4.75,
            "input_voltage_max": 23.0,
            "switching_freq_khz": 340,
            "efficiency_pct": 95,
            "integrated_fets": True,
            "quiescent_current_ua": 1800,
            "enable_pin": True,
            "power_good_pin": False,
            "soft_start": True,
            "short_circuit_protection": True,
            "thermal_shutdown": True,
            "inductor_uh": 10.0,
            "output_cap_uf": 100,
            "input_cap_uf": 22,
            "feedback_voltage_v": 0.925,
        },
        "tags": ["buck", "power", "switching", "regulator", "3a", "synchronous"],
    },
    {
        "mpn": "MT3608",
        "manufacturer": "Aerosemi",
        "name": "MT3608 2A Step-Up Boost Converter",
        "category": "power",
        "sub_type": "boost",
        "interface_types": ["GPIO"],
        "package": "SOT-23-6",
        "mounting": "smd",
        "pin_count": 6,
        "description": "2A boost converter, 2–24V in, up to 28V out, 1.2MHz — common 5V/12V booster",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 24.0,
            "current_draw_max_ma": 2000.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 600.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.40,
        "datasheet_url": "https://www.olimex.com/Products/Breadboarding/MT3608/resources/MT3608.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "boost",
            "output_voltage_v": None,
            "output_voltage_adjustable": True,
            "output_current_max_ma": 2000,
            "input_voltage_min": 2.0,
            "input_voltage_max": 24.0,
            "switching_freq_khz": 1200,
            "efficiency_pct": 93,
            "integrated_fets": True,
            "quiescent_current_ua": 600,
            "enable_pin": True,
            "power_good_pin": False,
            "soft_start": True,
            "short_circuit_protection": False,
            "thermal_shutdown": True,
            "inductor_uh": 22.0,
            "output_cap_uf": 22,
            "input_cap_uf": 10,
            "feedback_voltage_v": 0.6,
        },
        "tags": ["boost", "power", "switching", "regulator"],
    },
    {
        "mpn": "TP4056",
        "manufacturer": "NanJing Top Power ASIC",
        "name": "TP4056 Single-Cell Li-Ion/LiPo Charger",
        "category": "power",
        "sub_type": "charger",
        "interface_types": ["GPIO"],
        "package": "SOP-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "1A single-cell LiPo charger with thermal regulation, programmable charge current, CHRG/STDBY LEDs",
        "electrical_ratings": {
            "vdd_min": 4.0, "vdd_max": 8.0,
            "io_voltage_nominal": 4.2,
            "current_draw_max_ma": 1000.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.25,
        "datasheet_url": "https://dlnmh9ip6v2uc.cloudfront.net/datasheets/Prototyping/TP4056.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "charger",
            "battery_chemistry": "lipo",
            "cell_count": 1,
            "charge_voltage_v": 4.2,
            "charge_current_max_ma": 1000,
            "charge_current_programmable": True,
            "charge_current_set_method": "resistor",
            "precharge_threshold_v": 2.9,
            "termination_current_ma": 100,
            "input_voltage_min": 4.0,
            "input_voltage_max": 8.0,
            "charge_status_pins": 2,
            "ntc_monitoring": False,
            "timer_safety": True,
            "thermal_regulation": True,
            "input_path_management": False,
        },
        "tags": ["charger", "lipo", "battery", "usb", "1a"],
    },
    {
        "mpn": "MCP73831T-2ATI",
        "manufacturer": "Microchip",
        "name": "MCP73831 Single-Cell LiPo Charger",
        "category": "power",
        "sub_type": "charger",
        "interface_types": ["GPIO"],
        "package": "SOT-23-5",
        "mounting": "smd",
        "pin_count": 5,
        "description": "Single-cell Li-Ion/LiPo charger, 500mA, programmable via RPROG resistor",
        "electrical_ratings": {
            "vdd_min": 3.75, "vdd_max": 6.0,
            "io_voltage_nominal": 4.2,
            "current_draw_max_ma": 500.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.60,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/MCP73831-2-OT-MCP73832-2-OT-DS20001984G.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "charger",
            "battery_chemistry": "lipo",
            "cell_count": 1,
            "charge_voltage_v": 4.2,
            "charge_current_max_ma": 500,
            "charge_current_programmable": True,
            "charge_current_set_method": "resistor",
            "precharge_threshold_v": 2.8,
            "termination_current_ma": 36,
            "input_voltage_min": 3.75,
            "input_voltage_max": 6.0,
            "charge_status_pins": 1,
            "ntc_monitoring": False,
            "timer_safety": True,
            "thermal_regulation": True,
            "input_path_management": False,
        },
        "tags": ["charger", "lipo", "battery", "500ma"],
    },
    {
        "mpn": "MAX17048G+T",
        "manufacturer": "Maxim Integrated",
        "name": "MAX17048 LiPo Fuel Gauge",
        "category": "power",
        "sub_type": "fuel-gauge",
        "interface_types": ["I2C"],
        "package": "DFN-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "1-cell LiPo/Li-Ion fuel gauge with ModelGauge algorithm via I2C, 3µA quiescent",
        "electrical_ratings": {
            "vdd_min": 3.5, "vdd_max": 4.5,
            "io_voltage_min": 1.7, "io_voltage_max": 4.5, "io_voltage_nominal": 3.3,
            "current_draw_typical_ma": 0.003, "current_draw_max_ma": 0.3,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 3.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x36"],
        "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x08", "description": "Read Version register (expect 0x0011 or 0x001x)"}]},
            {"phase": "configure", "order": 1,
             "writes": [{"reg_addr": "0x0C", "value": "0x9700", "description": "Set RCOMP, TEMPCO from datasheet"}]},
        ]},
        "unit_cost_usd": 2.80,
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX17048-MAX17049.pdf",
        "status": "active",
        "library_support": ["arduino", "circuitpython"],
        "capabilities": {
            "topology": "fuel-gauge",
            "soc_algorithm": "modelgauge",
            "cell_count": 1,
            "soc_accuracy_pct": 1.0,
            "battery_chemistry": "lipo",
            "current_sense": False,
            "reported_params": ["soc", "voltage", "rate_of_change"],
            "alert_thresholds": True,
            "hibernate_current_ua": 0.5,
        },
        "tags": ["fuel-gauge", "battery", "lipo", "soc", "i2c", "low-power"],
    },
    {
        "mpn": "IP5306",
        "manufacturer": "INJOINIC",
        "name": "IP5306 Power Bank SoC",
        "category": "power",
        "sub_type": "power-bank",
        "interface_types": ["I2C"],
        "package": "SOP-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Integrated power bank IC: 5V/2.4A boost + LiPo charger + fuel gauge + 4 LEDs",
        "electrical_ratings": {
            "vdd_min": 3.4, "vdd_max": 4.35,
            "io_voltage_nominal": 5.0,
            "current_draw_max_ma": 2400.0,
            "temp_min_c": -20.0, "temp_max_c": 70.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x75"],
        "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [{"reg_addr": "0x00", "value": "0x37", "description": "Enable boost, charge, LEDs"}]},
        ]},
        "unit_cost_usd": 0.50,
        "datasheet_url": "https://datasheet.lcsc.com/szlcsc/INJOINIC-IP5306_C181692.pdf",
        "status": "active",
        "library_support": ["arduino"],
        "capabilities": {
            "topology": "power-bank",
            "integrated_charger": True,
            "integrated_boost": True,
            "integrated_fuel_gauge": True,
            "output_voltage_v": 5.0,
            "output_current_max_ma": 2400,
            "charge_current_max_ma": 2000,
            "cell_count": 1,
            "battery_chemistry": "lipo",
            "led_driver_pins": 4,
            "button_input": True,
            "usb_pd_support": False,
        },
        "tags": ["power-bank", "boost", "charger", "lipo", "fuel-gauge"],
    },

    # ===================================================================
    # P0.2 — Industrial Power Components (Load Switch, Ideal Diode,
    #         Power-Path, Battery Protection)
    # ===================================================================

    # --- Load Switch / eFuse ---
    {
        "mpn": "TPS22918DBVR",
        "manufacturer": "Texas Instruments",
        "name": "TPS22918 Load Switch",
        "category": "power",
        "sub_type": "load_switch",
        "interface_types": ["GPIO"],
        "package": "SOT-23-6",
        "mounting": "smd",
        "pin_count": 6,
        "description": "5.5V, 2A load switch with controlled rise time (1ms), 52mOhm Rds(on), "
                       "active-high ON, for USB/rail power gating and inrush current limiting",
        "electrical_ratings": {
            "vdd_min": 1.0, "vdd_max": 5.5,
            "io_voltage_nominal": 3.3,
            "current_draw_max_ma": 2000.0,
            "abs_max_voltage": 6.5,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
            "quiescent_current_ua": 1.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.45,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/tps22918.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "load_switch",
            "max_continuous_current_a": 2.0,
            "rds_on_mohm": 52,
            "controlled_rise_time_ms": 1.0,
            "enable_pin": True,
            "active_high": True,
            "reverse_current_blocking": True,
            "thermal_shutdown": True,
            "input_voltage_max": 5.5,
        },
        "tags": ["load-switch", "power-gating", "efuse", "soft-start", "inrush", "usb"],
        "tier": "enterprise",
    },

    # --- Ideal Diode / Reverse Polarity Controller ---
    {
        "mpn": "LM74610DGKR",
        "manufacturer": "Texas Instruments",
        "name": "LM74610 Smart Diode Controller",
        "category": "power",
        "sub_type": "ideal_diode",
        "interface_types": ["GPIO"],
        "package": "VSSOP-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Zero quiescent current ideal diode controller, uses external N-MOSFET, "
                       "replaces Schottky diodes for reverse polarity protection with < 30mV drop",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 45.0,
            "io_voltage_nominal": 12.0,
            "current_draw_max_ma": 0.0,
            "abs_max_voltage": 50.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
            "quiescent_current_ua": 0.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.85,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/lm74610.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "ideal_diode",
            "max_voltage_v": 45.0,
            "quiescent_current_ua": 0,
            "forward_voltage_drop_mv": 30,
            "requires_external_mosfet": True,
            "reverse_polarity_protection": True,
        },
        "tags": ["ideal-diode", "reverse-polarity", "verpolschutz", "mosfet", "industrial", "24v"],
        "tier": "enterprise",
    },

    # --- Power-Path IC (USB + Li-Ion) ---
    {
        "mpn": "BQ24075RGTR",
        "manufacturer": "Texas Instruments",
        "name": "BQ24075 Power-Path Li-Ion Charger",
        "category": "power",
        "sub_type": "power_path",
        "interface_types": ["GPIO"],
        "package": "QFN-16",
        "mounting": "smd",
        "pin_count": 16,
        "description": "1.5A USB-friendly Li-Ion charger with power-path management, "
                       "USB input current limiting (100/500mA), dynamic PPM, simultaneous "
                       "charge and system power, VOUT decoupled from battery",
        "electrical_ratings": {
            "vdd_min": 4.35, "vdd_max": 6.4,
            "io_voltage_nominal": 4.2,
            "current_draw_max_ma": 1500.0,
            "abs_max_voltage": 7.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 600.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 2.10,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/bq24075.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "power_path",
            "charge_current_max_ma": 1500,
            "usb_current_limit": True,
            "usb_100ma_mode": True,
            "usb_500ma_mode": True,
            "power_path_management": True,
            "simultaneous_charge_and_system": True,
            "cell_count": 1,
            "battery_chemistry": "lipo",
            "charge_voltage_v": 4.2,
            "pgood_output": True,
            "charge_status_outputs": 2,
        },
        "tags": ["power-path", "charger", "lipo", "usb", "load-sharing", "battery-management"],
        "tier": "enterprise",
    },

    # --- Battery Protection (1S) ---
    {
        "mpn": "DW01A-G",
        "manufacturer": "Fortune Semiconductor",
        "name": "DW01A Li-Ion Battery Protection IC",
        "category": "power",
        "sub_type": "battery_protection",
        "interface_types": [],
        "package": "SOT-23-6",
        "mounting": "smd",
        "pin_count": 6,
        "description": "1S Li-Ion/LiPo battery protection: overcharge (4.3V), "
                       "over-discharge (2.4V), overcurrent (3A), short-circuit protection. "
                       "Paired with FS8205A dual MOSFET for charge/discharge switching",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 5.0,
            "io_voltage_nominal": 3.7,
            "current_draw_max_ma": 0.005,
            "abs_max_voltage": 7.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 3.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.05,
        "datasheet_url": "https://datasheet.lcsc.com/szlcsc/Fortune-Semicon-DW01A-G_C351410.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "battery_protection",
            "cell_count": 1,
            "ovp_threshold_v": 4.3,
            "uvp_threshold_v": 2.4,
            "ocp_threshold_a": 3.0,
            "short_circuit_protection": True,
            "requires_external_mosfet": True,
            "recommended_mosfet": "FS8205A",
        },
        "tags": ["battery-protection", "lipo", "1s", "ovp", "uvp", "ocp", "dw01a"],
        "tier": "enterprise",
    },
    {
        "mpn": "FS8205A",
        "manufacturer": "Fortune Semiconductor",
        "name": "FS8205A Dual N-MOSFET for Battery Protection",
        "category": "power",
        "sub_type": "battery_protection",
        "interface_types": [],
        "package": "TSSOP-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Dual N-channel MOSFET (Rds(on) 24mOhm each) for 1S Li-Ion protection, "
                       "paired with DW01A protection IC. Back-to-back configuration for "
                       "charge/discharge current switching",
        "electrical_ratings": {
            "vdd_min": 0.0, "vdd_max": 20.0,
            "io_voltage_nominal": 3.7,
            "current_draw_max_ma": 6000.0,
            "abs_max_voltage": 20.0,
            "temp_min_c": -40.0, "temp_max_c": 150.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 0.05,
        "datasheet_url": "https://datasheet.lcsc.com/szlcsc/Fortune-Semicon-FS8205A_C32254.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "dual_mosfet",
            "rds_on_mohm": 24,
            "max_continuous_current_a": 6.0,
            "vds_max_v": 20.0,
            "vgs_threshold_v": 1.0,
            "paired_with": "DW01A-G",
        },
        "tags": ["mosfet", "dual-mosfet", "battery-protection", "lipo", "1s"],
        "tier": "enterprise",
    },

    # ===================================================================
    # DB-6 Seed Expansion — Ideal Diode, Wide-Input Buck
    # ===================================================================

    # --- LTC4359 Ideal Diode Controller ---
    {
        "mpn": "LTC4359ITS8-TRMPBF",
        "manufacturer": "Analog Devices / Linear Technology",
        "name": "LTC4359 Ideal Diode Controller",
        "category": "power",
        "sub_type": "protection",
        "interface_types": ["GPIO"],
        "package": "TSOT-23-8",
        "mounting": "smd",
        "pin_count": 8,
        "description": "Ideal Diode controller 3.5V-36V — eliminates reverse-polarity diode dropout",
        "electrical_ratings": {
            "vdd_min": 3.5, "vdd_max": 36.0,
            "io_voltage_nominal": 12.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.025, "current_draw_max_ma": 0.05,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
    },

    # ===================================================================
    # Solar Power Management
    # ===================================================================

    # --- MPPT Solar Boost Converter ---
    {
        "mpn": "SPV1040",
        "manufacturer": "STMicroelectronics",
        "name": "SPV1040 MPPT Solar Boost Converter",
        "category": "power",
        "sub_type": "mppt",
        "interface_types": ["GPIO"],
        "package": "TSOT-23-6",
        "mounting": "smd",
        "pin_count": 6,
        "description": (
            "Indoors/outdoors MPPT (Maximum Power Point Tracking) solar boost converter. "
            "Input 0.3V-5.5V from PV cell, output up to 5V/400mA, 95% peak efficiency. "
            "Fractional open-circuit MPPT, adjustable via resistor divider."
        ),
        "electrical_ratings": {
            "vdd_min": 0.3, "vdd_max": 5.5,
            "io_voltage_nominal": 3.3,
            "current_draw_max_ma": 400.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 800.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 1.20,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/spv1040.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "mppt_boost",
            "input_voltage_min": 0.3,
            "input_voltage_max": 5.5,
            "output_voltage_v": 5.0,
            "output_voltage_adjustable": True,
            "output_current_max_ma": 400,
            "efficiency_pct": 95,
            "mppt_algorithm": "fractional_open_circuit",
            "solar_cell_compatible": True,
            "switching_freq_khz": 100,
        },
        "tags": ["solar", "mppt", "boost", "power", "photovoltaic", "energy-harvesting"],
    },

    # --- Solar Battery Charger ---
    {
        "mpn": "BQ24650",
        "manufacturer": "Texas Instruments",
        "name": "BQ24650 Solar Battery Charger Controller",
        "category": "power",
        "sub_type": "solar_charger",
        "interface_types": ["GPIO", "analog"],
        "package": "VQFN-20",
        "mounting": "smd",
        "pin_count": 20,
        "description": (
            "Synchronous switch-mode solar battery charge controller. "
            "Supports Li-Ion, Li-Polymer, LiFePO4, NiMH. MPPT via MPPSET resistor divider. "
            "Input 5V-28V (solar panel / DC source), up to 10A charge current, "
            "High-accuracy voltage (0.5%) and current (1%) regulation."
        ),
        "electrical_ratings": {
            "vdd_min": 5.0, "vdd_max": 28.0,
            "io_voltage_nominal": 5.0,
            "current_draw_max_ma": 10000.0,
            "abs_max_voltage": 30.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
            "quiescent_current_ua": 700.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 2.80,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/bq24650.pdf",
        "status": "active",
        "library_support": [],
        "capabilities": {
            "topology": "solar_charger",
            "input_voltage_min": 5.0,
            "input_voltage_max": 28.0,
            "charge_current_max_a": 10.0,
            "battery_chemistry": ["lipo", "lifepo4", "nimh"],
            "mppt_support": True,
            "mppt_method": "mppset_resistor",
            "charge_voltage_accuracy_pct": 0.5,
            "charge_current_accuracy_pct": 1.0,
            "cell_count": "1-4",
            "synchronous": True,
            "external_mosfet": True,
        },
        "tags": [
            "solar", "charger", "battery", "mppt", "lipo", "lifepo4",
            "synchronous", "solar-charger", "solar-battery", "bq24650",
        ],
    },
]
