# SPDX-License-Identifier: AGPL-3.0-or-later
"""Sensor seed data — environmental, IMU, distance, light, bio, power monitors, gas, touch."""
from __future__ import annotations
from knowledge.schema import ComponentEntry

COMPONENTS: list[ComponentEntry] = [
    # --- Environmental ---
    {
        "mpn": "BME280",
        "manufacturer": "Bosch Sensortec",
        "name": "BME280 Pressure/Humidity/Temperature Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "SPI"],
        "package": "LGA-8",
        "description": "Combined humidity, temperature, and barometric pressure sensor",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 3.6,
            "io_voltage_min": 1.2, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False, "logic_high_min": 0.7, "logic_low_max": 0.3,
            "current_draw_typical_ma": 0.34, "current_draw_max_ma": 1.0,
            "abs_max_voltage": 4.25, "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 3400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 10000000, "spi_modes": [0, 3],
        },
        "known_i2c_addresses": ["0x76", "0x77"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0xE0", "value": "0xB6", "description": "Soft reset"}],
             "delay_after_ms": 2},
            {"phase": "verify", "order": 1,
             "reads": [{"reg_addr": "0xD0", "expected_value": "0x60", "description": "chip_id expect 0x60"}]},
            {"phase": "configure", "order": 2,
             "writes": [
                 {"reg_addr": "0xF2", "value": "0x01", "description": "ctrl_hum: oversampling x1"},
                 {"reg_addr": "0xF4", "value": "0x27", "description": "ctrl_meas: temp x1, press x1, normal"},
                 {"reg_addr": "0xF5", "value": "0xA0", "description": "config: standby 1000ms, filter off"},
             ]},
        ]},
        "unit_cost_usd": 3.80,
        "tags": ["temperature", "humidity", "pressure", "environmental"],
        "capabilities": {
            "measures": ["temperature", "humidity", "pressure"],
            "range": {
                "temperature": {"min": -40, "max": 85, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
                "pressure": {"min": 300, "max": 1100, "unit": "hPa"},
            },
            "accuracy": {
                "temperature": {"value": 1.0, "unit": "°C"},
                "humidity": {"value": 3.0, "unit": "%RH"},
                "pressure": {"value": 1.0, "unit": "hPa"},
            },
            "resolution": {
                "temperature": {"value": 0.01, "unit": "°C"},
                "humidity": {"value": 0.008, "unit": "%RH"},
                "pressure": {"value": 0.18, "unit": "Pa"},
            },
            "resolution_bits": 20,
            "oversampling": True,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "BME680",
        "manufacturer": "Bosch Sensortec",
        "name": "BME680 Environmental Sensor + VOC Gas",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme680-ds001.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "SPI"],
        "package": "LGA-8",
        "description": "Environmental sensor with temperature, pressure, humidity and VOC gas",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 3.6,
            "io_voltage_min": 1.71, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.9, "current_draw_max_ma": 13.0,
            "abs_max_voltage": 4.25, "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 3400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 10000000, "spi_modes": [0, 3],
        },
        "known_i2c_addresses": ["0x76", "0x77"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0xE0", "value": "0xB6", "description": "Soft reset"}],
             "delay_after_ms": 10},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x72", "value": "0x01", "description": "Humidity oversampling x1"},
                 {"reg_addr": "0x74", "value": "0x27", "description": "Temp x1, Press x1, forced mode"},
                 {"reg_addr": "0x5A", "value": "0x73", "description": "Heater resistance 300C"},
                 {"reg_addr": "0x64", "value": "0x59", "description": "Gas wait 100ms"},
                 {"reg_addr": "0x71", "value": "0x10", "description": "Enable gas measurement"},
             ]},
        ]},
        "unit_cost_usd": 4.50,
        "tags": ["temperature", "humidity", "pressure", "gas", "voc", "environmental", "air-quality"],
        "capabilities": {
            "measures": ["temperature", "humidity", "pressure", "gas"],
            "range": {
                "temperature": {"min": -40, "max": 85, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
                "pressure": {"min": 300, "max": 1100, "unit": "hPa"},
            },
            "accuracy": {
                "temperature": {"value": 1.0, "unit": "°C"},
                "humidity": {"value": 3.0, "unit": "%RH"},
                "pressure": {"value": 0.6, "unit": "hPa"},
            },
            "resolution": {
                "temperature": {"value": 0.01, "unit": "°C"},
                "humidity": {"value": 0.008, "unit": "%RH"},
                "pressure": {"value": 0.18, "unit": "Pa"},
            },
            "resolution_bits": 20,
            "oversampling": True,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
            "gas_types": ["voc"],
            "warmup_time_s": 30,
        },
    },
    {
        "mpn": "AHT20",
        "manufacturer": "ASAIR",
        "name": "AHT20 Temperature and Humidity Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 6,
        "datasheet_url": "https://asairsensors.com/wp-content/uploads/2021/09/Data-Sheet-AHT20-Humidity-and-Temperature-Sensor-ASAIR-V1.0.03.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "LCC-6",
        "description": "Calibrated digital humidity and temperature sensor",
        "electrical_ratings": {
            "vdd_min": 2.2, "vdd_max": 5.5,
            "io_voltage_min": 2.2, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.23, "current_draw_max_ma": 1.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x38"], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 40, "description": "Power-on startup"},
            {"phase": "configure", "order": 1,
             "writes": [{"reg_addr": "0xBE", "value": "0x08", "description": "Initialize calibration"}],
             "delay_after_ms": 10},
        ]},
        "unit_cost_usd": 1.20,
        "tags": ["temperature", "humidity", "environmental"],
        "capabilities": {
            "measures": ["temperature", "humidity"],
            "range": {
                "temperature": {"min": -40, "max": 85, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
            },
            "accuracy": {
                "temperature": {"value": 0.3, "unit": "°C"},
                "humidity": {"value": 2.0, "unit": "%RH"},
            },
            "resolution": {
                "temperature": {"value": 0.01, "unit": "°C"},
                "humidity": {"value": 0.024, "unit": "%RH"},
            },
            "resolution_bits": 20,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "SHTC3",
        "manufacturer": "Sensirion",
        "name": "SHTC3 Humidity and Temperature Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 4,
        "datasheet_url": "https://sensirion.com/media/documents/643F9C8E/6164081E/Sensirion_Humidity_Sensors_SHTC3_Datasheet.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "DFN-4",
        "description": "Ultra-low-power digital humidity & temperature sensor, RH ±2%, T ±0.2°C",
        "electrical_ratings": {
            "vdd_min": 1.62, "vdd_max": 3.6,
            "io_voltage_min": 1.62, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.45, "current_draw_max_ma": 2.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"]},
        "known_i2c_addresses": ["0x70"], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0, "delay_after_ms": 1, "description": "Software reset 0x805D"},
            {"phase": "configure", "order": 1,
             "description": "Measurement command 0x7CA2 (normal) or 0x6458 (low-power)",
             "delay_after_ms": 13},
        ]},
        "unit_cost_usd": 1.80,
        "tags": ["temperature", "humidity", "environmental", "low-power", "sensirion"],
        "capabilities": {
            "measures": ["temperature", "humidity"],
            "range": {
                "temperature": {"min": -40, "max": 125, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
            },
            "accuracy": {
                "temperature": {"value": 0.2, "unit": "°C"},
                "humidity": {"value": 2.0, "unit": "%RH"},
            },
            "resolution": {
                "temperature": {"value": 0.01, "unit": "°C"},
                "humidity": {"value": 0.01, "unit": "%RH"},
            },
            "resolution_bits": 16,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "SHT31-DIS",
        "manufacturer": "Sensirion",
        "name": "SHT31 High-Accuracy Temperature and Humidity Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://sensirion.com/media/documents/213E6A3B/63A5A569/Datasheet_SHT3x_DIS.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "DFN-8",
        "description": "High-accuracy digital temperature and humidity sensor, ±0.3°C, ±2% RH",
        "electrical_ratings": {
            "vdd_min": 2.4, "vdd_max": 5.5,
            "io_voltage_min": 2.4, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.6, "current_draw_max_ma": 1.5,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 1000000, "i2c_modes": ["standard", "fast", "fast_plus"]},
        "known_i2c_addresses": ["0x44", "0x45"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x30A2", "value": "", "description": "Soft reset"}],
             "delay_after_ms": 2},
            {"phase": "configure", "order": 1,
             "writes": [{"reg_addr": "0x2400", "value": "", "description": "Single-shot high repeatability"}],
             "delay_after_ms": 16},
        ]},
        "unit_cost_usd": 4.20,
        "tags": ["temperature", "humidity", "environmental", "sensirion", "high-accuracy"],
        "capabilities": {
            "measures": ["temperature", "humidity"],
            "range": {
                "temperature": {"min": -40, "max": 125, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
            },
            "accuracy": {
                "temperature": {"value": 0.3, "unit": "°C"},
                "humidity": {"value": 2.0, "unit": "%RH"},
            },
            "resolution": {
                "temperature": {"value": 0.015, "unit": "°C"},
                "humidity": {"value": 0.01, "unit": "%RH"},
            },
            "resolution_bits": 16,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "MCP9808",
        "manufacturer": "Microchip",
        "name": "MCP9808 High-Accuracy Temperature Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/25095A.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "SOT-23-5",
        "description": "High-accuracy (+/- 0.25C) digital temperature sensor with alert",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 5.5,
            "io_voltage_min": 2.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.2, "current_draw_max_ma": 0.4,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x18", "0x19", "0x1A", "0x1B", "0x1C", "0x1D", "0x1E", "0x1F"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x06", "expected_value": "0x0054", "description": "Manufacturer ID"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x08", "value": "0x03", "description": "Resolution 0.0625°C"},
                 {"reg_addr": "0x01", "value": "0x0000", "description": "Enable continuous conversion"},
             ]},
        ]},
        "unit_cost_usd": 1.80,
        "tags": ["temperature", "environmental", "high-accuracy"],
        "capabilities": {
            "measures": ["temperature"],
            "range": {
                "temperature": {"min": -40, "max": 125, "unit": "°C"},
            },
            "accuracy": {
                "temperature": {"value": 0.25, "unit": "°C"},
            },
            "resolution": {
                "temperature": {"value": 0.0625, "unit": "°C"},
            },
            "resolution_bits": 13,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "SCD41",
        "manufacturer": "Sensirion",
        "name": "SCD41 CO2 + Temperature + Humidity Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "smd",
        "pin_count": 10,
        "datasheet_url": "https://sensirion.com/media/documents/48C4B7FB/6426E14D/CD_DS_SCD40_SCD41_Datasheet_D1.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "DFN-10",
        "description": "Photoacoustic NDIR CO2 sensor, 400–5000ppm, ±40ppm, with T+RH",
        "electrical_ratings": {
            "vdd_min": 2.4, "vdd_max": 5.5,
            "io_voltage_min": 1.75, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 18.0, "current_draw_max_ma": 205.0,
            "temp_min_c": -10.0, "temp_max_c": 60.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 100000, "i2c_modes": ["standard"]},
        "known_i2c_addresses": ["0x62"], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x3646", "value": "", "description": "Stop periodic measurement"}],
             "delay_after_ms": 500},
            {"phase": "configure", "order": 1,
             "writes": [{"reg_addr": "0x21B1", "value": "", "description": "Start periodic measurement"}],
             "delay_after_ms": 5000},
        ]},
        "unit_cost_usd": 20.00,
        "tags": ["co2", "carbon-dioxide", "temperature", "humidity", "air-quality", "sensirion"],
        "capabilities": {
            "measures": ["co2", "temperature", "humidity"],
            "range": {
                "co2": {"min": 400, "max": 5000, "unit": "ppm"},
                "temperature": {"min": -10, "max": 60, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
            },
            "accuracy": {
                "co2": {"value": 40, "unit": "ppm"},
                "temperature": {"value": 0.8, "unit": "°C"},
                "humidity": {"value": 6.0, "unit": "%RH"},
            },
            "resolution": {
                "co2": {"value": 1, "unit": "ppm"},
                "temperature": {"value": 0.01, "unit": "°C"},
                "humidity": {"value": 0.01, "unit": "%RH"},
            },
            "sample_rate_hz": 0.2,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": True,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "MLX90614ESF",
        "manufacturer": "Melexis",
        "name": "MLX90614 Non-Contact IR Temperature Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "tht",
        "pin_count": 4,
        "datasheet_url": "https://www.melexis.com/en/documents/documentation/datasheets/datasheet-mlx90614",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "TO-39",
        "description": "Contactless IR thermometer, -70°C to +380°C, ±0.5°C, 90° FOV",
        "electrical_ratings": {
            "vdd_min": 2.6, "vdd_max": 3.6,
            "io_voltage_min": 2.6, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 1.5, "current_draw_max_ma": 2.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 100000, "i2c_modes": ["standard"]},
        "known_i2c_addresses": ["0x5A"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x07", "description": "Read object temperature (Ta reg)"}]},
        ]},
        "unit_cost_usd": 8.50,
        "tags": ["temperature", "ir", "non-contact", "infrared", "thermometer"],
        "capabilities": {
            "measures": ["temperature"],
            "range": {
                "temperature": {"min": -70, "max": 380, "unit": "°C"},
            },
            "accuracy": {
                "temperature": {"value": 0.5, "unit": "°C"},
            },
            "resolution": {
                "temperature": {"value": 0.02, "unit": "°C"},
            },
            "resolution_bits": 17,
            "fov_deg": 90,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    # --- IMU ---
    {
        "mpn": "MPU-6050",
        "manufacturer": "InvenSense",
        "name": "MPU-6050 6-Axis IMU",
        "category": "sensor",
        "sub_type": "imu",
        "mounting": "smd",
        "pin_count": 24,
        "datasheet_url": "https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "QFN-24",
        "description": "6-axis (3-axis gyroscope + 3-axis accelerometer) IMU with DMP",
        "electrical_ratings": {
            "vdd_min": 2.375, "vdd_max": 3.46,
            "io_voltage_min": 1.8, "io_voltage_max": 3.46, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 3.9, "current_draw_max_ma": 10.0,
            "abs_max_voltage": 4.0, "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x68", "0x69"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x6B", "value": "0x80", "description": "PWR_MGMT_1: device reset"}],
             "delay_after_ms": 100},
            {"phase": "verify", "order": 1,
             "reads": [{"reg_addr": "0x75", "expected_value": "0x68", "description": "WHO_AM_I"}]},
            {"phase": "configure", "order": 2,
             "writes": [
                 {"reg_addr": "0x6B", "value": "0x01", "description": "Wake up, use PLL"},
                 {"reg_addr": "0x1A", "value": "0x03", "description": "DLPF 44Hz"},
                 {"reg_addr": "0x1B", "value": "0x08", "description": "Gyro ±500 dps"},
                 {"reg_addr": "0x1C", "value": "0x00", "description": "Accel ±2g"},
             ]},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["imu", "gyroscope", "accelerometer", "motion"],
        "capabilities": {
            "measures": ["acceleration", "angular_velocity", "temperature"],
            "axes": 6,
            "accel_range_g": [2, 4, 8, 16],
            "gyro_range_dps": [250, 500, 1000, 2000],
            "resolution_bits": 16,
            "sample_rate_hz": 1000,
            "fifo_depth": 1024,
            "interrupt_pin": True,
            "self_test": True,
            "sensor_fusion": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "ICM-42688-P",
        "manufacturer": "TDK InvenSense",
        "name": "ICM-42688-P 6-Axis IMU",
        "category": "sensor",
        "sub_type": "imu",
        "mounting": "smd",
        "pin_count": 14,
        "datasheet_url": "https://invensense.tdk.com/wp-content/uploads/2020/04/ds-000347_icm-42688-p-datasheet.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "SPI"],
        "package": "LGA-14",
        "description": "High-precision 6-axis IMU: ±16g accel, ±2000 dps gyro, 20-bit FIFO",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 1.89,
            "io_voltage_min": 1.71, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.77, "current_draw_max_ma": 1.6,
            "abs_max_voltage": 3.9, "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 24000000, "spi_modes": [0, 3],
        },
        "known_i2c_addresses": ["0x68", "0x69"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x11", "value": "0x01", "description": "DEVICE_CONFIG: soft reset"}],
             "delay_after_ms": 1},
            {"phase": "verify", "order": 1,
             "reads": [{"reg_addr": "0x75", "expected_value": "0x47", "description": "WHO_AM_I"}]},
            {"phase": "configure", "order": 2,
             "writes": [
                 {"reg_addr": "0x4E", "value": "0x0F", "description": "PWR_MGMT0: accel+gyro low-noise"},
                 {"reg_addr": "0x50", "value": "0x06", "description": "±2000 dps / ±16g, 1kHz ODR"},
             ], "delay_after_ms": 1},
        ]},
        "unit_cost_usd": 5.50,
        "tags": ["imu", "gyroscope", "accelerometer", "motion", "high-precision"],
        "capabilities": {
            "measures": ["acceleration", "angular_velocity", "temperature"],
            "axes": 6,
            "accel_range_g": [2, 4, 8, 16],
            "gyro_range_dps": [250, 500, 1000, 2000],
            "resolution_bits": 16,
            "sample_rate_hz": 32000,
            "fifo_depth": 2048,
            "interrupt_pin": True,
            "self_test": True,
            "sensor_fusion": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "ADXL345",
        "manufacturer": "Analog Devices",
        "name": "ADXL345 3-Axis Accelerometer",
        "category": "sensor",
        "sub_type": "imu",
        "mounting": "smd",
        "pin_count": 14,
        "datasheet_url": "https://www.analog.com/media/en/technical-documentation/data-sheets/ADXL345.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "SPI"],
        "package": "LGA-14",
        "description": "3-axis digital accelerometer, 13-bit resolution, ±16g",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 3.6,
            "io_voltage_min": 1.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.14, "current_draw_max_ma": 0.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 5000000, "spi_modes": [3],
        },
        "known_i2c_addresses": ["0x53", "0x1D"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x00", "expected_value": "0xE5", "description": "DEVID"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x31", "value": "0x0B", "description": "Full resolution, ±16g"},
                 {"reg_addr": "0x2C", "value": "0x0A", "description": "Data rate 100Hz"},
                 {"reg_addr": "0x2D", "value": "0x08", "description": "Measurement mode"},
             ]},
        ]},
        "unit_cost_usd": 2.80,
        "tags": ["accelerometer", "motion", "imu"],
        "capabilities": {
            "measures": ["acceleration"],
            "axes": 3,
            "accel_range_g": [2, 4, 8, 16],
            "resolution_bits": 13,
            "sample_rate_hz": 3200,
            "fifo_depth": 32,
            "interrupt_pin": True,
            "self_test": True,
            "sensor_fusion": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "LIS3DH",
        "manufacturer": "STMicroelectronics",
        "name": "LIS3DH Ultra-Low-Power 3-Axis Accelerometer",
        "category": "sensor",
        "sub_type": "imu",
        "mounting": "smd",
        "pin_count": 16,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/lis3dh.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "SPI"],
        "package": "LGA-16",
        "description": "Ultra-low-power 3-axis MEMS accelerometer, ±2/4/8/16g",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 3.6,
            "io_voltage_min": 1.71, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.011, "current_draw_max_ma": 0.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 10000000, "spi_modes": [3],
        },
        "known_i2c_addresses": ["0x18", "0x19"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x0F", "expected_value": "0x33", "description": "WHO_AM_I"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x20", "value": "0x57", "description": "100Hz, normal mode, all axes"},
                 {"reg_addr": "0x23", "value": "0x88", "description": "BDU enabled, ±2g, high resolution"},
             ]},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["accelerometer", "motion", "low-power"],
        "capabilities": {
            "measures": ["acceleration"],
            "axes": 3,
            "accel_range_g": [2, 4, 8, 16],
            "resolution_bits": 12,
            "sample_rate_hz": 5376,
            "fifo_depth": 32,
            "interrupt_pin": True,
            "self_test": True,
            "sensor_fusion": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "BNO055",
        "manufacturer": "Bosch Sensortec",
        "name": "BNO055 9-Axis Absolute Orientation Sensor",
        "category": "sensor",
        "sub_type": "imu",
        "mounting": "smd",
        "pin_count": 28,
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bno055-ds000.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "LGA-28",
        "description": "9-axis absolute orientation sensor with built-in sensor fusion",
        "electrical_ratings": {
            "vdd_min": 2.4, "vdd_max": 3.6,
            "io_voltage_min": 1.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 12.3, "current_draw_max_ma": 12.3,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x28", "0x29"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x3F", "value": "0x20", "description": "System reset"}],
             "delay_after_ms": 650},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x3E", "value": "0x00", "description": "Normal power mode"},
                 {"reg_addr": "0x3D", "value": "0x0C", "description": "NDOF fusion mode"},
             ], "delay_after_ms": 20},
        ]},
        "unit_cost_usd": 6.50,
        "tags": ["imu", "9-axis", "fusion", "orientation", "quaternion"],
        "capabilities": {
            "measures": ["acceleration", "angular_velocity", "magnetic_field", "orientation"],
            "axes": 9,
            "accel_range_g": [2, 4, 8, 16],
            "gyro_range_dps": [125, 250, 500, 1000, 2000],
            "resolution_bits": 14,
            "sample_rate_hz": 100,
            "fifo_depth": 0,
            "interrupt_pin": True,
            "self_test": True,
            "sensor_fusion": True,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "LSM6DSO",
        "manufacturer": "STMicroelectronics",
        "name": "LSM6DSO 6-Axis IMU with Machine Learning Core",
        "category": "sensor",
        "sub_type": "imu",
        "mounting": "smd",
        "pin_count": 14,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/lsm6dso.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "SPI"],
        "package": "LGA-14",
        "description": "iNEMO 6-axis IMU (accel + gyro) with machine learning core",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 3.6,
            "io_voltage_min": 1.62, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.55, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"],
            "spi_max_clock_hz": 10000000, "spi_modes": [3],
        },
        "known_i2c_addresses": ["0x6A", "0x6B"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x12", "value": "0x01", "description": "Software reset"}],
             "delay_after_ms": 10},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x12", "value": "0x44", "description": "BDU enabled, auto-increment"},
                 {"reg_addr": "0x10", "value": "0x40", "description": "Accel 104Hz, ±2g"},
                 {"reg_addr": "0x11", "value": "0x40", "description": "Gyro 104Hz, 250 dps"},
             ]},
        ]},
        "unit_cost_usd": 3.00,
        "tags": ["imu", "gyroscope", "accelerometer", "motion", "machine-learning"],
        "capabilities": {
            "measures": ["acceleration", "angular_velocity", "temperature"],
            "axes": 6,
            "accel_range_g": [2, 4, 8, 16],
            "gyro_range_dps": [125, 250, 500, 1000, 2000],
            "resolution_bits": 16,
            "sample_rate_hz": 6664,
            "fifo_depth": 3072,
            "interrupt_pin": True,
            "self_test": True,
            "sensor_fusion": False,
            "calibration_factory": True,
        },
    },
    # --- Distance / Light / Proximity ---
    {
        "mpn": "VL53L0X",
        "manufacturer": "STMicroelectronics",
        "name": "VL53L0X Time-of-Flight Distance Sensor",
        "category": "sensor",
        "sub_type": "distance",
        "mounting": "smd",
        "pin_count": 12,
        "datasheet_url": "https://www.st.com/resource/en/datasheet/vl53l0x.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C", "GPIO"],
        "package": "LCC-12",
        "description": "940nm laser ToF ranging sensor, up to 2m range",
        "electrical_ratings": {
            "vdd_min": 2.6, "vdd_max": 3.5,
            "io_voltage_min": 1.8, "io_voltage_max": 3.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 19.0, "current_draw_max_ma": 40.0,
            "abs_max_voltage": 3.6, "temp_min_c": -20.0, "temp_max_c": 70.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x29"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "enable", "order": 0,
             "description": "Assert XSHUT HIGH to enable", "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "description": "Load factory tuning, init ranging"},
        ]},
        "unit_cost_usd": 4.50,
        "tags": ["tof", "distance", "ranging", "laser"],
        "capabilities": {
            "measures": ["distance"],
            "range": {
                "distance": {"min": 30, "max": 2000, "unit": "mm"},
            },
            "accuracy": {
                "distance": {"value": 3, "unit": "%"},
            },
            "fov_deg": 25,
            "ranging_max_mm": 2000,
            "sample_rate_hz": 50,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "HC-SR04",
        "manufacturer": "Generic",
        "name": "HC-SR04 Ultrasonic Distance Sensor",
        "category": "sensor",
        "sub_type": "distance",
        "mounting": "module",
        "pin_count": 4,
        "datasheet_url": "https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["GPIO"],
        "package": "module",
        "description": "Ultrasonic ranging module, 2–400cm, 15° beam, TRIG+ECHO GPIO",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_min": 3.3, "io_voltage_max": 5.0, "io_voltage_nominal": 5.0,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 15.0, "current_draw_max_ma": 20.0,
            "temp_min_c": -15.0, "temp_max_c": 70.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Pulse TRIG HIGH 10µs, measure ECHO pulse duration (time-of-flight)"},
        ]},
        "unit_cost_usd": 0.50,
        "tags": ["ultrasonic", "distance", "ranging", "gpio"],
        "capabilities": {
            "measures": ["distance"],
            "range": {
                "distance": {"min": 20, "max": 4000, "unit": "mm"},
            },
            "accuracy": {
                "distance": {"value": 3, "unit": "mm"},
            },
            "fov_deg": 15,
            "ranging_max_mm": 4000,
            "sample_rate_hz": 40,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "APDS-9960",
        "manufacturer": "Broadcom",
        "name": "APDS-9960 Gesture/Proximity/Light/Color Sensor",
        "category": "sensor",
        "sub_type": "light",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://docs.broadcom.com/doc/AV02-4191EN",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "LCC-6",
        "description": "Digital proximity, ambient light, RGB and gesture sensor",
        "electrical_ratings": {
            "vdd_min": 2.4, "vdd_max": 3.6,
            "io_voltage_min": 1.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 4.5, "current_draw_max_ma": 8.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x39"], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "verify", "order": 0,
             "reads": [{"reg_addr": "0x92", "expected_value": "0xAB", "description": "Device ID"}]},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x80", "value": "0x00", "description": "Disable all"},
                 {"reg_addr": "0x81", "value": "0xDB", "description": "ALS integration 103ms"},
                 {"reg_addr": "0x8F", "value": "0x01", "description": "Proximity gain 2x, ALS 4x"},
                 {"reg_addr": "0x80", "value": "0x07", "description": "Enable PON + ALS + proximity"},
             ]},
        ]},
        "unit_cost_usd": 3.50,
        "tags": ["gesture", "proximity", "light", "color", "rgb"],
        "capabilities": {
            "measures": ["light", "color", "proximity", "gesture"],
            "range": {
                "proximity": {"min": 0, "max": 255, "unit": "counts"},
            },
            "resolution_bits": 16,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "TSL2561",
        "manufacturer": "AMS",
        "name": "TSL2561 Light-to-Digital Converter",
        "category": "sensor",
        "sub_type": "light",
        "mounting": "smd",
        "pin_count": 6,
        "datasheet_url": "https://ams.com/documents/20143/36005/TSL2561_DS000110_3-00.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "CHIPLT-6",
        "description": "Light-to-digital converter, 0.1 to 40000 lux",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 3.6,
            "io_voltage_min": 2.7, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.24, "current_draw_max_ma": 0.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x29", "0x39", "0x49"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x80", "value": "0x03", "description": "Power ON"},
                 {"reg_addr": "0x81", "value": "0x02", "description": "402ms integration, 1x gain"},
             ], "delay_after_ms": 410},
        ]},
        "unit_cost_usd": 2.20,
        "tags": ["light", "lux", "ambient"],
        "capabilities": {
            "measures": ["light"],
            "range": {
                "light": {"min": 0.1, "max": 40000, "unit": "lux"},
            },
            "resolution_bits": 16,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "BH1750FVI",
        "manufacturer": "Rohm",
        "name": "BH1750 Ambient Light Sensor",
        "category": "sensor",
        "sub_type": "light",
        "mounting": "smd",
        "pin_count": 6,
        "datasheet_url": "https://www.mouser.com/datasheet/2/348/bh1750fvi-e-186247.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "WSOF-6I",
        "description": "Digital ambient light sensor, 1 to 65535 lux",
        "electrical_ratings": {
            "vdd_min": 2.4, "vdd_max": 3.6,
            "io_voltage_min": 2.4, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.12, "current_draw_max_ma": 0.2,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x23", "0x5C"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x01", "value": "", "description": "Power on"},
                 {"reg_addr": "0x07", "value": "", "description": "Reset data register"},
                 {"reg_addr": "0x10", "value": "", "description": "Continuous high-resolution mode"},
             ], "delay_after_ms": 180},
        ]},
        "unit_cost_usd": 0.80,
        "tags": ["light", "lux", "ambient"],
        "capabilities": {
            "measures": ["light"],
            "range": {
                "light": {"min": 1, "max": 65535, "unit": "lux"},
            },
            "resolution": {
                "light": {"value": 1, "unit": "lux"},
            },
            "resolution_bits": 16,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    # --- Bio / Health ---
    {
        "mpn": "MAX30102",
        "manufacturer": "Maxim Integrated",
        "name": "MAX30102 Pulse Oximeter and Heart-Rate Sensor",
        "category": "sensor",
        "sub_type": "bio",
        "mounting": "smd",
        "pin_count": 14,
        "datasheet_url": "https://www.analog.com/media/en/technical-documentation/data-sheets/MAX30102.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "OLGA-14",
        "description": "Pulse oximetry and heart-rate monitor biosensor",
        "electrical_ratings": {
            "vdd_min": 1.8, "vdd_max": 3.3,
            "io_voltage_min": 1.7, "io_voltage_max": 5.0, "io_voltage_nominal": 1.8,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.6, "current_draw_max_ma": 50.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x57"], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x09", "value": "0x40", "description": "Reset device"}],
             "delay_after_ms": 10},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x09", "value": "0x03", "description": "SpO2 mode (Red + IR)"},
                 {"reg_addr": "0x0A", "value": "0x27", "description": "SpO2: 411us, 4096 range"},
                 {"reg_addr": "0x0C", "value": "0x24", "description": "Red LED 7.2mA"},
                 {"reg_addr": "0x0D", "value": "0x24", "description": "IR LED 7.2mA"},
             ]},
        ]},
        "unit_cost_usd": 7.50,
        "tags": ["pulse", "spo2", "heart-rate", "oximetry", "medical"],
        "capabilities": {
            "measures": ["spo2", "heart_rate"],
            "resolution_bits": 18,
            "sample_rate_hz": 3200,
            "fifo_depth": 32,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    # --- Current / Power monitors ---
    {
        "mpn": "INA226",
        "manufacturer": "Texas Instruments",
        "name": "INA226 Current and Power Monitor",
        "category": "sensor",
        "sub_type": "current-monitor",
        "mounting": "smd",
        "pin_count": 10,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ina226.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "SOT-23-10",
        "description": "36V, 16-bit current/voltage/power monitor with alert, ±0.1% accuracy",
        "electrical_ratings": {
            "vdd_min": 2.7, "vdd_max": 5.5,
            "io_voltage_min": 2.7, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.33, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 2083000,
            "i2c_modes": ["standard", "fast", "fast_plus", "high_speed"],
        },
        "known_i2c_addresses": ["0x40", "0x41", "0x44", "0x45", "0x48", "0x49", "0x4C", "0x4D"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [
                 {"reg_addr": "0x00", "value": "0x4127", "description": "16 avg, 1.1ms conv, continuous"},
                 {"reg_addr": "0x05", "value": "0x0800", "description": "Calibration register"},
             ]},
        ]},
        "unit_cost_usd": 2.10,
        "tags": ["current", "power", "voltage", "monitor"],
        "capabilities": {
            "measures": ["current", "voltage", "power"],
            "range": {
                "voltage": {"min": 0, "max": 36, "unit": "V"},
            },
            "accuracy": {
                "voltage": {"value": 0.1, "unit": "%"},
            },
            "resolution_bits": 16,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "INA219",
        "manufacturer": "Texas Instruments",
        "name": "INA219 Bidirectional Current/Power Monitor",
        "category": "sensor",
        "sub_type": "current-monitor",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ina219.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "SOT-23-8",
        "description": "High-side current/power monitor with I2C interface, 26V max",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 5.5,
            "io_voltage_min": 3.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.0, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 2560000,
            "i2c_modes": ["standard", "fast", "fast_plus", "high_speed"],
        },
        "known_i2c_addresses": [
            "0x40", "0x41", "0x42", "0x43", "0x44", "0x45", "0x46", "0x47",
            "0x48", "0x49", "0x4A", "0x4B", "0x4C", "0x4D", "0x4E", "0x4F",
        ],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x00", "value": "0x8000", "description": "Reset device"}],
             "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x05", "value": "0x1000", "description": "Calibrate 0.1Ω, 3.2A max"},
                 {"reg_addr": "0x00", "value": "0x399F", "description": "32V, /8 gain, 12-bit, continuous"},
             ]},
        ]},
        "unit_cost_usd": 1.80,
        "tags": ["current", "power", "voltage", "monitor"],
        "capabilities": {
            "measures": ["current", "voltage", "power"],
            "range": {
                "voltage": {"min": 0, "max": 26, "unit": "V"},
            },
            "resolution_bits": 12,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "ADS1115",
        "manufacturer": "Texas Instruments",
        "name": "ADS1115 16-Bit 4-Channel ADC",
        "category": "sensor",
        "sub_type": "adc",
        "mounting": "smd",
        "pin_count": 10,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ads1115.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "MSOP-10",
        "description": "16-bit 4-channel delta-sigma ADC with programmable gain amplifier",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 5.5,
            "io_voltage_min": 2.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.15, "current_draw_max_ma": 0.2,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {
            "i2c_max_clock_hz": 3400000,
            "i2c_modes": ["standard", "fast", "fast_plus", "high_speed"],
        },
        "known_i2c_addresses": ["0x48", "0x49", "0x4A", "0x4B"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [{"reg_addr": "0x01", "value": "0xC583",
                         "description": "AIN0, ±2.048V, single-shot, 128SPS"}],
             "delay_after_ms": 8},
        ]},
        "unit_cost_usd": 3.50,
        "tags": ["adc", "analog", "measurement", "16-bit"],
        "capabilities": {
            "measures": ["voltage"],
            "resolution_bits": 16,
            "sample_rate_hz": 860,
            "adc_channels": 4,
            "pga_builtin": True,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    # --- Temperature / 1-Wire ---
    {
        "mpn": "DS18B20",
        "manufacturer": "Maxim Integrated",
        "name": "DS18B20 1-Wire Digital Temperature Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "tht",
        "pin_count": 3,
        "datasheet_url": "https://www.analog.com/media/en/technical-documentation/data-sheets/DS18B20.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["GPIO"],
        "package": "TO-92",
        "description": "Programmable resolution 1-Wire digital thermometer, -55 to +125°C",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 5.5,
            "io_voltage_min": 3.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.0, "current_draw_max_ma": 1.5,
            "temp_min_c": -55.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"gpio_max_freq_hz": 15625},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "description": "1-Wire reset pulse (480µs low)", "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "description": "Skip ROM, start conversion (0x44)", "delay_after_ms": 750},
        ]},
        "unit_cost_usd": 2.00,
        "tags": ["temperature", "1-wire", "waterproof", "environmental"],
        "capabilities": {
            "measures": ["temperature"],
            "range": {
                "temperature": {"min": -55, "max": 125, "unit": "°C"},
            },
            "accuracy": {
                "temperature": {"value": 0.5, "unit": "°C"},
            },
            "resolution": {
                "temperature": {"value": 0.0625, "unit": "°C"},
            },
            "resolution_bits": 12,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "MAX31855KASA+",
        "manufacturer": "Maxim Integrated",
        "name": "MAX31855 Thermocouple Amplifier",
        "category": "sensor",
        "sub_type": "thermocouple",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://www.analog.com/media/en/technical-documentation/data-sheets/MAX31855.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["SPI"],
        "package": "SOIC-8",
        "description": "K-type thermocouple amplifier, -200 to +1350°C, 0.25°C resolution, SPI",
        "electrical_ratings": {
            "vdd_min": 3.0, "vdd_max": 3.6,
            "io_voltage_min": 3.0, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 1.5, "current_draw_max_ma": 2.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"spi_max_clock_hz": 5000000, "spi_modes": [0]},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Read 32-bit SPI frame: thermocouple temp (D[31:18]) + cold junction (D[15:4])"},
        ]},
        "unit_cost_usd": 4.50,
        "tags": ["thermocouple", "temperature", "high-temperature", "k-type", "spi"],
        "capabilities": {
            "measures": ["temperature"],
            "range": {
                "temperature": {"min": -200, "max": 1350, "unit": "°C"},
            },
            "accuracy": {
                "temperature": {"value": 2.0, "unit": "°C"},
            },
            "resolution": {
                "temperature": {"value": 0.25, "unit": "°C"},
            },
            "resolution_bits": 14,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    {
        "mpn": "AM2302",
        "manufacturer": "Aosong",
        "name": "DHT22/AM2302 Temperature and Humidity Sensor",
        "category": "sensor",
        "sub_type": "environmental",
        "mounting": "tht",
        "pin_count": 4,
        "datasheet_url": "https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["GPIO"],
        "package": "4-pin module",
        "description": "Digital temperature and humidity sensor, single-wire protocol",
        "electrical_ratings": {
            "vdd_min": 3.3, "vdd_max": 5.5,
            "io_voltage_min": 3.3, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.5, "current_draw_max_ma": 2.5,
            "temp_min_c": -40.0, "temp_max_c": 80.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "description": "Pull data line low 1-10ms then release"},
            {"phase": "configure", "order": 1,
             "description": "Read 40 bits: 16b humid + 16b temp + 8b checksum"},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["temperature", "humidity", "environmental"],
        "capabilities": {
            "measures": ["temperature", "humidity"],
            "range": {
                "temperature": {"min": -40, "max": 80, "unit": "°C"},
                "humidity": {"min": 0, "max": 100, "unit": "%RH"},
            },
            "accuracy": {
                "temperature": {"value": 0.5, "unit": "°C"},
                "humidity": {"value": 2.0, "unit": "%RH"},
            },
            "resolution": {
                "temperature": {"value": 0.1, "unit": "°C"},
                "humidity": {"value": 0.1, "unit": "%RH"},
            },
            "resolution_bits": 16,
            "sample_rate_hz": 0.5,
            "oversampling": False,
            "fifo_depth": 0,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "HX711",
        "manufacturer": "Avia Semiconductor",
        "name": "HX711 24-Bit ADC for Load Cells",
        "category": "sensor",
        "sub_type": "load-cell",
        "mounting": "smd",
        "pin_count": 16,
        "datasheet_url": "https://cdn.sparkfun.com/datasheets/Sensors/ForceFlex/hx711_english.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["GPIO"],
        "package": "SOP-16",
        "description": "24-bit ADC for weigh scales and load cells",
        "electrical_ratings": {
            "vdd_min": 2.6, "vdd_max": 5.5,
            "io_voltage_min": 2.6, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 1.5, "current_draw_max_ma": 2.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "description": "Power-on wait for DOUT low", "delay_after_ms": 400},
            {"phase": "configure", "order": 1,
             "description": "25 SCK pulses: read 24-bit data + set gain=128 ch.A"},
        ]},
        "unit_cost_usd": 1.20,
        "tags": ["adc", "load-cell", "weight", "scale"],
        "capabilities": {
            "measures": ["weight"],
            "resolution_bits": 24,
            "sample_rate_hz": 80,
            "adc_channels": 2,
            "pga_builtin": True,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": False,
        },
    },
    # --- Touch ---
    {
        "mpn": "MPR121QR2",
        "manufacturer": "NXP",
        "name": "MPR121 12-Channel Capacitive Touch Controller",
        "category": "sensor",
        "sub_type": "touch",
        "mounting": "smd",
        "pin_count": 20,
        "datasheet_url": "https://www.nxp.com/docs/en/data-sheet/MPR121.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "interface_types": ["I2C"],
        "package": "QFN-20",
        "description": "12-electrode capacitive touch sensor with proximity detection, I2C",
        "electrical_ratings": {
            "vdd_min": 1.71, "vdd_max": 3.6,
            "io_voltage_min": 1.71, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.029, "current_draw_max_ma": 1.0,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000, "i2c_modes": ["standard", "fast"]},
        "known_i2c_addresses": ["0x5A", "0x5B", "0x5C", "0x5D"],
        "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "reset", "order": 0,
             "writes": [{"reg_addr": "0x80", "value": "0x63", "description": "Soft reset"}],
             "delay_after_ms": 1},
            {"phase": "configure", "order": 1,
             "writes": [
                 {"reg_addr": "0x5E", "value": "0x8F", "description": "ECR: enable 12 electrodes"},
             ]},
        ]},
        "unit_cost_usd": 2.50,
        "tags": ["touch", "capacitive", "proximity", "12-channel"],
        "capabilities": {
            "measures": ["touch", "proximity"],
            "touch_channels": 12,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    # --- Current sensing ---
    {
        "mpn": "ACS712ELCTR-05B-T",
        "manufacturer": "Allegro MicroSystems",
        "name": "ACS712 Hall-Effect Current Sensor 5A",
        "category": "sensor",
        "sub_type": "current-monitor",
        "mounting": "smd",
        "pin_count": 8,
        "datasheet_url": "https://www.allegromicro.com/en/products/sense/current-sensor-ics/zero-to-fifty-amp-integrated-conductor-sensor-ics/acs712",
        "status": "active",
        "library_support": ["arduino"],
        "interface_types": ["ADC"],
        "package": "SOIC-8",
        "description": "±5A Hall-effect current sensor, 185mV/A, analog output, galvanic isolation",
        "electrical_ratings": {
            "vdd_min": 4.5, "vdd_max": 5.5,
            "io_voltage_nominal": 2.5,
            "current_draw_typical_ma": 10.0, "current_draw_max_ma": 13.5,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {},
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": False, "init_contract_template": {},
        "unit_cost_usd": 2.00,
        "tags": ["current", "hall-effect", "analog", "isolated", "sensing"],
        "capabilities": {
            "measures": ["current"],
            "range": {
                "current": {"min": -5, "max": 5, "unit": "A"},
            },
            "accuracy": {
                "current": {"value": 1.5, "unit": "%"},
            },
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
    },
    {
        "mpn": "ADS8681",
        "manufacturer": "Texas Instruments",
        "name": "ADS8681 16-Bit 1MSPS SPI ADC",
        "category": "sensor",
        "sub_type": "adc",
        "mounting": "smd",
        "pin_count": 16,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ads8681.pdf",
        "status": "active",
        "library_support": ["arduino", "stm32-hal", "zephyr"],
        "interface_types": ["SPI"],
        "package": "TSSOP-16",
        "description": "16-bit 1MSPS SAR ADC with SPI interface, ±10V or ±5V input range, internal reference",
        "electrical_ratings": {
            "vdd_min": 4.75, "vdd_max": 5.25,
            "io_voltage_min": 1.65, "io_voltage_max": 5.25, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 7.0, "current_draw_max_ma": 10.0,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {
            "spi_max_clock_hz": 70000000, "spi_modes": [0, 1],
        },
        "known_i2c_addresses": [], "i2c_address_selectable": False,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "description": "Send 32-bit SPI frame: 4-bit CMD + 12-bit data + 16-bit result",
             "delay_after_ms": 1},
        ]},
        "unit_cost_usd": 6.50,
        "tags": ["adc", "spi", "16-bit", "high-speed", "data-acquisition", "sar"],
        "capabilities": {
            "measures": ["voltage"],
            "resolution_bits": 16,
            "sample_rate_hz": 1000000,
            "adc_channels": 1,
            "pga_builtin": False,
            "internal_reference": True,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": False,
        },
    },

    # --- Seed Expansion (DB-6) ---
    {
        "mpn": "BH1750",
        "manufacturer": "ROHM Semiconductor",
        "name": "BH1750 Ambient Light Sensor",
        "category": "sensor",
        "sub_type": "light",
        "interface_types": ["I2C"],
        "package": "WSOF-6I",
        "mounting": "smd",
        "pin_count": 6,
        "description": "Digital 16-bit ambient light sensor, 1-65535 lux, I2C",
        "electrical_ratings": {
            "vdd_min": 2.4, "vdd_max": 3.6,
            "io_voltage_min": 1.8, "io_voltage_max": 3.6, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": False,
            "current_draw_typical_ma": 0.12, "current_draw_max_ma": 0.19,
            "temp_min_c": -40.0, "temp_max_c": 85.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000},
        "known_i2c_addresses": ["0x23", "0x5C"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [{"reg_addr": "0x10", "value": "0x00", "description": "Continuously H-Res mode (1 lux resolution)"}],
             "delay_after_ms": 180},
        ]},
        "unit_cost_usd": 0.55,
        "datasheet_url": "https://www.rohm.com/datasheet/BH1750FVI/bh1750fvi-e.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython"],
        "capabilities": {
            "measures": ["illuminance"],
            "range": {"illuminance": {"min": 1, "max": 65535, "unit": "lux"}},
            "resolution_bits": 16,
            "interrupt_pin": False,
            "self_test": False,
            "calibration_factory": True,
        },
        "tags": ["light", "lux", "ambient", "illuminance"],
    },
    {
        "mpn": "ADS1115",
        "manufacturer": "Texas Instruments",
        "name": "ADS1115 16-bit 4-ch ADC with PGA",
        "category": "sensor",
        "sub_type": "adc",
        "interface_types": ["I2C"],
        "package": "SSOP-16",
        "mounting": "smd",
        "pin_count": 16,
        "description": "16-bit 860SPS ADC, 4-ch differential or 8 single-ended, with PGA and comparator",
        "electrical_ratings": {
            "vdd_min": 2.0, "vdd_max": 5.5,
            "io_voltage_min": 2.0, "io_voltage_max": 5.5, "io_voltage_nominal": 3.3,
            "is_5v_tolerant": True,
            "current_draw_typical_ma": 0.15, "current_draw_max_ma": 0.25,
            "temp_min_c": -40.0, "temp_max_c": 125.0,
        },
        "timing_caps": {"i2c_max_clock_hz": 400000},
        "known_i2c_addresses": ["0x48", "0x49", "0x4A", "0x4B"], "i2c_address_selectable": True,
        "init_contract_coverage": True,
        "init_contract_template": {"phases": [
            {"phase": "configure", "order": 0,
             "writes": [{"reg_addr": "0x01", "value": "0xC3E3", "description": "Config: MUX=AIN0, PGA=±4.096V, 860SPS, comp disabled"}],
             "delay_after_ms": 2},
        ]},
        "unit_cost_usd": 1.85,
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ads1115.pdf",
        "status": "active",
        "library_support": ["arduino", "micropython", "circuitpython", "esp-idf"],
        "capabilities": {
            "measures": ["voltage"],
            "resolution_bits": 16,
            "sample_rate_hz": 860,
            "adc_channels": 4,
            "pga_builtin": True,
            "pga_gains": [0.256, 0.512, 1.024, 2.048, 4.096, 6.144],
            "internal_reference": True,
            "interrupt_pin": True,
            "self_test": False,
            "calibration_factory": False,
        },
        "tags": ["adc", "i2c", "16-bit", "pga", "precision", "analog-input"],
    },
]
