# SPDX-License-Identifier: AGPL-3.0-or-later
"""BME280 — Device Software Profile."""
from shared.knowledge.software_profile_schema import (
    DeviceSoftwareProfile,
    DriverFootprint,
    DriverOption,
    DriverQualityScore,
    IntegrationType,
    LicenseCompatibility,
    MaintenanceStatus,
    SourceType,
)

PROFILE = DeviceSoftwareProfile(
    component_mpn="BME280",
    protocol="I2C",
    default_driver_key="bosch_official",
    api_contract_id="temperature_sensor_v1",
    driver_options=[
        DriverOption(
            name="Bosch Official C Driver",
            key="bosch_official",
            source_type=SourceType.git,
            source_url="https://github.com/BoschSensortec/BME280_driver",
            license="BSD-3-Clause",
            license_compatibility=LicenseCompatibility.compatible,
            maturity="high",
            ecosystem=["baremetal", "Zephyr", "ESP-IDF", "Pico-SDK"],
            supported_targets=["esp32", "stm32", "rp2040", "nrf52"],
            integration_type=IntegrationType.source_embed,
            last_checked_version="v3.5.1",
            last_checked_date="2026-01-15",
            maintenance_status=MaintenanceStatus.active,
            known_issues=[],
            footprint=DriverFootprint(flash_bytes=8200, ram_bytes=512),
            quality_score=DriverQualityScore(
                test_pass_rate=0.95,
                maintenance_factor=0.90,
                ecosystem_support=0.85,
                community_adoption=0.80,
                license_score=1.0,
            ),
        ),
        DriverOption(
            name="Adafruit BME280 Library",
            key="adafruit",
            source_type=SourceType.git,
            source_url="https://github.com/adafruit/Adafruit_BME280_Library",
            license="MIT",
            license_compatibility=LicenseCompatibility.compatible,
            maturity="high",
            ecosystem=["Arduino"],
            supported_targets=["esp32", "rp2040"],
            integration_type=IntegrationType.package_manager,
            last_checked_version="v2.2.4",
            last_checked_date="2026-01-15",
            maintenance_status=MaintenanceStatus.active,
            known_issues=["Arduino-only, not portable to baremetal"],
            footprint=DriverFootprint(flash_bytes=12400, ram_bytes=1024),
            quality_score=DriverQualityScore(
                test_pass_rate=0.85,
                maintenance_factor=0.85,
                ecosystem_support=0.50,
                community_adoption=0.90,
                license_score=1.0,
            ),
        ),
        DriverOption(
            name="Zephyr In-Tree Sensor Driver",
            key="zephyr_intree",
            source_type=SourceType.package_registry,
            source_url="zephyr://drivers/sensor/bme280",
            license="Apache-2.0",
            license_compatibility=LicenseCompatibility.compatible,
            maturity="high",
            ecosystem=["Zephyr"],
            supported_targets=["nrf52", "stm32"],
            integration_type=IntegrationType.package_manager,
            last_checked_version="v3.6.0",
            last_checked_date="2026-01-15",
            maintenance_status=MaintenanceStatus.active,
            quality_score=DriverQualityScore(
                test_pass_rate=0.95,
                maintenance_factor=0.95,
                ecosystem_support=0.40,
                community_adoption=0.70,
                license_score=1.0,
            ),
        ),
    ],
)

from shared.knowledge.software_profiles import register
register(PROFILE)
