# SPDX-License-Identifier: AGPL-3.0-or-later
"""SX1276 LoRa Transceiver — Device Software Profile."""
from shared.knowledge.software_profile_schema import (
    DeviceSoftwareProfile,
    DriverFootprint,
    DriverOption,
    DriverQualityScore,
    IntegrationType,
    LicenseCompatibility,
    MaintenanceStatus,
    SourceType,
)

PROFILE = DeviceSoftwareProfile(
    component_mpn="SX1276",
    protocol="SPI",
    default_driver_key="radiolib",
    api_contract_id="lora_transceiver_v1",
    driver_options=[
        DriverOption(
            name="RadioLib — Universal Radio Library",
            key="radiolib",
            source_type=SourceType.git,
            source_url="https://github.com/jgromes/RadioLib",
            license="MIT",
            license_compatibility=LicenseCompatibility.compatible,
            maturity="high",
            ecosystem=["Arduino", "ESP-IDF", "Pico-SDK"],
            supported_targets=["esp32", "stm32", "rp2040"],
            integration_type=IntegrationType.source_embed,
            last_checked_version="v6.6.0",
            last_checked_date="2026-01-15",
            maintenance_status=MaintenanceStatus.active,
            footprint=DriverFootprint(flash_bytes=45000, ram_bytes=4096),
            quality_score=DriverQualityScore(
                test_pass_rate=0.90,
                maintenance_factor=0.95,
                ecosystem_support=0.85,
                community_adoption=0.90,
                license_score=1.0,
            ),
        ),
        DriverOption(
            name="LMIC — LoRaWAN MAC in C",
            key="lmic",
            source_type=SourceType.git,
            source_url="https://github.com/mcci-catena/arduino-lmic",
            license="MIT",
            license_compatibility=LicenseCompatibility.compatible,
            maturity="high",
            ecosystem=["Arduino", "baremetal"],
            supported_targets=["esp32", "stm32", "rp2040"],
            integration_type=IntegrationType.source_embed,
            last_checked_version="v4.1.1",
            last_checked_date="2026-01-15",
            maintenance_status=MaintenanceStatus.active,
            known_issues=["Heavy memory usage", "Complex configuration"],
            footprint=DriverFootprint(flash_bytes=65000, ram_bytes=8192),
            quality_score=DriverQualityScore(
                test_pass_rate=0.85,
                maintenance_factor=0.80,
                ecosystem_support=0.60,
                community_adoption=0.85,
                license_score=1.0,
            ),
        ),
        DriverOption(
            name="Semtech Official SX1276 Driver",
            key="semtech_official",
            source_type=SourceType.git,
            source_url="https://github.com/Lora-net/LoRaMac-node",
            license="BSD-3-Clause",
            license_compatibility=LicenseCompatibility.compatible,
            maturity="high",
            ecosystem=["baremetal"],
            supported_targets=["stm32"],
            integration_type=IntegrationType.source_embed,
            last_checked_version="v4.7.0",
            last_checked_date="2026-01-15",
            maintenance_status=MaintenanceStatus.active,
            footprint=DriverFootprint(flash_bytes=80000, ram_bytes=10000),
            quality_score=DriverQualityScore(
                test_pass_rate=0.90,
                maintenance_factor=0.85,
                ecosystem_support=0.30,
                community_adoption=0.70,
                license_score=1.0,
            ),
        ),
    ],
)

from shared.knowledge.software_profiles import register
register(PROFILE)
