// Auto-generated by boardsmith-fw from HIR v1.1.0
// Source: prompt
// Track: B
#include <Arduino.h>
#include "hardware.h"

// Components: ESP32 Wi-Fi+BT Module, BME280 Pressure/Humidity/Temperature Sensor, 3.3kΩ Resistor (i2c_pullup_sda_i2c0), 3.3kΩ Resistor (i2c_pullup_scl_i2c0), 100nF Capacitor (decoupling_vdd_ESP32_WROOM_32), 100nF Capacitor (decoupling_vdd_BME280), 10uF Capacitor (bulk_cap_VIN_5V), 10uF Capacitor (bulk_cap_3V3_REG), 10uF Capacitor (ldo_input_cap_U_LDO1), 10uF Capacitor (ldo_output_bulk_U_LDO1), 100nF Capacitor (ldo_output_noise_U_LDO1), AP2112K-3.3TRG1 LDO 5V→3.3V
// Buses: i2c0

extern void init_all_peripherals();

void setup() {
    Serial.begin(115200);
    Serial.println("boardsmith-fw generated firmware");
    Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);
    init_all_peripherals();
    Serial.println("Initialization complete.");
}

void loop() {
    // Application logic here
    delay(1000);
}
