# SPDX-License-Identifier: AGPL-3.0-or-later
"""generate_from_hir — deterministic firmware code generation from HIR.

Currently supports ESP32 (Arduino/ESP-IDF style C) as the primary target.
"""
from __future__ import annotations

import textwrap
from dataclasses import dataclass
from pathlib import Path

from synth_core.models.hir import HIR, BusContract, InitContract, InitPhase


def _resolve_adapter(component_mpn: str, target_sdk: str = "esp-idf"):
    """Try to resolve a LibraryAdapter for a component via the binding layer."""
    try:
        from shared.knowledge.software_profiles import get as get_sw_profile
        from shared.knowledge.contracts import get_registry
    except ImportError:
        return None

    sw_profile = get_sw_profile(component_mpn)
    if sw_profile is None:
        return None

    contract_id = sw_profile.api_contract_id
    if not contract_id:
        return None

    return get_registry().resolve_adapter(contract_id, target_sdk)


@dataclass
class GenerationSummary:
    target: str
    out_dir: Path
    files_written: list[str]
    warnings: list[str]


def generate_from_hir(hir: HIR, target: str, out_dir: Path, strict: bool = True) -> GenerationSummary:
    """Generate firmware project from canonical HIR.

    Args:
        hir: validated HIR object
        target: target platform identifier ("esp32", "stm32f103")
        out_dir: directory where firmware files are written
        strict: if True, raises on error-level constraint failures

    Returns:
        GenerationSummary with written files and any warnings
    """
    from synth_core.hir_bridge.validator import validate_hir, Severity, ConstraintStatus

    report = validate_hir(hir, validate_schema=False)
    if strict and not report.valid:
        errors = [d for d in report.constraints
                  if d.severity == Severity.error and d.status == ConstraintStatus.fail]
        msgs = "; ".join(e.description for e in errors)
        raise ValueError(f"HIR has {len(errors)} error(s), cannot generate (strict=True): {msgs}")

    out_dir.mkdir(parents=True, exist_ok=True)
    warnings: list[str] = [c.description for c in report.constraints if c.severity == Severity.warning]

    target_lower = target.lower()
    if "esp32" in target_lower:
        files = _gen_esp32(hir, out_dir)
    elif "stm32" in target_lower:
        files = _gen_stm32(hir, out_dir)
    else:
        files = _gen_generic(hir, out_dir, target)

    return GenerationSummary(target=target, out_dir=out_dir, files_written=files, warnings=warnings)


# ---------------------------------------------------------------------------
# ESP32 code generator
# ---------------------------------------------------------------------------

def _gen_esp32(hir: HIR, out_dir: Path) -> list[str]:
    files: list[str] = []

    # main.cpp (Arduino-style)
    main_code = _esp32_main(hir)
    (out_dir / "main.cpp").write_text(main_code)
    files.append("main.cpp")

    # hardware.h
    hw_h = _esp32_hardware_h(hir)
    (out_dir / "hardware.h").write_text(hw_h)
    files.append("hardware.h")

    # init.cpp
    init_cpp = _esp32_init_cpp(hir)
    (out_dir / "init.cpp").write_text(init_cpp)
    files.append("init.cpp")

    # CMakeLists.txt (ESP-IDF style)
    cmake = _esp32_cmake(out_dir.name)
    (out_dir / "CMakeLists.txt").write_text(cmake)
    files.append("CMakeLists.txt")

    return files


def _esp32_main(hir: HIR) -> str:
    comp_names = [c.name for c in hir.components]
    buses = [bc.bus_name for bc in hir.bus_contracts]

    lines = [
        "// Auto-generated by boardsmith-fw from HIR v" + hir.version,
        "// Source: " + hir.source,
        "// Track: " + hir.metadata.track,
        "#include <Arduino.h>",
        '#include "hardware.h"',
        "",
        "// Components: " + ", ".join(comp_names),
        "// Buses: " + ", ".join(buses),
        "",
        "extern void init_all_peripherals();",
        "",
        "void setup() {",
        "    Serial.begin(115200);",
        "    Serial.println(\"boardsmith-fw generated firmware\");",
        "    Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);",
        "    init_all_peripherals();",
        "    Serial.println(\"Initialization complete.\");",
        "}",
        "",
        "void loop() {",
        "    // Application logic here",
        "    delay(1000);",
        "}",
    ]
    return "\n".join(lines) + "\n"


def _esp32_hardware_h(hir: HIR) -> str:
    lines = [
        "// Auto-generated hardware pin definitions",
        "#pragma once",
        "#include <Wire.h>",
        "#include <SPI.h>",
        "",
    ]

    # Pin assignments from bus contracts
    i2c_sda = "21"
    i2c_scl = "22"
    for bc in hir.bus_contracts:
        if bc.bus_type.upper() == "I2C":
            i2c_sda = bc.pin_assignments.get("SDA", bc.pin_assignments.get("sda", "21"))
            i2c_scl = bc.pin_assignments.get("SCL", bc.pin_assignments.get("scl", "22"))
            break

    lines += [
        f"#define PIN_I2C_SDA  {i2c_sda}",
        f"#define PIN_I2C_SCL  {i2c_scl}",
        "",
    ]

    # I2C addresses
    for bc in hir.bus_contracts:
        if bc.bus_type.upper() == "I2C":
            for sid, addr in bc.slave_addresses.items():
                safe = sid.upper().replace("-", "_").replace(" ", "_")
                lines.append(f"#define I2C_ADDR_{safe}  {addr}")
    lines.append("")

    # SPI CS pins
    for bc in hir.bus_contracts:
        if bc.bus_type.upper() == "SPI":
            for sid in bc.slave_ids:
                cs = bc.pin_assignments.get(f"CS_{sid}", bc.pin_assignments.get("CS", "5"))
                safe = sid.upper().replace("-", "_").replace(" ", "_")
                lines.append(f"#define PIN_SPI_CS_{safe}  {cs}")
    lines.append("")

    return "\n".join(lines)


def _esp32_init_cpp(hir: HIR) -> str:
    lines = [
        "// Auto-generated peripheral initialization",
        '#include "hardware.h"',
        "#include <Arduino.h>",
        "",
    ]

    for ic in hir.init_contracts:
        comp = next((c for c in hir.components if c.id == ic.component_id), None)
        comp_name = ic.component_name or (comp.name if comp else ic.component_id)
        safe_name = ic.component_id.replace("-", "_").replace(" ", "_")
        comp_mpn = comp.mpn if comp else comp_name.split()[0].upper()

        # Try binding layer: resolve adapter for this component
        adapter = _resolve_adapter(comp_mpn, "esp-idf")

        lines += ["", f"// --- {comp_name} initialization ---"]

        if adapter and "init" in adapter.capability_mappings:
            # Adapter-driven init (contract → adapter → code)
            lines.append(f"// Driver: {adapter.driver_option_key} via {adapter.adapter_id}")
            if adapter.init_template:
                for comment_line in adapter.init_template.split("\n"):
                    lines.append(f"// {comment_line}")
            lines.append(f"static void init_{safe_name}() {{")
            init_code = adapter.capability_mappings["init"]
            for code_line in init_code.template.split("\n"):
                lines.append(f"    {code_line}")
            lines.append("}")
        else:
            # Fallback: register-level init from InitContract phases
            lines.append(f"static void init_{safe_name}() {{")
            sorted_phases = sorted(ic.phases, key=lambda p: p.order)
            for ph in sorted_phases:
                lines.append(f"    // Phase: {ph.phase.value}")
                if ph.delay_after_ms:
                    lines.append(f"    delay({ph.delay_after_ms});")
                for w in ph.writes:
                    lines.append(f"    // Write {w.reg_addr} = {w.value}" + (f" — {w.description}" if w.description else ""))
                    lines.append(f"    _i2c_write(I2C_ADDR_{ic.component_id.upper().replace('-', '_').replace(' ', '_')}, {w.reg_addr}, {w.value});")
                for r in ph.reads:
                    if r.expected_value:
                        lines.append(f"    // Read {r.reg_addr}, expect {r.expected_value}" + (f" — {r.description}" if r.description else ""))
                        lines.append(f"    _i2c_verify(I2C_ADDR_{ic.component_id.upper().replace('-', '_').replace(' ', '_')}, {r.reg_addr}, {r.expected_value});")
            lines.append("}")

    # Helper stubs
    lines += [
        "",
        "// I2C helpers",
        "static void _i2c_write(uint8_t addr, uint8_t reg, uint8_t val) {",
        "    Wire.beginTransmission(addr);",
        "    Wire.write(reg);",
        "    Wire.write(val);",
        "    Wire.endTransmission();",
        "}",
        "",
        "static uint8_t _i2c_read(uint8_t addr, uint8_t reg) {",
        "    Wire.beginTransmission(addr);",
        "    Wire.write(reg);",
        "    Wire.endTransmission(false);",
        "    Wire.requestFrom(addr, (uint8_t)1);",
        "    return Wire.read();",
        "}",
        "",
        "static bool _i2c_verify(uint8_t addr, uint8_t reg, uint8_t expected) {",
        "    uint8_t val = _i2c_read(addr, reg);",
        "    if (val != expected) {",
        "        Serial.printf(\"Verify failed: addr=0x%02X reg=0x%02X got=0x%02X expected=0x%02X\\n\",",
        "                      addr, reg, val, expected);",
        "        return false;",
        "    }",
        "    return true;",
        "}",
        "",
        "void init_all_peripherals() {",
    ]
    for ic in hir.init_contracts:
        safe_name = ic.component_id.replace("-", "_").replace(" ", "_")
        lines.append(f"    init_{safe_name}();")
    lines += ["}", ""]

    return "\n".join(lines)


def _esp32_cmake(project_name: str) -> str:
    return textwrap.dedent(f"""\
        cmake_minimum_required(VERSION 3.16)
        project({project_name})
        set(CMAKE_CXX_STANDARD 17)

        # ESP-IDF / Arduino component list
        set(COMPONENT_SRCS "main.cpp" "init.cpp")
        set(COMPONENT_ADD_INCLUDEDIRS ".")

        include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
    """)


# ---------------------------------------------------------------------------
# STM32 stub generator
# ---------------------------------------------------------------------------

def _gen_stm32(hir: HIR, out_dir: Path) -> list[str]:
    content = textwrap.dedent(f"""\
        // Auto-generated by boardsmith-fw for STM32 target
        // HIR version: {hir.version}
        #include "stm32f1xx_hal.h"

        void init_all_peripherals(void) {{
            // TODO: implement per-component init
        }}

        int main(void) {{
            HAL_Init();
            init_all_peripherals();
            while (1) {{ }}
        }}
    """)
    (out_dir / "main.c").write_text(content)
    return ["main.c"]


# ---------------------------------------------------------------------------
# Generic stub
# ---------------------------------------------------------------------------

def _gen_generic(hir: HIR, out_dir: Path, target: str) -> list[str]:
    content = textwrap.dedent(f"""\
        // Auto-generated by boardsmith-fw for target: {target}
        // HIR version: {hir.version}
        // Components: {[c.name for c in hir.components]}

        void init_all_peripherals() {{
            // TODO: implement for {target}
        }}

        int main() {{
            init_all_peripherals();
            return 0;
        }}
    """)
    (out_dir / "main.c").write_text(content)
    return ["main.c"]
