// Auto-generated by boardsmith-fw from HIR v1.1.0
// Source: prompt
// Track: B
#include <Arduino.h>
#include "hardware.h"

// Components: ESP32 Wi-Fi+BT Module, BME280 Pressure/Humidity/Temperature Sensor, BME680 Environmental Sensor + VOC Gas, UART Header Connector 4-Pin 2.54mm, USB Type-C Receptacle Connector, BSS138 N-Channel MOSFET Level Shifter, 3.3kΩ Resistor (i2c_pullup_sda_i2c0), 3.3kΩ Resistor (i2c_pullup_scl_i2c0), 100nF Capacitor (decoupling_vdd_ESP32_WROOM_32), 100nF Capacitor (decoupling_vdd_BME280), 100nF Capacitor (decoupling_vdd_BME680), 100nF Capacitor (decoupling_vdd_CONN_UART_4PIN), 100nF Capacitor (decoupling_vdd_USB_C_CONN), 10uF Capacitor (bulk_cap_VIN_5V), 10uF Capacitor (bulk_cap_3V3_REG), 10uF Capacitor (ldo_input_cap_U_LDO1), 10uF Capacitor (ldo_output_bulk_U_LDO1), 100nF Capacitor (ldo_output_noise_U_LDO1), 10kΩ Resistor (levelshift_pullup_USB-C-CONN_3.3V), 10kΩ Resistor (levelshift_pullup_USB-C-CONN_5.0V), 470Ω Resistor (uart_tx_series_uart0), 470Ω Resistor (uart_rx_series_uart0), 5.1kΩ Resistor (usbc_cc1_pulldown), 5.1kΩ Resistor (usbc_cc2_pulldown), AMS1117-3.3 LDO 5V→3.3V
// Buses: i2c0, uart0

extern void init_all_peripherals();

void setup() {
    Serial.begin(115200);
    Serial.println("boardsmith-fw generated firmware");
    Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);
    init_all_peripherals();
    Serial.println("Initialization complete.");
}

void loop() {
    // Application logic here
    delay(1000);
}
